"""Applied post-2160 technology programmes for A-Discord.

These short trees follow the useful part of The Darkest Hour's design:
technologies should change what a country can do, improve a concrete formation
or institution, and occasionally fire a bounded one-time effect.  They are
optional programmes rather than extra mandatory rungs in every old branch.
"""

APPLIED_YEARS = (2160, 2163, 2163, 2167, 2167, 2171, 2171, 2175)


APPLIED_PROGRAMMES = (
    {
        "key": "combat_medicine",
        "file": "ADISCORD_infantry.txt",
        "folders": ("infantry_folder",),
        "ru": "Боевая медицина",
        "en": "Combat Medicine",
        "profile": "protection",
        "description_ru": "сохраняет личный состав, опыт подразделений и темп возвращения раненых в строй",
        "description_en": "preserves manpower and unit experience while returning casualties to duty faster",
        "techs": (
            ("trauma_registry_networks", "Полевые реестры травм", "Field Trauma Registries", "tech_field_hospital"),
            ("rapid_casualty_corridors", "Коридоры быстрой эвакуации", "Rapid Casualty Corridors", "motorised_infantry"),
            ("forward_surgical_cells", "Передовые хирургические ячейки", "Forward Surgical Cells", "tech_field_hospital"),
            ("predictive_blood_logistics", "Предиктивная логистика крови", "Predictive Blood Logistics", "tech_logistics_company"),
            ("regenerative_surgery_modules", "Регенеративные хирургические модули", "Regenerative Surgery Modules", "tech_field_hospital"),
            ("autonomous_medevac_routing", "Автономная маршрутизация эвакуации", "Autonomous Medevac Routing", "radio"),
            ("sealed_recovery_wards", "Герметичные восстановительные палаты", "Sealed Recovery Wards", "engineers"),
            ("distributed_combat_medicine", "Распределённая боевая медицина", "Distributed Combat Medicine", "tech_field_hospital"),
        ),
    },
    {
        "key": "combat_engineering",
        "file": "ADISCORD_logistics_trains.txt",
        "folders": ("support_folder",),
        "ru": "Инженерное обеспечение",
        "en": "Combat Engineering",
        "profile": "support",
        "description_ru": "связывает фортификацию, полевой ремонт и инженерную поддержку наступления",
        "description_en": "connects fortification, field repair, and engineering support for offensive operations",
        "techs": (
            ("battle_damage_survey_teams", "Группы оценки боевых повреждений", "Battle-damage Survey Teams", "engineers"),
            ("assault_breaching_packages", "Штурмовые комплекты разграждения", "Assault Breaching Packages", "engineers2"),
            ("mobile_restoration_columns", "Мобильные восстановительные колонны", "Mobile Restoration Columns", "tech_maintenance_company"),
            ("robotic_obstacle_clearance", "Роботизированное разминирование", "Robotic Obstacle Clearance", "engineers3"),
            ("predictive_spare_part_pools", "Предиктивные фонды запчастей", "Predictive Spare-part Pools", "tech_maintenance_company"),
            ("autonomous_bridgehead_fabrication", "Автономное оборудование плацдармов", "Autonomous Bridgehead Fabrication", "engineers4"),
            ("self_repairing_field_depots", "Самовосстанавливающиеся полевые базы", "Self-repairing Field Depots", "tech_maintenance_company"),
            ("integrated_engineer_command", "Единое инженерное командование", "Integrated Engineer Command", "engineers4"),
        ),
    },
    {
        "key": "counter_drone_warfare",
        "file": "ADISCORD_electronics.txt",
        "folders": ("electronics_folder",),
        "ru": "РЭБ и противодроновая борьба",
        "en": "Electronic and Counter-drone Warfare",
        "profile": "signals",
        "description_ru": "противопоставляет активное подавление защищённым сетям обнаружения и управления",
        "description_en": "pits active suppression against resilient detection and command networks",
        "techs": (
            ("spectrum_threat_libraries", "Библиотеки спектральных угроз", "Spectrum Threat Libraries", "radio"),
            ("offensive_jamming_cells", "Ячейки наступательного подавления", "Offensive Jamming Cells", "basic_decryption"),
            ("passive_drone_detection_meshes", "Пассивные сети обнаружения дронов", "Passive Drone-detection Meshes", "radio_detection"),
            ("cognitive_emitter_spoofing", "Когнитивная подмена излучателей", "Cognitive Emitter Spoofing", "improved_decryption"),
            ("hardened_command_waveforms", "Защищённые командные сигналы", "Hardened Command Waveforms", "improved_encryption"),
            ("autonomous_jamming_swarms", "Автономные рои подавления", "Autonomous Jamming Swarms", "advanced_decryption"),
            ("distributed_counter_uas_grid", "Распределённая сеть противодействия БПЛА", "Distributed Counter-UAS Grid", "centimetric_radar"),
            ("adaptive_spectrum_dominance", "Адаптивное господство в спектре", "Adaptive Spectrum Dominance", "advanced_encryption"),
        ),
    },
    {
        "key": "air_mobility",
        "file": "ADISCORD_air.txt",
        "folders": ("air_techs_folder", "bba_air_techs_folder"),
        "ru": "Воздушная мобильность",
        "en": "Air Mobility",
        "profile": "air_support",
        "description_ru": "ускоряет переброску, снабжение и координацию войск с воздуха",
        "description_en": "accelerates airborne movement, resupply, and coordination of ground forces",
        "techs": (
            ("restored_airlift_planning", "Восстановленное планирование воздушных перевозок", "Restored Airlift Planning", "radio"),
            ("forward_tiltrotor_basing", "Передовое базирование конвертопланов", "Forward Tiltrotor Basing", "bba_tech_engines_1"),
            ("autonomous_cargo_gliders", "Автономные грузовые планеры", "Autonomous Cargo Gliders", "bba_tech_aircraft_construction"),
            ("vertical_envelopment_control", "Управление вертикальным охватом", "Vertical Envelopment Control", "radio"),
            ("precision_aerial_resupply", "Точное воздушное снабжение", "Precision Aerial Resupply", "bba_tech_armor_piercing_bombs"),
            ("distributed_assault_landing_zones", "Распределённые зоны высадки", "Distributed Assault Landing Zones", "centimetric_radar"),
            ("persistent_airbridge_networks", "Постоянные воздушные мосты", "Persistent Airbridge Networks", "advanced_centimetric_radar"),
            ("autonomous_theater_airlift", "Автономные театральные перевозки", "Autonomous Theater Airlift", "advanced_computing_machine"),
        ),
    },
    {
        "key": "riverine_warfare",
        "file": "ADISCORD_naval.txt",
        "folders": ("naval_folder", "mtgnavalfolder", "mtgnavalsupportfolder"),
        "ru": "Речные и десантные операции",
        "en": "Riverine and Amphibious Operations",
        "profile": "naval_support",
        "description_ru": "развивает высадку, огневую поддержку побережья и действия малых сил на мелководье",
        "description_en": "develops landing operations, coastal fire support, and shallow-water combat",
        "techs": (
            ("shallow_water_navigation_tables", "Таблицы мелководной навигации", "Shallow-water Navigation Tables", "sonar"),
            ("armored_river_patrols", "Бронированные речные патрули", "Armored River Patrols", "basic_cruiser_armor_scheme"),
            ("modular_landing_causeways", "Модульные десантные эстакады", "Modular Landing Causeways", "engineers"),
            ("drone_guided_river_ambushes", "Дроновое наведение речных засад", "Drone-guided River Ambushes", "advanced_sonar"),
            ("rapid_beachhead_logistics", "Быстрая логистика плацдарма", "Rapid Beachhead Logistics", "tech_logistics_company"),
            ("autonomous_littoral_fire_control", "Автономное управление огнём в прибрежной зоне", "Autonomous Littoral Fire Control", "advanced_centimetric_radar"),
            ("self_deploying_floating_depots", "Саморазвёртывающиеся плавучие базы", "Self-deploying Floating Depots", "naval_air_operations"),
            ("integrated_river_sea_command", "Единое речное и морское командование", "Integrated River-Sea Command", "modern_sonar"),
        ),
    },
    {
        "key": "unmanned_ground_systems",
        "file": "ADISCORD_armor.txt",
        "folders": ("armour_folder", "nsb_armour_folder"),
        "ru": "Беспилотные наземные системы",
        "en": "Unmanned Ground Systems",
        "profile": "recon_armor",
        "description_ru": "создаёт разведывательные, ремонтные и ударные машины без экипажа",
        "description_en": "develops crewless reconnaissance, recovery, and combat vehicles",
        "techs": (
            ("teleoperated_scout_carts", "Телеуправляемые разведывательные машины", "Teleoperated Scout Vehicles", "recon"),
            ("armed_recon_drones", "Вооружённые разведывательные платформы", "Armed Recon Vehicles", "sp_armored_signal"),
            ("autonomous_recovery_tractors", "Автономные эвакуационные тягачи", "Autonomous Recovery Tractors", "sp_armored_maintenance"),
            ("hunter_killer_ground_pairs", "Наземные пары поиска и поражения", "Ground Hunter-killer Teams", "armored_operations"),
            ("robotic_damage_control_crews", "Роботизированные аварийные команды", "Robotic Damage-control Crews", "sp_armored_engineer"),
            ("distributed_ground_swarm_control", "Распределённое управление наземным роем", "Distributed Ground-swarm Control", "sp_armored_signal"),
            ("self_recovering_combat_vehicles", "Самоэвакуирующиеся боевые машины", "Self-recovering Combat Vehicles", "sp_armored_maintenance"),
            ("autonomous_combined_arms_mesh", "Автономная общевойсковая сеть", "Autonomous Combined-arms Mesh", "armored_operations"),
        ),
    },
    {
        "key": "officer_training",
        "file": "ADISCORD_logistics_trains.txt",
        "folders": ("support_folder",),
        "ru": "Подготовка командного состава",
        "en": "Officer Training",
        "profile": "support",
        "description_ru": "улучшает штабную работу и повышает характеристики ограниченного числа случайных генералов",
        "description_en": "improves staff work and the abilities of a limited number of random generals",
        "techs": (
            ("reconstituted_staff_academies", "Восстановленные штабные академии", "Reconstituted Staff Academies", "radio"),
            ("assault_command_curriculum", "Курс наступательного командования", "Assault Command Curriculum", "armored_operations"),
            ("defensive_command_curriculum", "Курс оборонительного командования", "Defensive Command Curriculum", "engineers"),
            ("operational_planning_exercises", "Оперативные штабные учения", "Operational Planning Exercises", "computing_machine"),
            ("theater_logistics_wargames", "Тыловые манёвры театра", "Theater Logistics Wargames", "tech_logistics_company"),
            ("rotational_front_commands", "Ротация фронтовых командований", "Rotational Front Commands", "radio"),
            ("predictive_staff_colleges", "Коллегии предиктивного планирования", "Predictive Staff Colleges", "advanced_computing_machine"),
            ("adaptive_general_staff", "Адаптивный генеральный штаб", "Adaptive General Staff", "advanced_encryption"),
        ),
    },
)


APPLIED_EFFECTS = {
    "trauma_registry_networks": ("field_hospital = { casualty_trickleback = 0.03 experience_loss_factor = -0.02 }", "category_all_infantry = { default_morale = 0.02 }"),
    "rapid_casualty_corridors": ("field_hospital = { casualty_trickleback = 0.05 supply_consumption = -0.02 }", "land_reinforce_rate = 0.005"),
    "forward_surgical_cells": ("field_hospital = { experience_loss_factor = -0.04 casualty_trickleback = 0.03 }", "category_all_infantry = { max_organisation = 1 }"),
    "predictive_blood_logistics": ("field_hospital = { supply_consumption = -0.04 casualty_trickleback = 0.04 }", "supply_consumption_factor = -0.01"),
    "regenerative_surgery_modules": ("field_hospital = { casualty_trickleback = 0.07 experience_loss_factor = -0.03 }", "category_all_infantry = { default_morale = 0.03 }"),
    "autonomous_medevac_routing": ("field_hospital = { casualty_trickleback = 0.05 supply_consumption = -0.04 }", "land_reinforce_rate = 0.01"),
    "sealed_recovery_wards": ("field_hospital = { experience_loss_factor = -0.05 casualty_trickleback = 0.04 }", "attrition = -0.01"),
    "distributed_combat_medicine": ("field_hospital = { casualty_trickleback = 0.08 experience_loss_factor = -0.05 supply_consumption = -0.04 }", "category_all_infantry = { default_morale = 0.04 }"),

    "battle_damage_survey_teams": ("industry_repair_factor = 0.03", "category_support_battalions = { defense = 0.02 }"),
    "assault_breaching_packages": ("engineer = { breakthrough = 0.05 soft_attack = 0.03 }", "planning_speed = 0.02"),
    "mobile_restoration_columns": ("maintenance_company = { equipment_capture_factor = 0.02 }", "industry_repair_factor = 0.04", "org_loss_when_moving = -0.01"),
    "robotic_obstacle_clearance": ("engineer = { breakthrough = 0.07 defense = 0.04 }", "dig_in_speed_factor = 0.03"),
    "predictive_spare_part_pools": ("maintenance_company = { equipment_capture_factor = 0.03 }", "attrition = -0.015", "industry_repair_factor = 0.04"),
    "autonomous_bridgehead_fabrication": ("engineer = { breakthrough = 0.08 defense = 0.05 }", "production_speed_infrastructure_factor = 0.03"),
    "self_repairing_field_depots": ("category_support_battalions = { default_morale = 0.04 defense = 0.03 }", "supply_consumption_factor = -0.015", "industry_repair_factor = 0.05"),
    "integrated_engineer_command": ("engineer = { breakthrough = 0.10 defense = 0.08 }", "category_support_battalions = { max_organisation = 2 }", "planning_speed = 0.04"),

    "spectrum_threat_libraries": ("encryption_factor = 0.02", "decryption_factor = 0.02", "air_interception_detect_factor = 0.01"),
    "offensive_jamming_cells": ("decryption_factor = 0.04", "coordination_bonus = 0.01", "air_mission_efficiency = 0.01"),
    "passive_drone_detection_meshes": ("encryption_factor = 0.04", "air_interception_detect_factor = 0.03", "air_home_defence_factor = 0.02"),
    "cognitive_emitter_spoofing": ("decryption_factor = 0.05", "enemy_army_bonus_air_superiority_factor = -0.02", "coordination_bonus = 0.01"),
    "hardened_command_waveforms": ("encryption_factor = 0.05", "land_reinforce_rate = 0.01", "air_accidents_factor = -0.01"),
    "autonomous_jamming_swarms": ("decryption_factor = 0.06", "air_intercept_efficiency = 0.03", "enemy_army_bonus_air_superiority_factor = -0.03"),
    "distributed_counter_uas_grid": ("encryption_factor = 0.06", "air_interception_detect_factor = 0.04", "air_home_defence_factor = 0.03"),
    "adaptive_spectrum_dominance": ("encryption_factor = 0.05", "decryption_factor = 0.05", "coordination_bonus = 0.03", "air_mission_efficiency = 0.03"),

    "restored_airlift_planning": ("air_mission_efficiency = 0.02", "air_mission_xp_gain_factor = 0.03", "supply_consumption_factor = -0.005"),
    "forward_tiltrotor_basing": ("air_cas_present_factor = 0.03", "army_bonus_air_superiority_factor = 0.02", "air_accidents_factor = -0.01"),
    "autonomous_cargo_gliders": ("air_mission_efficiency = 0.03", "air_power_projection_factor = 0.02", "supply_consumption_factor = -0.01"),
    "vertical_envelopment_control": ("air_cas_efficiency = 0.04", "planning_speed = 0.03", "land_reinforce_rate = 0.005"),
    "precision_aerial_resupply": ("air_mission_efficiency = 0.04", "supply_consumption_factor = -0.02", "air_accidents_factor = -0.015"),
    "distributed_assault_landing_zones": ("air_cas_present_factor = 0.05", "army_bonus_air_superiority_factor = 0.03", "planning_speed = 0.03"),
    "persistent_airbridge_networks": ("air_power_projection_factor = 0.05", "air_mission_efficiency = 0.04", "supply_consumption_factor = -0.02"),
    "autonomous_theater_airlift": ("air_mission_efficiency = 0.06", "air_mission_xp_gain_factor = 0.06", "land_reinforce_rate = 0.01", "supply_consumption_factor = -0.025"),

    "shallow_water_navigation_tables": ("naval_detection = 0.02", "naval_mines_effect_reduction = 0.02", "convoy_escort_efficiency = 0.02"),
    "armored_river_patrols": ("screening_efficiency = 0.03", "naval_hit_chance = 0.02", "amphibious_invasion_defence = 0.03"),
    "modular_landing_causeways": ("naval_invasion_prep_speed = 0.05", "naval_invasion_penalty = -0.03", "shore_bombardment_bonus = 0.03"),
    "drone_guided_river_ambushes": ("naval_detection = 0.04", "naval_hit_chance = 0.02", "screening_efficiency = 0.03"),
    "rapid_beachhead_logistics": ("naval_invasion_planning_bonus_speed = 0.08", "supply_consumption_factor = -0.01", "convoy_escort_efficiency = 0.03"),
    "autonomous_littoral_fire_control": ("naval_hit_chance = 0.04", "shore_bombardment_bonus = 0.06", "naval_coordination = 0.02"),
    "self_deploying_floating_depots": ("convoy_escort_efficiency = 0.05", "naval_invasion_prep_speed = 0.08", "supply_consumption_factor = -0.015"),
    "integrated_river_sea_command": ("naval_coordination = 0.04", "naval_detection = 0.05", "shore_bombardment_bonus = 0.08", "naval_invasion_penalty = -0.05"),

    "teleoperated_scout_carts": ("category_recon = { recon = 0.5 defense = 0.02 }", "category_all_armor = { reliability = 0.02 }"),
    "armed_recon_drones": ("category_recon = { recon = 0.75 soft_attack = 0.04 }", "category_all_armor = { maximum_speed = 0.02 }"),
    "autonomous_recovery_tractors": ("category_all_armor = { reliability = 0.05 default_morale = 0.03 }", "industry_repair_factor = 0.02"),
    "hunter_killer_ground_pairs": ("category_all_armor = { breakthrough = 0.05 hard_attack = 0.04 }", "category_recon = { recon = 0.5 }"),
    "robotic_damage_control_crews": ("category_all_armor = { reliability = 0.06 defense = 0.04 }", "attrition = -0.01"),
    "distributed_ground_swarm_control": ("category_all_armor = { breakthrough = 0.06 soft_attack = 0.05 }", "coordination_bonus = 0.015"),
    "self_recovering_combat_vehicles": ("category_all_armor = { reliability = 0.08 default_morale = 0.05 }", "industry_repair_factor = 0.03"),
    "autonomous_combined_arms_mesh": ("category_all_armor = { breakthrough = 0.08 defense = 0.06 reliability = 0.05 }", "category_recon = { recon = 1 }", "coordination_bonus = 0.02"),

    "reconstituted_staff_academies": ("planning_speed = 0.02", "land_reinforce_rate = 0.005", "max_command_power_mult = 0.02"),
    "assault_command_curriculum": ("planning_speed = 0.03", "category_all_infantry = { breakthrough = 0.02 }"),
    "defensive_command_curriculum": ("dig_in_speed_factor = 0.03", "category_all_infantry = { defense = 0.02 }"),
    "operational_planning_exercises": ("planning_speed = 0.04", "max_planning = 0.02", "coordination_bonus = 0.01"),
    "theater_logistics_wargames": ("supply_consumption_factor = -0.015", "land_reinforce_rate = 0.01", "org_loss_when_moving = -0.01"),
    "rotational_front_commands": ("planning_speed = 0.04", "land_reinforce_rate = 0.015", "max_command_power_mult = 0.03"),
    "predictive_staff_colleges": ("coordination_bonus = 0.02", "supply_consumption_factor = -0.02", "max_planning = 0.02"),
    "adaptive_general_staff": ("planning_speed = 0.06", "coordination_bonus = 0.03", "land_reinforce_rate = 0.02", "max_command_power_mult = 0.05"),
}


# attribute, number of different random army leaders improved.  Temporary
# flags prevent the same leader from being selected twice by one technology;
# flags are cleared immediately so later academy technologies may train them.
LEADER_TRAINING = {
    "assault_command_curriculum": ("attack", 2),
    "defensive_command_curriculum": ("defense", 2),
    "operational_planning_exercises": ("planning", 2),
    "theater_logistics_wargames": ("logistics", 2),
    "rotational_front_commands": ("attack", 3),
    "predictive_staff_colleges": ("planning", 3),
    "adaptive_general_staff": ("logistics", 3),
}
