"""Starting population and country content for the remaining land shells.

The remainder-state builder owns these outputs. Province membership stays with
the existing geographic source; this layer supplies political history only.
"""

from __future__ import annotations

import io
import json
import re
from functools import lru_cache
from pathlib import Path

from PIL import Image

from tools.builders.build_adiscord_northern_countries import (
    distribute_levels,
    largest_remainder,
    load_definition,
    load_pixel_areas,
    render_flag,
)
from tools.builders.build_adiscord_strategic_regions import (
    connected_components,
    load_province_adjacency,
    load_province_definitions,
)
from tools.lib.paths import repository_root


ROOT = repository_root()
SOURCE = ROOT / "tools/data/adiscord_remainder_countries.json"
MARKER = "# Populated by tools/build_adiscord_remainder_states.py"
HEADER = "# Generated by tools/build_adiscord_remainder_states.py\n"
COUNTRIES = json.loads(SOURCE.read_text(encoding="utf-8"))["countries"]
STATE_OWNERS = {
    state_id: tag for tag, row in COUNTRIES.items() for state_id in row["states"]
}
IDEOLOGIES = (
    "humanism", "hedonism", "etatism", "pragmatism", "technocracy",
    "utilitarism", "chauvinism", "anarchism",
)


def state_path(state_id: int) -> Path:
    matches = sorted((ROOT / "history/states").glob(f"{state_id}-*.txt"))
    if len(matches) != 1:
        raise ValueError(f"State {state_id}: expected one geographic source")
    return matches[0]


@lru_cache(maxsize=1)
def profiles() -> dict[int, dict]:
    colors, details = load_definition()
    areas = load_pixel_areas(colors)
    types, packed_colors = load_province_definitions()
    adjacency = load_province_adjacency(
        types, packed_colors, include_special_adjacencies=False
    )
    result = {}
    for tag, country in COUNTRIES.items():
        state_ids = country["states"]
        weights = {}
        for state_id in state_ids:
            source = state_path(state_id).read_text(encoding="utf-8-sig")
            match = re.search(r"\bprovinces\s*=\s*\{([^}]+)", source)
            provinces = set(map(int, match[1].split()))
            if any(details[p]["type"] != "land" for p in provinces):
                raise ValueError(f"State {state_id} contains non-land provinces")
            ports = []
            for component in connected_components(provinces, adjacency):
                coastal = [p for p in component if details[p]["coastal"]]
                if coastal:
                    ports.append(max(coastal, key=lambda p: (areas[p], -p)))
            anchor = max(ports or provinces, key=lambda p: (areas[p], -p))
            weights[state_id] = sum(areas[p] for p in provinces)
            result[state_id] = dict(
                owner=tag, provinces=provinces, ports=sorted(ports), anchor=anchor
            )
        ordered = [country["capital"]] + sorted(
            (s for s in state_ids if s != country["capital"]),
            key=lambda s: (-weights[s], s),
        )
        population = largest_remainder(country["population"], weights)
        civilians = distribute_levels(country["civilian"], ordered, 3)
        military = distribute_levels(country["military"], ordered, 2)
        for state_id in state_ids:
            capital = state_id == country["capital"]
            result[state_id].update(
                population=population[state_id], civilian=civilians[state_id],
                military=military[state_id], capital=capital,
                dockyard=country["dockyard"] if capital else 0,
                infrastructure=3 if capital else 1,
            )
    return result


def populate_state(source: str, state_id: int) -> str:
    """Rebuild the owned history without changing provinces or climate markers."""
    if state_id not in STATE_OWNERS:
        return source
    profile = profiles()[state_id]
    # All populated history is after this marker, making a second application
    # independent of the formatting of its previous generated history block.
    if MARKER in source:
        source = source.split(MARKER, 1)[0].rstrip() + "\n}\n"
    tag = profile["owner"]
    slots = sum(profile[key] for key in ("civilian", "military", "dockyard"))
    category = "city" if slots > 4 else "town" if slots > 2 else "rural"
    source = re.sub(r"\bmanpower\s*=\s*\d+", f"manpower = {profile['population']}", source)
    source = re.sub(r"\bstate_category\s*=\s*\w+", f"state_category = {category}", source)
    source = re.sub(r"\blocal_supplies\s*=\s*[\d.]+", "local_supplies = 2.0", source)
    history = [
        MARKER, "\thistory = {", f"\t\towner = {tag}", f"\t\tadd_core_of = {tag}",
    ]
    if profile["capital"]:
        history.append(f"\t\tvictory_points = {{ {profile['anchor']} 10 }}")
    history += ["\t\tbuildings = {", f"\t\t\tinfrastructure = {profile['infrastructure']}"]
    for building, key in (("industrial_complex", "civilian"), ("arms_factory", "military"), ("dockyard", "dockyard")):
        if profile[key]:
            history.append(f"\t\t\t{building} = {profile[key]}")
    for province in profile["ports"]:
        history.append(f"\t\t\t{province} = {{ naval_base = 1 }}")
    history += ["\t\t}", "\t}", "}", ""]
    return source.rstrip().rsplit("}", 1)[0].rstrip() + "\n" + "\n".join(history)


def country_history(tag: str, row: dict) -> str:
    return HEADER + "\n".join([
        f"capital = {row['capital']}", f'oob = "{tag}"',
        f"recruit_character = {tag}_head_of_state", "",
        "set_politics = {", f"\truling_party = {row['ideology']}",
        "\telections_allowed = no", "}",
        f"set_popularities = {{ {row['ideology']} = 100 }}",
        "set_stability = 0.55", "set_war_support = 0.25",
        "set_research_slots = 2", "set_convoys = 30", "",
    ])


def country_oob(tag: str, row: dict) -> str:
    template = f"{tag} Territorial Brigade"
    lines = [
        HEADER.rstrip(), "division_template = {", f'\tname = "{template}"',
        "\tregiments = {", "\t\tinfantry = { x = 0 y = 0 }",
        "\t\tinfantry = { x = 1 y = 0 }", "\t\tinfantry = { x = 2 y = 0 }",
        "\t}", "}", "", "units = {",
    ]
    states = [row["capital"]] + [s for s in row["states"] if s != row["capital"]]
    for index in range(row["divisions"]):
        location = profiles()[states[index % len(states)]]["anchor"]
        lines += [
            "\tdivision = {", f'\t\tname = "{index + 1}. Territorial Brigade"',
            f"\t\tlocation = {location}", f'\t\tdivision_template = "{template}"',
            "\t\tstart_experience_factor = 0.1", "\t\tstart_equipment_factor = 0.7",
            "\t}",
        ]
    return "\n".join([*lines, "}", ""])


def country_outputs() -> dict[Path, bytes]:
    outputs = {}
    tags = [HEADER.rstrip()]
    characters = [HEADER.rstrip(), "characters = {"]
    localisation = {language: {} for language in ("russian", "english")}
    for tag, row in COUNTRIES.items():
        tags.append(f'{tag} = "countries/{tag}.txt"')
        color = " ".join(map(str, row["color"]))
        outputs[ROOT / f"common/countries/{tag}.txt"] = (
            HEADER + 'graphical_culture = western_european_gfx\n'
            'graphical_culture_2d = western_european_2d\n'
            f'color = rgb {{ {color} }}\n'
        ).encode("utf-8")
        outputs[ROOT / f"history/countries/{tag} - {tag}.txt"] = country_history(tag, row).encode("utf-8")
        outputs[ROOT / f"history/units/{tag}.txt"] = country_oob(tag, row).encode("utf-8")
        characters += [
            f"\t{tag}_head_of_state = {{", f"\t\tname = {tag}_head_of_state",
            f"\t\tportraits = {{ civilian = {{ large = {row['portrait']} }} }}",
            "\t\tcountry_leader = {", f"\t\t\tideology = {row['ideology']}_ideology",
            '\t\t\texpire = "2200.1.1.1"', "\t\t\tid = -1",
            f"\t\t\tdesc = {tag}_head_of_state_desc", "\t\t}", "\t}",
        ]
        anchor = profiles()[row["capital"]]["anchor"]
        for language, entries in localisation.items():
            entries.update({
                tag: row["name"][language], f"{tag}_DEF": row["name"][language],
                f"{tag}_ADJ": row["adjective"][language],
                f"{tag}_head_of_state": row["leader"][language],
                f"{tag}_head_of_state_desc": row["description"][language],
                f"{tag}_{row['ideology']}_party": row["party"][language],
                f"{tag}_{row['ideology']}_party_long": row["party"][language],
                f"VICTORY_POINTS_{anchor}": row["city"][language],
            })
            for ideology in IDEOLOGIES:
                entries[f"{tag}_{ideology}"] = row["name"][language]
                entries[f"{tag}_{ideology}_DEF"] = row["name"][language]
                entries[f"{tag}_{ideology}_ADJ"] = row["adjective"][language]
        colors = tuple(tuple(c) for c in row["flag_colors"])
        flag = render_flag(tag, colors, row["flag_style"])
        for directory, size in (("", (82, 52)), ("medium/", (41, 26)), ("small/", (10, 7))):
            stream = io.BytesIO()
            flag.resize(size, Image.Resampling.LANCZOS).save(stream, format="TGA")
            outputs[ROOT / f"gfx/flags/{directory}{tag}.tga"] = stream.getvalue()
    outputs[ROOT / "common/country_tags/08_ADISCORD_remainder_countries.txt"] = ("\n".join(tags) + "\n").encode("utf-8")
    outputs[ROOT / "common/characters/ADISCORD_remainder_characters.txt"] = ("\n".join([*characters, "}", ""])).encode("utf-8")
    for language, entries in localisation.items():
        lines = [f"l_{language}:", f" # Generated by tools/build_adiscord_remainder_states.py"]
        for key, value in entries.items():
            lines.append(f' {key}:0 "{value}"')
        outputs[ROOT / f"localisation/{language}/ADISCORD_remainder_countries_l_{language}.yml"] = ("\n".join(lines) + "\n").encode("utf-8-sig")
    return outputs


def expected_outputs() -> dict[Path, bytes]:
    outputs = country_outputs()
    for state_id in STATE_OWNERS:
        path = state_path(state_id)
        source = path.read_text(encoding="utf-8-sig")
        outputs[path] = populate_state(source, state_id).encode("utf-8")
    return outputs


def synchronize(*, apply: bool = False) -> list[str]:
    changed = []
    for path, content in expected_outputs().items():
        if not path.exists() or path.read_bytes() != content:
            changed.append(path.relative_to(ROOT).as_posix())
            if apply:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    return changed
