"""Additional dated technology nodes for A-Discord civil and infantry branches."""


EXPANSIONS: dict[str, dict[int, tuple[str, str, str, str]]] = {
    "reconstruction": {
        2150: ("drone_construction_cartography", "Картография строительных дронов", "Construction Drone Cartography", "basic_construction"),
        2162: ("structural_ruin_assessment", "Оценка несущих конструкций руин", "Structural Ruin Assessment", "improved_construction"),
        2164: ("standardized_utility_corridors", "Стандартные инженерные коридоры", "Standardized Utility Corridors", "advanced_construction"),
        2166: ("rapid_bridge_section_casting", "Быстрое литьё мостовых секций", "Rapid Bridge Section Casting", "improved_construction"),
        2168: ("reclaimed_aggregate_concrete", "Бетон с вторичным заполнителем", "Reclaimed Aggregate Concrete", "advanced_construction"),
        2173: ("automated_demolition_planning", "Автоматизированное планирование сноса", "Automated Demolition Planning", "advanced_construction"),
        2176: ("robotic_foundation_piling", "Роботизированная забивка свай", "Robotic Foundation Piling", "advanced_construction"),
        2179: ("seismic_retrofit_frames", "Каркасы сейсмического усиления", "Seismic Retrofit Frames", "advanced_construction"),
        2185: ("self_sealing_utility_mains", "Самогерметизирующиеся коммунальные магистрали", "Self-Sealing Utility Mains", "advanced_construction"),
        2188: ("swarm_masonry_platforms", "Роевые кладочные платформы", "Swarm Masonry Platforms", "advanced_construction"),
        2191: ("adaptive_district_scaffolds", "Адаптивные каркасы городских районов", "Adaptive District Scaffolds", "advanced_construction"),
        2194: ("autonomous_infrastructure_inspection", "Автономная инспекция инфраструктуры", "Autonomous Infrastructure Inspection", "advanced_construction"),
        2197: ("arcology_load_redistribution", "Перераспределение нагрузок аркологий", "Arcology Load Redistribution", "advanced_construction"),
    },
    "production": {
        2150: ("precision_metrology_recovery", "Восстановление точной метрологии", "Precision Metrology Recovery", "improved_machine_tools"),
        2162: ("digital_tooling_libraries", "Цифровые библиотеки оснастки", "Digital Tooling Libraries", "advanced_machine_tools"),
        2164: ("sensor_calibrated_machining", "Сенсорная калибровка станков", "Sensor-Calibrated Machining", "advanced_machine_tools"),
        2166: ("modular_fixture_systems", "Модульные системы крепления", "Modular Fixture Systems", "assembly_line_production"),
        2168: ("closed_loop_quality_control", "Замкнутый контроль качества", "Closed-Loop Quality Control", "concentrated_industry"),
        2173: ("flexible_robotic_tooling", "Гибкая роботизированная оснастка", "Flexible Robotic Tooling", "flexible_line"),
        2176: ("additive_spare_part_cells", "Ячейки аддитивного выпуска запчастей", "Additive Spare-Part Cells", "advanced_machine_tools"),
        2179: ("machine_vision_inspection", "Контроль машинным зрением", "Machine-Vision Inspection", "assembly_line_production"),
        2185: ("self_balancing_production_lines", "Самобалансирующиеся производственные линии", "Self-Balancing Production Lines", "streamlined_line"),
        2188: ("collaborative_industrial_swarms", "Коллаборативные промышленные рои", "Collaborative Industrial Swarms", "flexible_line"),
        2191: ("molecular_precision_deposition", "Осаждение с молекулярной точностью", "Molecular-Precision Deposition", "advanced_machine_tools"),
        2194: ("demand_synchronized_fabrication", "Синхронизированное со спросом производство", "Demand-Synchronized Fabrication", "streamlined_line"),
        2197: ("lights_out_microfactories", "Безлюдные микрофабрики", "Lights-Out Microfactories", "flexible_line"),
    },
    "resources": {
        2150: ("spectral_ore_sorting", "Спектральная сортировка руды", "Spectral Ore Sorting", "excavation2"),
        2162: ("borehole_sensor_grids", "Сети скважинных датчиков", "Borehole Sensor Grids", "excavation1"),
        2164: ("plasma_scrap_separation", "Плазменное разделение металлолома", "Plasma Scrap Separation", "excavation2"),
        2166: ("microbial_tailings_leaching", "Микробное выщелачивание отвалов", "Microbial Tailings Leaching", "excavation4"),
        2168: ("refinery_catalyst_recovery", "Регенерация катализаторов НПЗ", "Refinery Catalyst Recovery", "improved_oil_processing"),
        2173: ("high_pressure_polymer_synthesis", "Высокобарический синтез полимеров", "High-Pressure Polymer Synthesis", "rubber_processing"),
        2176: ("geothermal_brine_extraction", "Извлечение минералов из геотермальных рассолов", "Geothermal Brine Extraction", "excavation4"),
        2179: ("rare_earth_solvent_loops", "Замкнутые циклы редкоземельной экстракции", "Rare-Earth Solvent Loops", "excavation4"),
        2185: ("automated_deep_mining", "Автоматизированная глубокая добыча", "Automated Deep Mining", "excavation5"),
        2188: ("carbon_feedstock_cracking", "Крекинг углеродного сырья", "Carbon Feedstock Cracking", "oil_processing"),
        2191: ("isotope_selective_refining", "Изотопно-селективное рафинирование", "Isotope-Selective Refining", "excavation5"),
        2194: ("urban_mine_cartography", "Картография городских месторождений", "Urban Mine Cartography", "excavation4"),
        2197: ("strategic_element_reclamation", "Регенерация стратегических элементов", "Strategic Element Reclamation", "excavation5"),
    },
    "finance": {
        2150: ("unified_treasury_ledgers", "Единые казначейские реестры", "Unified Treasury Ledgers", "mechanical_computing"),
        2162: ("biometric_tax_identity", "Биометрическая налоговая идентификация", "Biometric Tax Identity", "mechanical_computing"),
        2164: ("realtime_customs_clearing", "Таможенный расчёт в реальном времени", "Real-Time Customs Clearing", "improved_computing_machine"),
        2166: ("programmable_procurement_escrow", "Программируемое обеспечение госзакупок", "Programmable Procurement Escrow", "computing_machine"),
        2168: ("automated_fraud_scoring", "Автоматическая оценка мошеннических рисков", "Automated Fraud Scoring", "improved_computing_machine"),
        2173: ("regional_clearing_network", "Региональная клиринговая сеть", "Regional Clearing Network", "computing_machine"),
        2176: ("dynamic_ration_credit", "Динамический пайковый кредит", "Dynamic Ration Credit", "improved_computing_machine"),
        2179: ("sovereign_risk_simulation", "Моделирование суверенных рисков", "Sovereign Risk Simulation", "improved_computing_machine"),
        2185: ("machine_audited_budgets", "Машинный аудит бюджетов", "Machine-Audited Budgets", "advanced_computing_machine"),
        2188: ("algorithmic_bond_auctions", "Алгоритмические аукционы облигаций", "Algorithmic Bond Auctions", "computing_machine"),
        2191: ("cryptographic_reserve_custody", "Криптографическое хранение резервов", "Cryptographic Reserve Custody", "advanced_computing_machine"),
        2194: ("predictive_revenue_balancing", "Предиктивная балансировка доходов", "Predictive Revenue Balancing", "improved_computing_machine"),
        2197: ("autonomous_fiscal_stabilization", "Автономная фискальная стабилизация", "Autonomous Fiscal Stabilization", "advanced_computing_machine"),
    },
    "administration": {
        2150: ("cadastral_archive_digitization", "Оцифровка кадастровых архивов", "Cadastral Archive Digitization", "mechanical_computing"),
        2162: ("portable_civil_service_terminals", "Переносные терминалы госслужбы", "Portable Civil-Service Terminals", "mechanical_computing"),
        2164: ("federated_identity_registry", "Федеративный реестр личности", "Federated Identity Registry", "improved_computing_machine"),
        2166: ("automated_permit_routing", "Автоматическая маршрутизация разрешений", "Automated Permit Routing", "computing_machine"),
        2168: ("emergency_population_census", "Оперативная перепись населения", "Emergency Population Census", "computing_machine"),
        2173: ("interoperable_municipal_databases", "Совместимые муниципальные базы данных", "Interoperable Municipal Databases", "improved_computing_machine"),
        2176: ("machine_readable_civil_code", "Машиночитаемый гражданский кодекс", "Machine-Readable Civil Code", "computing_machine"),
        2179: ("algorithmic_case_triage", "Алгоритмическая сортировка обращений", "Algorithmic Case Triage", "improved_computing_machine"),
        2185: ("decentralized_service_kiosks", "Децентрализованные киоски госуслуг", "Decentralized Service Kiosks", "mechanical_computing"),
        2188: ("civic_digital_twin", "Цифровой двойник гражданской системы", "Civic Digital Twin", "advanced_computing_machine"),
        2191: ("adaptive_jurisdiction_mapping", "Адаптивное картирование юрисдикций", "Adaptive Jurisdiction Mapping", "improved_computing_machine"),
        2194: ("autonomous_records_verification", "Автономная проверка реестров", "Autonomous Records Verification", "advanced_computing_machine"),
        2197: ("anticipatory_service_allocation", "Упреждающее распределение госуслуг", "Anticipatory Service Allocation", "advanced_computing_machine"),
    },
    "civil_resilience": {
        2150: ("shelter_ventilation_filters", "Фильтры вентиляции убежищ", "Shelter Ventilation Filters", "basic_construction"),
        2162: ("emergency_water_purification", "Аварийная очистка воды", "Emergency Water Purification", "basic_machine_tools"),
        2164: ("neighborhood_microgrids", "Районные микросети", "Neighborhood Microgrids", "improved_construction"),
        2166: ("modular_field_clinics", "Модульные полевые клиники", "Modular Field Clinics", "advanced_construction"),
        2168: ("reserve_food_preservation", "Консервация резервного продовольствия", "Reserve Food Preservation", "basic_machine_tools"),
        2173: ("evacuation_route_beacons", "Маяки эвакуационных маршрутов", "Evacuation Route Beacons", "advanced_construction"),
        2176: ("autonomous_firefighting_drones", "Автономные пожарные дроны", "Autonomous Firefighting Drones", "advanced_machine_tools"),
        2179: ("radiation_safe_transit_corridors", "Радиационно-безопасные транзитные коридоры", "Radiation-Safe Transit Corridors", "advanced_construction"),
        2185: ("robotic_flood_barriers", "Роботизированные противопаводковые барьеры", "Robotic Flood Barriers", "advanced_construction"),
        2188: ("distributed_emergency_stockpiles", "Распределённые аварийные запасы", "Distributed Emergency Stockpiles", "concentrated_industry5"),
        2191: ("urban_heat_refuge_networks", "Сети городских климатических убежищ", "Urban Heat-Refuge Networks", "advanced_construction"),
        2194: ("predictive_disaster_evacuation", "Предиктивная эвакуация при катастрофах", "Predictive Disaster Evacuation", "concentrated_industry5"),
        2197: ("self_healing_civil_lifelines", "Самовосстанавливающиеся городские коммуникации", "Self-Healing Civil Lifelines", "advanced_construction"),
    },
    "power": {
        2150: ("phase_synchronized_substations", "Фазосинхронизированные подстанции", "Phase-Synchronized Substations", "electronic_mechanical_engineering"),
        2162: ("ceramic_grid_insulators", "Керамические сетевые изоляторы", "Ceramic Grid Insulators", "radio"),
        2164: ("solid_state_grid_breakers", "Твердотельные сетевые выключатели", "Solid-State Grid Breakers", "electronic_mechanical_engineering"),
        2166: ("modular_fission_heat_exchangers", "Модульные теплообменники деления", "Modular Fission Heat Exchangers", "nuclear_reactor"),
        2168: ("radiation_hardened_control_rods", "Радиационно-стойкие управляющие стержни", "Radiation-Hardened Control Rods", "nuclear_reactor"),
        2173: ("molten_salt_cleanup_systems", "Системы очистки расплавов солей", "Molten-Salt Cleanup Systems", "nuclear_reactor"),
        2176: ("load_following_microreactors", "Маневренные микрореакторы", "Load-Following Microreactors", "nuclear_reactor"),
        2179: ("superconducting_power_busbars", "Сверхпроводящие силовые шины", "Superconducting Power Busbars", "nuclear_reactor"),
        2185: ("passive_decay_heat_sinks", "Пассивные поглотители остаточного тепла", "Passive Decay-Heat Sinks", "nuclear_reactor"),
        2188: ("autonomous_reactor_diagnostics", "Автономная диагностика реакторов", "Autonomous Reactor Diagnostics", "nuclear_reactor"),
        2191: ("closed_fuel_cycle_separators", "Сепараторы замкнутого топливного цикла", "Closed Fuel-Cycle Separators", "nuclear_reactor"),
        2194: ("high_density_thermal_storage", "Высокоплотные тепловые накопители", "High-Density Thermal Storage", "nuclear_reactor"),
        2197: ("continental_load_balancing", "Континентальная балансировка нагрузки", "Continental Load Balancing", "nuclear_reactor"),
    },
    "signals": {
        2150: ("frequency_hopping_field_sets", "Полевые станции со скачками частоты", "Frequency-Hopping Field Sets", "radio"),
        2162: ("directional_mesh_relays", "Направленные ячеистые ретрансляторы", "Directional Mesh Relays", "radio_detection"),
        2164: ("lattice_key_exchange", "Обмен ключами на решётках", "Lattice-Key Exchange", "basic_encryption"),
        2166: ("passive_emitter_geolocation", "Пассивная геолокация излучателей", "Passive Emitter Geolocation", "basic_decryption"),
        2168: ("packetized_fire_control_links", "Пакетные каналы управления огнём", "Packetized Fire-Control Links", "radio_detection"),
        2173: ("cognitive_spectrum_management", "Когнитивное управление спектром", "Cognitive Spectrum Management", "improved_encryption"),
        2176: ("stratospheric_burst_relays", "Стратосферные ретрансляторы пакетной связи", "Stratospheric Burst Relays", "radio"),
        2179: ("autonomous_intrusion_hunting", "Автономный поиск вторжений", "Autonomous Intrusion Hunting", "improved_decryption"),
        2185: ("photonic_encryption_modules", "Фотонные модули шифрования", "Photonic Encryption Modules", "advanced_encryption"),
        2188: ("battlefield_sensor_fusion", "Сведение датчиков поля боя", "Battlefield Sensor Fusion", "radio_detection"),
        2191: ("adaptive_deception_networks", "Адаптивные сети радиообмана", "Adaptive Deception Networks", "improved_decryption"),
        2194: ("quantum_command_authentication", "Квантовая аутентификация команд", "Quantum Command Authentication", "advanced_encryption"),
        2197: ("self_healing_tactical_networks", "Самовосстанавливающиеся тактические сети", "Self-Healing Tactical Networks", "advanced_encryption"),
    },
    "computing": {
        2150: ("vacuum_sealed_logic_restoration", "Восстановление герметичной логики", "Vacuum-Sealed Logic Restoration", "mechanical_computing"),
        2162: ("rugged_chiplet_packaging", "Защищённая компоновка чиплетов", "Rugged Chiplet Packaging", "mechanical_computing"),
        2164: ("neuromorphic_coprocessors", "Нейроморфные сопроцессоры", "Neuromorphic Coprocessors", "improved_computing_machine"),
        2166: ("error_correcting_field_computers", "Полевые вычислители с коррекцией ошибок", "Error-Correcting Field Computers", "computing_machine"),
        2168: ("distributed_operational_caches", "Распределённые оперативные хранилища", "Distributed Operational Caches", "computing_machine"),
        2173: ("analog_ai_accelerators", "Аналоговые ускорители ИИ", "Analog AI Accelerators", "improved_computing_machine"),
        2176: ("synthetic_training_environments", "Синтетические учебные среды", "Synthetic Training Environments", "computing_machine"),
        2179: ("federated_operational_learning", "Федеративное оперативное обучение", "Federated Operational Learning", "improved_computing_machine"),
        2185: ("explainable_command_models", "Объяснимые командные модели", "Explainable Command Models", "advanced_computing_machine"),
        2188: ("photonic_compute_arrays", "Фотонные вычислительные массивы", "Photonic Compute Arrays", "advanced_computing_machine"),
        2191: ("autonomous_code_synthesis", "Автономный синтез кода", "Autonomous Code Synthesis", "improved_computing_machine"),
        2194: ("strategic_digital_twins", "Стратегические цифровые двойники", "Strategic Digital Twins", "advanced_computing_machine"),
        2197: ("bounded_general_planning_cores", "Ограниченные ядра общего планирования", "Bounded General-Planning Cores", "advanced_computing_machine"),
    },
    "small_arms": {
        2150: ("caseless_ammunition_trials", "Испытания безгильзовых боеприпасов", "Caseless Ammunition Trials", "infantry_weapons2"),
        2162: ("sealed_receiver_assemblies", "Герметичные ствольные коробки", "Sealed Receiver Assemblies", "infantry_weapons"),
        2164: ("electrothermal_ignition", "Электротермическое воспламенение", "Electrothermal Ignition", "infantry_weapons3"),
        2166: ("smart_recoil_compensators", "Умные компенсаторы отдачи", "Smart Recoil Compensators", "infantry_weapons3"),
        2168: ("networked_weapon_sights", "Сетевые оружейные прицелы", "Networked Weapon Sights", "night_vision"),
        2173: ("biometric_trigger_locks", "Биометрические блокираторы спуска", "Biometric Trigger Locks", "infantry_weapons3"),
        2176: ("variable_velocity_ammunition", "Боеприпасы с регулируемой скоростью", "Variable-Velocity Ammunition", "infantry_at2"),
        2179: ("integrated_target_designation", "Встроенное целеуказание", "Integrated Target Designation", "night_vision2"),
        2185: ("powered_ammunition_carriers", "Механизированные носители боекомплекта", "Powered Ammunition Carriers", "infantry_at2"),
        2188: ("coil_assisted_service_rifles", "Строевые винтовки с катушечным ускорителем", "Coil-Assisted Service Rifles", "infantry_weapons3"),
        2191: ("adaptive_projectile_fuzing", "Адаптивное программирование взрывателей", "Adaptive Projectile Fuzing", "infantry_at2"),
        2194: ("squad_fire_control_optics", "Оптика управления огнём отделения", "Squad Fire-Control Optics", "night_vision2"),
        2197: ("hybrid_kinetic_energy_carbines", "Гибридные кинетико-энергетические карабины", "Hybrid Kinetic-Energy Carbines", "infantry_weapons3"),
    },
    "squad_weapons": {
        2150: ("recoilless_squad_launchers", "Безоткатные гранатомёты отделения", "Recoilless Squad Launchers", "support_weapons2"),
        2162: ("programmable_grenade_fuzes", "Программируемые гранатные взрыватели", "Programmable Grenade Fuzes", "support_weapons2"),
        2164: ("man_portable_sensor_masts", "Переносные сенсорные мачты", "Man-Portable Sensor Masts", "tech_signal_company"),
        2166: ("distributed_ammunition_carriers", "Распределённые носители боеприпасов", "Distributed Ammunition Carriers", "support_weapons3"),
        2168: ("drone_guided_support_fire", "Поддерживающий огонь по данным дронов", "Drone-Guided Support Fire", "support_weapons3"),
        2173: ("remote_weapon_tripods", "Дистанционные оружейные треноги", "Remote Weapon Tripods", "tech_signal_company"),
        2176: ("loitering_munition_teams", "Расчёты барражирующих боеприпасов", "Loitering Munition Teams", "infantry_at"),
        2179: ("cooperative_target_handoff", "Кооперативная передача целей", "Cooperative Target Handoff", "tech_signal_company"),
        2185: ("autonomous_mortar_sections", "Автономные миномётные отделения", "Autonomous Mortar Sections", "support_weapons4"),
        2188: ("microdrone_suppression_nets", "Сети подавления микродронов", "Microdrone Suppression Nets", "support_weapons4"),
        2191: ("electromagnetic_anti_armor_launchers", "Электромагнитные противоброневые установки", "Electromagnetic Anti-Armor Launchers", "infantry_at"),
        2194: ("robotic_heavy_weapon_teams", "Роботизированные расчёты тяжёлого оружия", "Robotic Heavy-Weapon Teams", "support_weapons4"),
        2197: ("swarm_coordinated_fire_support", "Роевая координация огневой поддержки", "Swarm-Coordinated Fire Support", "tech_special_forces"),
    },
    "protection": {
        2150: ("ceramic_trauma_inserts", "Керамические травмозащитные вставки", "Ceramic Trauma Inserts", "tech_field_hospital"),
        2162: ("sealed_respirator_interfaces", "Герметичные интерфейсы респираторов", "Sealed Respirator Interfaces", "engineers2"),
        2164: ("active_hearing_protection", "Активная защита слуха", "Active Hearing Protection", "tech_field_hospital2"),
        2166: ("thermal_signature_liners", "Подкладки снижения тепловой сигнатуры", "Thermal-Signature Liners", "recon3"),
        2168: ("powered_load_bearing_harnesses", "Приводные разгрузочные системы", "Powered Load-Bearing Harnesses", "engineers3"),
        2173: ("smart_tourniquet_systems", "Умные турникетные системы", "Smart Tourniquet Systems", "tech_field_hospital2"),
        2176: ("autonomous_casualty_monitors", "Автономные мониторы состояния раненых", "Autonomous Casualty Monitors", "tech_field_hospital2"),
        2179: ("reactive_camouflage_textiles", "Реактивные маскировочные ткани", "Reactive Camouflage Textiles", "recon3"),
        2185: ("exosuit_joint_actuators", "Шарнирные приводы экзокостюмов", "Exosuit Joint Actuators", "engineers4"),
        2188: ("nanofiber_wound_dressings", "Нановолоконные раневые повязки", "Nanofiber Wound Dressings", "tech_field_hospital2"),
        2191: ("adaptive_radiation_shielding", "Адаптивное радиационное экранирование", "Adaptive Radiation Shielding", "engineers4"),
        2194: ("closed_loop_combat_life_support", "Замкнутое боевое жизнеобеспечение", "Closed-Loop Combat Life Support", "engineers4"),
        2197: ("self_sealing_combat_skins", "Самогерметизирующиеся боевые оболочки", "Self-Sealing Combat Skins", "recon4"),
    },
    "special_forces": {
        2150: ("subterranean_route_reconnaissance", "Разведка подземных маршрутов", "Subterranean Route Reconnaissance", "recon"),
        2162: ("urban_vertical_access_rigs", "Снаряжение вертикального доступа", "Urban Vertical-Access Rigs", "tech_special_forces"),
        2164: ("low_observable_infiltration_suits", "Малозаметные костюмы проникновения", "Low-Observable Infiltration Suits", "recon2"),
        2166: ("autonomous_scout_microdrones", "Автономные разведывательные микродроны", "Autonomous Scout Microdrones", "paratroopers"),
        2168: ("contested_zone_navigation", "Навигация в оспариваемой зоне", "Contested-Zone Navigation", "recon2"),
        2173: ("high_altitude_insertion_capsules", "Высотные капсулы десантирования", "High-Altitude Insertion Capsules", "paratroopers2"),
        2176: ("multispectral_concealment_discipline", "Мультиспектральная скрытность", "Multispectral Concealment Discipline", "recon4"),
        2179: ("remote_beacon_extraction", "Эвакуация по дистанционным маякам", "Remote-Beacon Extraction", "paratroopers2"),
        2185: ("predictive_patrol_evasion", "Предиктивный обход патрулей", "Predictive Patrol Evasion", "recon4"),
        2188: ("distributed_recon_sensor_caches", "Распределённые тайники разведдатчиков", "Distributed Recon Sensor Caches", "recon4"),
        2191: ("robotic_breaching_companions", "Роботизированные комплексы прорыва", "Robotic Breaching Companions", "tech_special_forces"),
        2194: ("deep_area_sustainment_pods", "Капсулы снабжения глубинных групп", "Deep-Area Sustainment Pods", "paratroopers3"),
        2197: ("augmented_mission_rehearsal", "Дополненная репетиция операций", "Augmented Mission Rehearsal", "paratroopers3"),
    },
    "field_support": {
        2150: ("standardized_field_tool_chests", "Стандартные наборы полевого инструмента", "Standardized Field Tool Chests", "tech_maintenance_company"),
        2162: ("portable_diagnostic_benches", "Переносные диагностические стенды", "Portable Diagnostic Benches", "engineers"),
        2164: ("modular_bridge_launch_kits", "Модульные комплекты наведения мостов", "Modular Bridge-Launch Kits", "engineers2"),
        2166: ("sterilized_casualty_modules", "Стерильные эвакуационные модули", "Sterilized Casualty Modules", "tech_field_hospital2"),
        2168: ("drone_delivered_repair_spares", "Доставка ремкомплектов дронами", "Drone-Delivered Repair Spares", "tech_maintenance_company3"),
        2173: ("remote_maintenance_telemetry", "Телеметрия дистанционного обслуживания", "Remote Maintenance Telemetry", "tech_maintenance_company3"),
        2176: ("robotic_recovery_winches", "Роботизированные эвакуационные лебёдки", "Robotic Recovery Winches", "tech_maintenance_company4"),
        2179: ("additive_field_fabrication", "Аддитивное полевое производство", "Additive Field Fabrication", "engineers3"),
        2185: ("autonomous_triage_stations", "Автономные сортировочные пункты", "Autonomous Triage Stations", "tech_field_hospital2"),
        2188: ("self_deploying_field_workshops", "Саморазвёртывающиеся полевые мастерские", "Self-Deploying Field Workshops", "tech_maintenance_company4"),
        2191: ("predictive_parts_prepositioning", "Предиктивное размещение запчастей", "Predictive Parts Prepositioning", "tech_logistics_company4"),
        2194: ("unmanned_recovery_convoys", "Беспилотные эвакуационные колонны", "Unmanned Recovery Convoys", "tech_maintenance_company4"),
        2197: ("regenerative_support_depots", "Регенеративные базы обеспечения", "Regenerative Support Depots", "tech_logistics_company4"),
    },
    "logistics": {
        2150: ("standardized_cargo_pallets", "Стандартные грузовые паллеты", "Standardized Cargo Pallets", "tech_logistics_company"),
        2162: ("convoy_radio_beacons", "Радиомаяки транспортных колонн", "Convoy Radio Beacons", "motorised_infantry"),
        2164: ("modular_fuel_bladders", "Модульные мягкие топливные резервуары", "Modular Fuel Bladders", "tech_logistics_company2"),
        2166: ("cold_chain_field_containers", "Полевые контейнеры холодовой цепи", "Cold-Chain Field Containers", "tech_logistics_company2"),
        2168: ("automated_depot_manifests", "Автоматизированные складские ведомости", "Automated Depot Manifests", "tech_signal_company2"),
        2173: ("drone_resupply_corridors", "Коридоры снабжения дронами", "Drone Resupply Corridors", "tech_logistics_company3"),
        2176: ("predictive_convoy_scheduling", "Предиктивное расписание колонн", "Predictive Convoy Scheduling", "tech_signal_company3"),
        2179: ("terrain_adaptive_cargo_carriers", "Грузовые носители с адаптацией к местности", "Terrain-Adaptive Cargo Carriers", "tech_logistics_company3"),
        2185: ("distributed_microdepots", "Распределённые микросклады", "Distributed Microdepots", "tech_logistics_company4"),
        2188: ("autonomous_last_mile_carriers", "Автономные носители последней мили", "Autonomous Last-Mile Carriers", "tech_signal_company3"),
        2191: ("dynamic_supply_allocation", "Динамическое распределение снабжения", "Dynamic Supply Allocation", "tech_logistics_company4"),
        2194: ("self_routing_logistics_mesh", "Самомаршрутизирующаяся логистическая сеть", "Self-Routing Logistics Mesh", "tech_signal_company4"),
        2197: ("closed_loop_field_supply", "Замкнутый цикл полевого снабжения", "Closed-Loop Field Supply", "tech_logistics_company4"),
    },
    "rail": {
        2150: ("ultrasonic_rail_inspection", "Ультразвуковая дефектоскопия рельсов", "Ultrasonic Rail Inspection", "train_equipment_1"),
        2162: ("modular_sleeper_casting", "Модульное литьё шпал", "Modular Sleeper Casting", "train_equipment_2"),
        2164: ("recoil_braced_firing_sidings", "Огневые тупики с компенсацией отдачи", "Recoil-Braced Firing Sidings", "generic_railway_gun"),
        2166: ("armored_ammunition_tenders", "Бронированные вагоны боепитания", "Armored Ammunition Tenders", "train_equipment_2"),
        2168: ("counter_battery_relocation_tables", "Таблицы противобатарейной передислокации", "Counter-Battery Relocation Tables", "generic_railway_gun"),
        2173: ("drone_track_survey", "Дроновая инспекция путей", "Drone Track Survey", "engineers3"),
        2176: ("predictive_wheelset_maintenance", "Предиктивное обслуживание колёсных пар", "Predictive Wheelset Maintenance", "train_equipment_3"),
        2179: ("distributed_rail_traffic_control", "Распределённое управление движением", "Distributed Rail Traffic Control", "train_equipment_3"),
        2185: ("autonomous_yard_shunting", "Автономная сортировка вагонов", "Autonomous Yard Shunting", "train_equipment_3"),
        2188: ("active_suspension_gun_carriages", "Орудийные платформы с активной подвеской", "Active-Suspension Gun Carriages", "generic_super_heavy_railway_gun"),
        2191: ("smart_railbed_repair_swarms", "Рои ремонта железнодорожного полотна", "Smart Railbed Repair Swarms", "engineers3"),
        2194: ("hypersonic_shell_telemetry", "Телеметрия гиперзвуковых снарядов", "Hypersonic Shell Telemetry", "generic_super_heavy_railway_gun"),
        2197: ("continental_fire_control_relays", "Континентальные ретрансляторы управления огнём", "Continental Fire-Control Relays", "generic_super_heavy_railway_gun"),
    },
}

