"""Small helpers for safely updating shared HOI4 localisation files."""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from pathlib import Path


def sync_builder_english_localisation(root: Path, owner: str, *, apply: bool) -> int:
    """Render reviewed English names without regenerating map or country data.

    Russian values are pinned alongside the translation so renamed source entries
    fail validation instead of silently retaining an obsolete English name.
    """
    catalogue = json.loads((root / "tools/data/adiscord_world_names_english.json").read_text(encoding="utf-8"))
    differences = 0
    for specification in catalogue[owner]:
        source = (root / specification["source"]).read_text(encoding="utf-8-sig")
        marker = specification["marker"]
        if marker and specification.get("source_marker", True):
            source = source.split(f" # BEGIN GENERATED: {marker}\n", 1)[1].split(f" # END GENERATED: {marker}", 1)[0]
        entries = dict(re.findall(r'^\s*([\w.-]+):(?:\d+)?\s*"(.*)"', source, re.M))
        reviewed = specification["entries"]
        if not specification.get("source_marker", True):
            entries = {key: value for key, value in entries.items() if key in reviewed}
        if entries != {key: value["russian"] for key, value in reviewed.items()}:
            raise ValueError(f"English name review required for {specification['source']} ({marker or owner})")
        target = root / specification["target"]
        translations = {key: value["english"] for key, value in reviewed.items()}
        lines = [f' {key}: "{value}"' for key, value in translations.items()]
        if marker:
            begin, end = f" # BEGIN GENERATED: {marker}", f" # END GENERATED: {marker}"
            block = "\n".join((begin, *lines, end))
            existing = target.read_text(encoding="utf-8-sig") if target.exists() else "l_english:\n"
            if begin in existing:
                updated, count = re.subn(rf"(?ms)^{re.escape(begin)}\n.*?^{re.escape(end)}$", lambda _: block, existing)
                if count != 1:
                    raise ValueError(f"Invalid English generated block: {target}")
            else:
                updated = existing.rstrip() + "\n" + block + "\n"
        else:
            updated = "l_english:\n" + f" # Generated by {owner}\n" + "\n".join(lines) + "\n"
        expected = b"\xef\xbb\xbf" + (updated.rstrip() + "\n").encode("utf-8")
        if not target.exists() or target.read_bytes() != expected:
            differences += 1
            if apply:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(expected)
        print(f"{'Applied' if apply else 'Checked'} English names: {specification['target']}")
    return 0 if apply or not differences else 1


def replace_generated_localisation_block(
    path: Path,
    marker: str,
    entries: Mapping[str, str],
) -> None:
    """Replace one generator-owned block while preserving the shared file."""
    if not path.exists():
        raise RuntimeError(f"shared localisation file is missing: {path}")
    if not path.read_bytes().startswith(b"\xef\xbb\xbf"):
        raise RuntimeError(f"shared localisation file must use UTF-8 BOM: {path}")

    source = path.read_text(encoding="utf-8-sig", errors="strict")
    if not re.match(r"^l_[a-z_]+:\s*(?:\n|$)", source):
        raise RuntimeError(f"shared localisation file has an invalid language header: {path}")

    begin = f" # BEGIN GENERATED: {marker}"
    end = f" # END GENERATED: {marker}"
    if source.count(begin) != source.count(end) or source.count(begin) > 1:
        raise RuntimeError(f"generated localisation block markers are unbalanced: {marker}")

    rendered_entries: list[str] = []
    for key, value in entries.items():
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", key):
            raise ValueError(f"invalid localisation key {key!r}")
        if any(character in value for character in ('"', "\r", "\n")):
            raise ValueError(f"localisation value for {key} cannot be rendered safely")
        rendered_entries.append(f' {key}: "{value}"')
    block = "\n".join((begin, *rendered_entries, end))

    if begin in source:
        pattern = rf"(?ms)^{re.escape(begin)}\n.*?^{re.escape(end)}$"
        updated, count = re.subn(pattern, lambda _match: block, source)
        if count != 1:
            raise RuntimeError(f"expected one generated localisation block for {marker}, found {count}")
    else:
        updated = source.rstrip() + "\n" + block + "\n"

    path.write_text(updated.rstrip() + "\n", encoding="utf-8-sig", newline="\n")
