"""Build/check the shared eight-generation weapon package and mesh bindings."""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from PIL import Image

ROOT=Path(__file__).parent
MOD=ROOT.parents[3]
DEST=MOD/'gfx/models/units/ADISCORD_weapons'
sys.path.insert(0,str(ROOT.parent/'STP_shabrat'))
from package_shabrat import dds_mips


def prepare():
    for level in range(8):
        label=f'infantry_{level}'
        Image.open(ROOT/f'{label}_diffuse.png').convert('RGBA').save(ROOT/f'{label}_diffuse.dds',pixel_format='DXT5')
        Image.new('RGBA',(512,512),(128,128,0,128)).save(ROOT/f'{label}_normal.dds',pixel_format='DXT5')
        Image.new('RGBA',(512,512),(0,65,65,60)).save(ROOT/f'{label}_specular.dds',pixel_format='DXT5')


def bindings():
    header='# Generated by tools/assets/source/infantry_weapons_3d/package_weapons.py.\n'
    meshes=header+'objectTypes = {\n'
    anims=header
    for level in range(8):
        meshes+=f'\tpdxmesh = {{\n\t\tname = "ADISCORD_infantry_weapon_{level}_mesh"\n\t\tfile = "gfx/models/units/ADISCORD_weapons/infantry_{level}.mesh"\n'
        for state,clip in (('idle','idle'),('attack','fire'),('support_attack','support')):
            meshes+=f'\t\tanimation = {{ id = "{state}" type = "ADISCORD_infantry_weapon_{level}_{clip}_animation" }}\n'
        meshes+='\t}\n'
        for clip in ('fire','support','idle'):
            anims+=f'animation = {{\n\tname = "ADISCORD_infantry_weapon_{level}_{clip}_animation"\n\tfile = "infantry_{level}_{clip}.anim"\n}}\n'
    meshes+='}\n'
    asset=MOD/'gfx/entities/zy_ADISCORD_infantry_weapon_progression.asset'
    text=asset.read_text(encoding='utf-8')
    # Existing clone transforms and attack particle/sound events are inherited.
    # Skinned props also require a defined bind pose in their neutral states.
    def block_at(source,start):
        depth=0
        for end in range(source.index('{',start),len(source)):
            if source[end]=='{':depth+=1
            elif source[end]=='}':
                depth-=1
                if depth==0:return source[start:end+1]
        raise ValueError('Unclosed entity')
    game=Path(r'Z:/SteamLibrary/steamapps/common/Hearts of Iron IV/gfx/entities/units_infantry.asset').read_text()
    for level in range(8):
        for pose in ('right','left','long_idle'):
            name=f'ADISCORD_infantry_weapon_{level}_{pose}_entity'
            candidates=[(m.start(),block_at(text,m.start())) for m in re.finditer(r'(?m)^entity\s*=\s*\{',text)]
            start,old=next((start,b) for start,b in candidates if re.search(r'\bname\s*=\s*"'+name+'"',b))
            parent=re.search(r'clone\s*=\s*"([^"]+)"',old)[1]
            new=f'entity = {{\n\tclone = "{parent}"\n\tname = "{name}"\n\tpdxmesh = "ADISCORD_infantry_weapon_{level}_mesh"\n\tdefault_state = "idle"\n'
            for state in ('idle','move'):
                new+=f'\tstate = {{ name = "{state}" animation = "idle" }}\n'
            if (level==0 and pose=='left') or (level>0 and pose=='right'):
                native=next(block_at(game,m.start()) for m in re.finditer(r'(?m)^entity\s*=\s*\{',game)
                            if re.search(r'\bname\s*=\s*"'+parent+'"',block_at(game,m.start())))
                defend=next(block_at(native,m.start()) for m in re.finditer(r'\bstate\s*=\s*\{',native)
                            if re.search(r'\bname\s*=\s*"defend"',block_at(native,m.start())))
                defend=defend.replace('name = "defend"','name = "defend" animation = "support_attack"',1)
                new+='\t'+defend+'\n'
            new+='}'
            text=text[:start]+new+text[start+len(old):]
    text=text.replace('# Wrappers retain native weapon transforms and states. Mesh overrides\n# select the shared weapon generation for every country.',
                      '# Wrappers retain native transforms and firing events. Explicit bind-pose\n# clips initialize the skinned weapons in idle and move states.')
    return {MOD/'gfx/entities/ADISCORD_infantry_weapons.gfx':meshes.encode(),DEST/'animation.asset':anims.encode(),asset:text.encode()}


def package(apply=False):
    files=bindings()
    for level in range(8):
        for suffix in ('.mesh','_fire.anim','_support.anim','_idle.anim'):
            name=f'infantry_{level}{suffix}'
            files[DEST/name]=(ROOT/name).read_bytes()
        for kind in ('diffuse','normal','specular'):
            name=f'infantry_{level}_{kind}.dds'
            files[DEST/name]=dds_mips(ROOT/name)
    changed=[str(p.relative_to(MOD)) for p,data in files.items() if not p.is_file() or p.read_bytes()!=data]
    if apply:
        for path,data in files.items():
            path.parent.mkdir(parents=True,exist_ok=True)
            if not path.is_file() or path.read_bytes()!=data:
                path.write_bytes(data)
        (ROOT/'package_report.json').write_text(json.dumps({str(p.relative_to(MOD)):{'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()} for p,data in files.items()},indent=2))
    print(json.dumps({'files':len(files),'changed':changed,'applied':apply},indent=2))
    return changed


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--prepare',action='store_true')
    parser.add_argument('--apply',action='store_true')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    if args.prepare:
        prepare()
    elif package(args.apply) and args.check:
        raise SystemExit(1)
