"""Build and package the RUS officer; preserve the other authored HQ models.

Blender: --background --python this_file -- --build --output PATH
Python: this_file --output PATH (stage), then --check
Blender: --background --python this_file -- --verify --output PATH
Python: this_file --output PATH --apply, then --check
"""

import argparse
import hashlib
import inspect
import io
import json
import math
from pathlib import Path
import re
import struct
import sys

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[3]
GAME = Path('Z:/SteamLibrary/steamapps/common/Hearts of Iron IV')
NATIVE = GAME / 'gfx/models/units/army_headquarters'
DONOR = NATIVE / 'generic_army_headquarters.mesh'
DEST = Path('gfx/models/units/ADISCORD_headquarters')
HEADER = '# Generated by tools/assets/source/build_headquarters.py\n'
START = '# BEGIN ADISCORD RUS headquarters\n'
END = '# END ADISCORD RUS headquarters\n'
ANIMATIONS = {
    'idle': 'army_headquarters_idle_pistol',
    'notes': 'army_headquarters_long_idle01_pistol',
    'scout': 'army_headquarters_long_idle02_pistol',
    'stance': 'army_headquarters_long_idle04_pistol',
    'brush': 'army_headquarters_long_idle05_pistol',
    'attack01': 'army_headquarters_attack_stand01_pistol',
    'attack02': 'army_headquarters_attack_stand02_pistol',
    'support_attack': 'army_headquarters_attack_crouch_pistol',
    'charge_pistol': 'army_headquarters_charge_pistol',
    'charge_pistol_shoot': 'army_headquarters_charge_pistol_shoot',
    'move': 'army_headquarters_moving_pistol',
    'retreat': 'army_headquarters_retreat_pistol',
    'training': 'army_headquarters_idle_training',
    'jumping_jacks': 'army_headquarters_jumping_jacks',
    'pushup': 'army_headquarters_pushup',
}


def pdx_tools():
    sys.path.insert(0, str(Path(__file__).parent))
    sys.path.insert(0, str(
        Path.home()
        / 'AppData/Roaming/Blender Foundation/Blender/5.2/extensions/user_default'
    ))
    from io_pdx_mesh import pdx_data
    from io_pdx_mesh.pdx_blender import blender_import_export as pdx

    source = inspect.getsource(pdx.create_shader)
    for line in (
        '    new_shader.shadow_method = "CLIP"',
        '    new_shader.blend_method = "CLIP"',
    ):
        source = source.replace(line, '')
    exec(compile(source, '<Blender material compatibility>', 'exec'), pdx.__dict__)
    # Native animation offsets are relative to the posed parent, not its bind pose.
    source = inspect.getsource(pdx.import_animfile)
    source = source.replace(
        'parent_matrix = edit_bone.parent.matrix_local',
        'parent_matrix = pose_bone.parent.matrix.copy()',
    ).replace(
        'initial_pose[bone_name] = pose_bone.matrix',
        'bpy.context.view_layer.update()\n            initial_pose[bone_name] = pose_bone.matrix.copy()',
    )
    exec(compile(source, '<Native parent-relative animation>', 'exec'), pdx.__dict__)
    return pdx, pdx_data


def build(output):
    import bmesh
    import bpy
    from mathutils import Vector
    from types import SimpleNamespace

    pdx, _ = pdx_tools()
    from infantry_polish import bake_diffuse, cloth_bag, polish_normals
    from build_northern_infantry import fitted_panel_factory, finalize_mesh

    output.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.read_factory_settings(use_empty=True)
    pdx.import_meshfile(str(DONOR), imp_locs=False, join_materials=False)
    scene = bpy.context.scene
    body = max(
        (obj for obj in scene.objects if obj.type == 'MESH'),
        key=lambda obj: len(obj.data.polygons),
    )
    rig = next(mod.object for mod in body.modifiers if mod.type == 'ARMATURE')
    for obj in list(scene.objects):
        if obj not in (body, rig):
            bpy.data.objects.remove(obj, do_unlink=True)
    body.name = 'RUS_hq_body'
    rig.name = 'RUS_hq_rig'

    # The cap has its own islands, including duplicate vertices at UV seams.
    keys = [tuple(round(c, 4) for c in vertex.co) for vertex in body.data.vertices]
    links = {key: set() for key in keys}
    for face in body.data.polygons:
        for a, b in zip(face.vertices, (*face.vertices[1:], face.vertices[0])):
            links[keys[a]].add(keys[b])
            links[keys[b]].add(keys[a])
    unseen = set(keys)
    cap = set()
    jacket_surface = set()
    trouser_surface = set()
    while unseen:
        first = unseen.pop()
        component = {first}
        pending = [first]
        while pending:
            for key in links[pending.pop()]:
                if key in unseen:
                    unseen.remove(key)
                    component.add(key)
                    pending.append(key)
        if min(point[2] for point in component) > 6.8:
            cap.update(component)
        low = min(point[2] for point in component)
        high = max(point[2] for point in component)
        if 3 < low < 3.5 and 6.4 < high < 6.7:
            jacket_surface.update(component)
        if low < 0.1 and 3.5 < high < 3.8:
            trouser_surface.update(component)
    assert cap, 'Native officer cap not found'
    assert jacket_surface and trouser_surface, 'Native uniform islands not found'
    bm = bmesh.new()
    bm.from_mesh(body.data)
    bmesh.ops.delete(bm, geom=[
        vertex for vertex in bm.verts
        if tuple(round(c, 4) for c in vertex.co) in cap
    ], context='VERTS')
    bm.to_mesh(body.data)
    bm.free()
    original = body.data.materials[0]

    def material(name, color, detail=False):
        mat = original.copy() if detail else bpy.data.materials.new(name)
        mat.name = name
        mat.use_nodes = True
        nodes, links = mat.node_tree.nodes, mat.node_tree.links
        shader = nodes.get('Principled BSDF')
        if detail:
            source = shader.inputs['Base Color'].links[0].from_socket
            gray = nodes.new('ShaderNodeRGBToBW')
            links.new(source, gray.inputs[0])
            strength = nodes.new('ShaderNodeMath')
            strength.operation = 'MULTIPLY_ADD'
            strength.inputs[1].default_value = 0.70
            strength.inputs[2].default_value = 0.55
            links.new(gray.outputs[0], strength.inputs[0])
            tint = nodes.new('ShaderNodeMixRGB')
            tint.blend_type = 'MULTIPLY'
            tint.inputs[0].default_value = 1
            tint.inputs[1].default_value = (*color, 1)
            links.new(strength.outputs[0], tint.inputs[2])
            links.new(tint.outputs[0], shader.inputs['Base Color'])
        else:
            shader.inputs['Base Color'].default_value = (*color, 1)
        for socket in ('Roughness', 'Metallic'):
            for link in list(shader.inputs[socket].links):
                links.remove(link)
        shader.inputs['Roughness'].default_value = 0.76
        shader.inputs['Metallic'].default_value = 0
        return mat

    coat = material('Imperial charcoal wool', (0.046, 0.062, 0.072), True)
    trousers = material('Dark officer trousers', (0.028, 0.034, 0.041), True)
    burgundy = material('Burgundy command facing', (0.24, 0.022, 0.035))
    brass = material('Warm brass rank', (0.55, 0.32, 0.075))
    leather = material('Black leather', (0.016, 0.018, 0.023))
    canvas = material('Brown map case', (0.085, 0.044, 0.023))
    body.data.materials.append(coat)
    body.data.materials.append(trousers)
    for face in body.data.polygons:
        key = tuple(round(c, 4) for c in body.data.vertices[face.vertices[0]].co)
        if key in jacket_surface:
            face.material_index = 1
        elif key in trouser_surface:
            face.material_index = 2
    bake_diffuse(body, output / 'RUS_hq_body.png', 'RUS_hq_body')
    gear = []

    def mesh(name, vertices, faces, mat, bone='back_mid'):
        data = bpy.data.meshes.new(name)
        data.from_pydata(vertices, [], faces)
        data.update()
        obj = bpy.data.objects.new(name, data)
        scene.collection.objects.link(obj)
        obj.data.materials.append(mat)
        obj.vertex_groups.new(name=bone).add(list(range(len(vertices))), 1, 'REPLACE')
        obj.modifiers.new('Headquarters rig', 'ARMATURE').object = rig
        gear.append(obj)
        return obj

    def rings(name, rows, mat):
        segments = 40
        vertices = [
            (rx * math.cos(angle), ry * math.sin(angle), z)
            for rx, ry, z in rows
            for angle in (math.tau * i / segments for i in range(segments))
        ]
        faces = [
            (r * segments + i, r * segments + (i + 1) % segments,
             (r + 1) * segments + (i + 1) % segments, (r + 1) * segments + i)
            for r in range(len(rows) - 1) for i in range(segments)
        ]
        faces.extend((
            tuple(reversed(range(segments))),
            tuple(range((len(rows) - 1) * segments, len(rows) * segments)),
        ))
        obj = mesh(name, vertices, faces, mat, 'head')
        for face in obj.data.polygons:
            face.use_smooth = True
        return obj

    rings('Burgundy peaked cap band', [(0.385, 0.427, 7.02), (0.39, 0.43, 7.18)], burgundy)
    rings('Broad charcoal cap crown', [
        (0.40, 0.44, 7.16), (0.49, 0.51, 7.29),
        (0.46, 0.49, 7.36), (0.04, 0.045, 7.38),
    ], coat)
    rings('Cap gold piping', [(0.395, 0.435, 7.16), (0.405, 0.445, 7.18)], brass)
    vertices = []
    for radius, height in ((1, 7.065), (1.44, 6.985)):
        for i in range(25):
            angle = math.pi * (1.10 + 0.8 * i / 24)
            vertices.append((0.39 * radius * math.cos(angle),
                             0.45 * radius * math.sin(angle), height))
    visor = mesh('Black leather visor', vertices, [
        (i, i + 1, 26 + i, 25 + i) for i in range(24)
    ], leather, 'head')
    solid = visor.modifiers.new('Visor thickness', 'SOLIDIFY')
    solid.thickness = 0.018
    bpy.context.view_layer.objects.active = visor
    bpy.ops.object.modifier_apply(modifier=solid.name)
    mesh('Brass command diamond', [
        (0, -0.447, 7.21), (0.065, -0.451, 7.12),
        (0, -0.457, 7.04), (-0.065, -0.451, 7.12), (0, -0.482, 7.12),
    ], [(0, 1, 4), (1, 2, 4), (2, 3, 4), (3, 0, 4)], brass, 'head')

    panel = fitted_panel_factory(body, mesh)
    for side in (-1, 1):
        panel('Burgundy collar tab', side * 0.23, 5.94, 0.16, 0.20, burgundy, offset=0.025)
        panel('Gold collar bar', side * 0.23, 5.97, 0.12, 0.028, brass, offset=0.035)
        panel('Burgundy shoulder board', side * 0.65, 5.90, 0.18, 0.24, burgundy, offset=0.028)
        for z in (5.83, 5.90, 5.97):
            panel('Gold shoulder rank', side * 0.65, z, 0.15, 0.035, brass, offset=0.04)
    for z in (4.78, 5.04, 5.30, 5.56):
        panel('Brass tunic button', 0, z, 0.043, 0.043, brass, offset=0.03)
    panel('Officer service ribbon', -0.36, 5.52, 0.27, 0.075, burgundy, offset=0.028)
    panel('Ribbon clasp', -0.36, 5.52, 0.040, 0.07, brass, offset=0.040)
    location = Vector((-0.69, -0.36, 4.20))
    for part, kind, vertices, faces in cloth_bag(0.39, 0.21, 0.56):
        mesh('Map case ' + part, [
            tuple(location + Vector((-x, -y, z))) for x, y, z in vertices
        ], faces, canvas if kind == 'canvas' else leather, 'Hip')

    bpy.ops.object.select_all(action='DESELECT')
    for obj in gear:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = gear[0]
    bpy.ops.object.join()
    equipment = bpy.context.object
    equipment.name = 'RUS_hq_gear'
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.uv.smart_project(island_margin=0.015)
    bpy.ops.object.mode_set(mode='OBJECT')
    polish_normals(equipment)
    bake_diffuse(equipment, output / 'RUS_hq_gear.png', 'RUS_hq_gear')
    # Keep an editable source with the authored materials and packed donor maps.
    bpy.ops.file.pack_all()
    bpy.ops.wm.save_as_mainfile(filepath=str(output / 'RUS_hq.blend'))
    for obj, part in ((body, 'body'), (equipment, 'gear')):
        (output / f'RUS_hq_{part}_diffuse.dds').write_bytes(
            (output / f'RUS_hq_{part}.png').read_bytes()
        )
        for kind in ('normal', 'specular'):
            (output / f'RUS_hq_{part}_{kind}.dds').write_bytes(
                (NATIVE / f'generic_army_headquarters_{kind}.dds').read_bytes()
            )
        spec = SimpleNamespace(
            shader=['PdxMeshAdvanced'], diff=[f'RUS_hq_{part}_diffuse.dds'],
            n=[f'RUS_hq_{part}_normal.dds'], spec=[f'RUS_hq_{part}_specular.dds'],
        )
        mat = pdx.create_shader(spec, obj.name, str(output))
        obj.data.materials.clear()
        obj.data.materials.append(mat)
        for face in obj.data.polygons:
            face.material_index = 0
    bpy.ops.object.select_all(action='DESELECT')
    body.select_set(True)
    equipment.select_set(True)
    path = output / 'RUS_hq.mesh'
    pdx.export_meshfile(str(path), exp_selected=True, exp_locs=False)
    data, donor = path.read_bytes(), DONOR.read_bytes()
    marker = b'[locator\0'
    assert data.count(marker) == donor.count(marker) == 1
    path.write_bytes(data[:data.index(marker)] + donor[donor.index(marker):])
    finalize_mesh(path)


def bindings():
    from build_northern_infantry import blocks

    paths = (
        Path('gfx/entities/ADISCORD_army_headquarters.gfx'),
        Path('gfx/entities/zz_ADISCORD_army_headquarters.asset'),
        Path('gfx/interface/equipmentdesigner/graphic_db/ADISCORD_army_headquarters.txt'),
    )
    texts = []
    for path in paths:
        text = (ROOT / path).read_text(encoding='utf-8')
        text = re.sub(re.escape(START) + '.*?' + re.escape(END), '', text, flags=re.S)
        text = re.sub(r'^# Generated by [^\n]*\n', '', text)
        texts.append(text.rstrip() + '\n')
    gfx, asset, pools = texts
    source = next(block for block in blocks(gfx, 'pdxmesh')
                  if 'name = "ADISCORD_generic_hq_mesh"' in block)
    animations = re.findall(
        r'animation\s*=\s*\{\s*id\s*=\s*"([^"]+)"\s*type\s*=\s*"([^"]+)"',
        source,
    )
    assert len(animations) == 16
    lines = [
        '\tpdxmesh = {', '\t\tname = "ADISCORD_RUS_hq_mesh"',
        '\t\tfile = "gfx/models/units/ADISCORD_headquarters/RUS_hq.mesh"', '',
    ]
    for name, animation in animations:
        lines.extend((
            '\t\tanimation = {', f'\t\t\tid = "{name}"',
            f'\t\t\ttype = "{animation}"', '\t\t}',
        ))
    lines.append('\t}')
    mesh = '\n'.join(lines)
    gfx = gfx[:gfx.rfind('}')].rstrip() + '\n' + START + mesh + '\n' + END + '}\n'
    entities = []
    for tag in ('RUS', 'RUS_last_empire'):
        entities.append('\n'.join((
            'entity = {',
            '\tclone = "ADISCORD_army_headquarters_base_entity"',
            f'\tname = "{tag}_army_headquarters_entity"',
            '\tpdxmesh = "ADISCORD_RUS_hq_mesh"',
            '}',
        )))
    asset += '\n' + START + '\n\n'.join(entities) + '\n' + END
    pool = '\n'.join((
        'RUS = {', '\tinfantry_equipment = {', '\t\tpool = {',
        '\t\t\tsub_units = { hq_support_company }', '\t\t\tweight = 3000',
        '\t\t\tmodels = { RUS_army_headquarters_entity }',
        '\t\t}', '\t}', '}',
    ))
    pools += '\n' + START + pool + '\n' + END
    return {path: (HEADER + text).encode('utf-8')
            for path, text in zip(paths, (gfx, asset, pools))}


def dds(image, packed=False):
    from PIL import Image

    image = image.convert('RGBA')
    levels = []
    while True:
        stream = io.BytesIO()
        image.save(stream, format='DDS', pixel_format='DXT5')
        levels.append(stream.getvalue())
        if image.size == (1, 1):
            break
        size = tuple(max(1, value // 2) for value in image.size)
        if packed:
            image = Image.merge('RGBA', tuple(
                channel.resize(size, Image.Resampling.BOX) for channel in image.split()
            ))
        else:
            image = image.resize(size, Image.Resampling.LANCZOS)
    header = bytearray(levels[0][:128])
    struct.pack_into('<I', header, 8, struct.unpack_from('<I', header, 8)[0] | 0x20000)
    struct.pack_into('<I', header, 28, len(levels))
    struct.pack_into('<I', header, 108, 0x401008)
    return bytes(header) + b''.join(level[128:] for level in levels)


def package(output, apply=False, check=False):
    from PIL import Image

    files = bindings()
    files[DEST / 'RUS_hq.mesh'] = (output / 'RUS_hq.mesh').read_bytes()
    files[Path('tools/assets/source/RUS_hq.blend')] = (output / 'RUS_hq.blend').read_bytes()
    for part in ('body', 'gear'):
        files[DEST / f'RUS_hq_{part}_diffuse.dds'] = dds(Image.open(output / f'RUS_hq_{part}.png'))
        normal = (Image.open(NATIVE / 'generic_army_headquarters_normal.dds')
                  if part == 'body' else Image.new('RGBA', (512, 512), (255, 128, 0, 128)))
        files[DEST / f'RUS_hq_{part}_normal.dds'] = dds(normal, True)
        files[DEST / f'RUS_hq_{part}_specular.dds'] = dds(
            Image.new('RGBA', (512, 512), (0, 48, 0, 36)), True,
        )
    changed = [str(path) for path, content in files.items()
               if not (ROOT / path).exists() or (ROOT / path).read_bytes() != content]
    if apply:
        report = json.loads((output / 'verification.json').read_text())
        for path, content in files.items():
            if path.parent == DEST:
                assert report['hashes'][path.name] == hashlib.sha256(content).hexdigest(), (
                    str(path) + ': re-run --verify'
                )
    if not check:
        for path, content in files.items():
            target = (ROOT if apply else output / 'package') / path
            if not target.exists() or target.read_bytes() != content:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(content)
    print(json.dumps({'changed': changed, 'applied': apply}, indent=2))
    if check and changed:
        raise SystemExit(1)


def preview_attachments(pdx):
    import bpy
    from mathutils import Matrix
    from build_northern_infantry import blocks

    meshes = {}
    entities = {}
    for filename, kind, target in (
        ('army_headquarters.gfx', 'pdxmesh', meshes),
        ('infantry.gfx', 'pdxmesh', meshes),
        ('units_army_headquarters.asset', 'entity', entities),
        ('units_infantry.asset', 'entity', entities),
    ):
        for block in blocks((GAME / 'gfx/entities' / filename).read_text(), kind):
            name = re.search(r'\bname\s*=\s*"([^"]+)"', block)[1]
            target[name] = block

    def resolve(name):
        block = entities[name]
        parent = re.search(r'\bclone\s*=\s*"([^"]+)"', block)
        inherited = resolve(parent[1]) if parent else (None, 1)
        mesh = re.search(r'\bpdxmesh\s*=\s*"([^"]+)"', block)
        scale = re.search(r'\bscale\s*=\s*([\d.]+)', block)
        return mesh[1] if mesh else inherited[0], float(scale[1]) if scale else inherited[1]

    base = (ROOT / 'gfx/entities/zz_ADISCORD_army_headquarters.asset').read_text()
    props = []
    for block in blocks(base, 'attach'):
        (field, name), (node, entity) = re.findall(r'\b(\w+)\s*=\s*"([^"]+)"', block)
        assert field == 'name'
        mesh, scale = resolve(entity)
        filename = re.search(r'\bfile\s*=\s*"([^"]+)"', meshes[mesh])[1]
        before = set(bpy.data.objects)
        pdx.import_meshfile(str(GAME / filename), imp_locs=False, join_materials=False)
        added = set(bpy.data.objects) - before
        pivot = bpy.data.objects.new(name + '_attachment', None)
        bpy.context.scene.collection.objects.link(pivot)
        for obj in added:
            if obj.parent not in added:
                transform = obj.matrix_world.copy()
                obj.parent = pivot
                obj.matrix_parent_inverse = Matrix.Identity(4)
                obj.matrix_basis = transform
        parts = [obj for obj in added if obj.type == 'MESH' and not any(
            mat.get(pdx.PDX_SHADER) == 'Collision' for mat in obj.data.materials
        )]
        for obj in added:
            if obj.type == 'MESH' and obj not in parts:
                obj.hide_render = True
        props.append((name, node, pivot, parts, scale))
    assert len(props) == 7
    return props


def verify(output):
    import bpy
    from mathutils import Matrix, Vector

    pdx, pdx_data = pdx_tools()
    directory = output / 'package' / DEST
    path = directory / 'RUS_hq.mesh'
    hashes = {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
              for p in sorted(directory.glob('RUS_hq*'))}
    tree = pdx_data.read_meshfile(str(path))
    donor = pdx_data.read_meshfile(str(DONOR))
    assert [(n.tag, n.attrib) for n in tree.find('locator')] == [
        (n.tag, n.attrib) for n in donor.find('locator')
    ]
    donor_bones = next(shape.find('skeleton') for shape in donor.find('object')
                       if shape.find('skeleton') is not None)
    shapes = []
    for shape in tree.find('object'):
        bones = shape.find('skeleton')
        assert [b.tag for b in bones] == [b.tag for b in donor_bones]
        for element in shape.findall('mesh'):
            data = pdx_data.PDXData(element)
            count = len(data.p) // 3
            assert 0 < count < 65536
            assert all(math.isfinite(v) for v in data.p + data.n + data.u0)
            assert len(data.tri) % 3 == 0 and min(data.tri) >= 0 and max(data.tri) < count
            stride = data.skin.bones[0]
            assert 1 <= stride <= 4
            assert len(data.skin.w) == len(data.skin.ix) == count * stride
            assert all(0 <= i < len(bones) for i in data.skin.ix)
            weighted = set()
            for i in range(count):
                weights = data.skin.w[i * stride:(i + 1) * stride]
                indices = data.skin.ix[i * stride:(i + 1) * stride]
                assert abs(sum(weights) - 1) < 0.001
                weighted.update(index for index, weight in zip(indices, weights) if weight > 0)
            for i in weighted:
                assert bones[i].attrib.get('pa') == donor_bones[i].attrib.get('pa')
                assert max(abs(a - b) for a, b in zip(
                    bones[i].attrib['tx'], donor_bones[i].attrib['tx'],
                )) < 0.001
            for key in ('diff', 'n', 'spec'):
                assert (directory / getattr(data.material, key)[0]).is_file()
            shapes.append({'vertices': count, 'triangles': len(data.tri) // 3})
    bpy.ops.wm.read_factory_settings(use_empty=True)
    pdx.import_meshfile(str(path), imp_locs=False)
    scene = bpy.context.scene
    rigs = [obj for obj in scene.objects if obj.type == 'ARMATURE']
    bodies = [obj for obj in scene.objects if obj.type == 'MESH']
    props = preview_attachments(pdx)

    def apply_attachments():
        visible = []
        objects = list(bodies)
        for name, node, pivot, parts, scale in props:
            matrix = rigs[0].pose.bones[node].matrix
            shown = max(abs(value) for value in matrix.to_scale()) > 0.001
            pivot.matrix_world = rigs[0].matrix_world @ matrix @ Matrix.Scale(scale, 4)
            for obj in parts:
                obj.hide_render = not shown
            if shown:
                visible.append(name)
                objects.extend(parts)
        bpy.context.view_layer.update()
        return visible, objects

    scene.render.engine = 'CYCLES'
    scene.cycles.samples = 24
    scene.render.resolution_x = 800
    scene.render.resolution_y = 1000
    scene.render.resolution_percentage = 100
    scene.world = bpy.data.worlds.new('Officer studio')
    scene.world.use_nodes = True
    scene.world.node_tree.nodes['Background'].inputs[0].default_value = (0.16, 0.19, 0.23, 1)
    for mat in bpy.data.materials:
        if mat.use_nodes:
            shader = mat.node_tree.nodes.get('Principled BSDF')
            if shader:
                for link in list(shader.inputs['Roughness'].links):
                    mat.node_tree.links.remove(link)
                shader.inputs['Roughness'].default_value = 0.8
    target = Vector((0, 0, 3.8))
    for location, power in (((4, -8, 12), 1600), ((-6, -1, 8), 950), ((2, 5, 11), 1700)):
        bpy.ops.object.light_add(type='AREA', location=location)
        obj = bpy.context.object
        obj.data.energy = power
        obj.data.size = 6
        obj.rotation_euler = (target - obj.location).to_track_quat('-Z', 'Y').to_euler()
    bpy.ops.object.camera_add(location=(9, -20, 9))
    camera = bpy.context.object
    camera.data.type = 'ORTHO'
    camera.data.ortho_scale = 8.9
    camera.rotation_euler = (target - camera.location).to_track_quat('-Z', 'Y').to_euler()
    scene.camera = camera
    clips = {name: NATIVE / (filename + '.anim') for name, filename in ANIMATIONS.items()}
    clips['death'] = GAME / 'gfx/models/units/GER_infantry_death_mg.anim'
    poses = {}
    for name, clip in clips.items():
        for rig in rigs:
            rig.animation_data_clear()
            for bone in rig.pose.bones:
                bone.matrix_basis.identity()
        pdx.import_animfile(str(clip))
        frames = (1, (scene.frame_end + 1) // 2, scene.frame_end)
        for frame in frames:
            scene.frame_set(frame)
            visible, objects = apply_attachments()
            graph = bpy.context.evaluated_depsgraph_get()
            for obj in objects:
                evaluated = obj.evaluated_get(graph)
                assert all(math.isfinite(c) for v in evaluated.data.vertices for c in v.co)
                assert max((evaluated.matrix_world @ v.co).length
                           for v in evaluated.data.vertices) < 20
        poses[name] = {'sampled_frames': frames}
        if name in ('idle', 'notes', 'scout', 'move', 'attack02'):
            scene.frame_set(frames[1])
            visible, _ = apply_attachments()
            poses[name]['render_attachments'] = visible
            scene.render.filepath = str(output / f'RUS_hq_{name}.png')
            bpy.ops.render.render(write_still=True)
        if name == 'idle':
            bpy.ops.wm.save_as_mainfile(filepath=str(output / 'RUS_hq_preview.blend'))
            camera.location = (-9, 20, 9)
            camera.rotation_euler = (target - camera.location).to_track_quat('-Z', 'Y').to_euler()
            scene.render.filepath = str(output / 'RUS_hq_back.png')
            bpy.ops.render.render(write_still=True)
            camera.location = (9, -20, 9)
            camera.rotation_euler = (target - camera.location).to_track_quat('-Z', 'Y').to_euler()
    assert hashes == {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                      for p in sorted(directory.glob('RUS_hq*'))}
    report = {'hashes': hashes, 'shapes': shapes, 'poses': poses,
              'native_locators_unchanged': True, 'bones': len(donor_bones)}
    (output / 'verification.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    action = parser.add_mutually_exclusive_group()
    action.add_argument('--build', action='store_true')
    action.add_argument('--verify', action='store_true')
    action.add_argument('--apply', action='store_true')
    action.add_argument('--check', action='store_true')
    argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else sys.argv[1:]
    args = parser.parse_args(argv)
    if args.build:
        build(args.output.resolve())
    elif args.verify:
        verify(args.output.resolve())
    else:
        package(args.output.resolve(), args.apply, args.check)
