"""Apply verified style changes to current main without overwriting newer work."""
from pathlib import Path
import ast
import collections
import hashlib
import json
import re
import subprocess
import sys
from replay_style import python_format, LUA_TOKENS, LOC_VALUES
from style_formatter import format_clausewitz, format_localisation, format_lua_defines, token_signature

root, cache, evidence, old_manifest = (Path(value).resolve() for value in sys.argv[1:])
old = json.loads(old_manifest.read_text())
old_items = {item['path']: item for item in old['changed']}
base = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root).decode().strip()
upstream = subprocess.check_output(['git', 'diff', '--name-only', old['base'], base], cwd=root).decode().splitlines()
registry = json.loads((root / 'tools/data/generated_output_owners.json').read_text())
protected = set()
for family in registry['families']:
    for pattern in family['output_globs']:
        protected.update(path.relative_to(root).as_posix() for path in root.glob(pattern) if path.is_file())
focus_outputs = {name for name in protected if name.startswith('common/national_focus/')}
originals = {name: (root / name).read_bytes() for name in focus_outputs}
kinds = {name: 'generated-focus' for name in focus_outputs}
report = {'base': base, 'previous_base': old['base'], 'upstream_files_preserved': upstream, 'changed': [], 'counts': {}, 'python_exceptions': [], 'excluded': old['excluded']}

def classify(name):
    path = Path(name)
    if name in focus_outputs:
        return 'generated-focus'
    if name in protected:
        return None
    if name in old_items:
        return old_items[name]['kind']
    if name.startswith('tools/') and path.suffix == '.py':
        return 'python'
    if name.startswith('localisation/') and path.suffix == '.yml':
        return 'localisation'
    if name == 'common/defines/ADISCORD_defines_changes.lua':
        return 'lua'
    if path.suffix not in {'.txt', '.gfx', '.gui', '.asset', '.mod'}:
        return None
    if name.split('/')[0] not in {'common', 'events', 'focus_trees', 'history', 'interface', 'gfx', 'music', 'sound', 'tutorial', 'country_metadata', 'portraits'} and name != 'descriptor.mod':
        return None
    if name.startswith('interface/') and not any(marker in path.name for marker in ['ADISCORD', 'superevents', 'sva.', '_random_portraits']):
        return None
    if name in {'gfx/entities/zz_ADISCORD_country_infantry.asset', 'gfx/entities/ADISCORD_country_infantry.gfx'}:
        return None
    if name.startswith('gfx/') and path.suffix == '.txt':
        return None
    source = (root / name).read_text(encoding='utf-8-sig')
    if re.search(r'(?im)^#.*(?:generated by|autogenerated|auto-generated|do not edit)', '\n'.join(source.splitlines()[:6])):
        return None
    return 'clausewitz'

for name in sorted(set(old_items) | set(upstream)):
    path = root / name
    if not path.is_file():
        continue
    kind = classify(name)
    if not kind or kind == 'generated-focus':
        continue
    before = path.read_bytes()
    source = before.decode('utf-8-sig')
    if name in old_items and hashlib.sha256(before).hexdigest() == old_items[name]['before']:
        after = (cache / name).read_bytes()
        assert hashlib.sha256(after).hexdigest() == old_items[name]['after'], name
    elif kind == 'python':
        _, after, exception = python_format(path)
        if exception:
            report['python_exceptions'].append({'path': name, 'reason': exception})
            continue
    else:
        if kind == 'localisation':
            formatted = format_localisation(source)
            assert format_localisation(formatted) == formatted, name
        elif kind == 'lua':
            formatted = format_lua_defines(source)
            assert format_lua_defines(formatted) == formatted, name
        else:
            indent = int(name.startswith('focus_trees/') and '# @section ' in source)
            formatted = format_clausewitz(source, base_indent=indent)
            assert format_clausewitz(formatted, base_indent=indent) == formatted, name
        after = formatted.encode('utf-8')
        if before.startswith(b'\xef\xbb\xbf'):
            after = b'\xef\xbb\xbf' + after
    target = after.decode('utf-8-sig')
    if kind == 'python':
        assert ast.dump(ast.parse(source), include_attributes=False) == ast.dump(ast.parse(target), include_attributes=False), name
    elif kind == 'localisation':
        assert LOC_VALUES.findall(source) == LOC_VALUES.findall(target), name
    elif kind == 'lua':
        assert LUA_TOKENS.findall(source) == LUA_TOKENS.findall(target), name
    else:
        assert token_signature(source) == token_signature(target), name
    assert before.startswith(b'\xef\xbb\xbf') == after.startswith(b'\xef\xbb\xbf'), name
    if before != after:
        originals[name] = before
        kinds[name] = kind
        path.write_bytes(after)
for stage, option in enumerate(['--check', '--apply', '--check']):
    result = subprocess.run([sys.executable, '-B', '-m', 'tools.builders.build_adiscord_focus_trees', option], cwd=root, capture_output=True, text=True)
    with (evidence / 'focus-generation.log').open('a') as stream:
        stream.write(option + '\n' + result.stdout + result.stderr)
    if stage > 0:
        assert result.returncode == 0, result.stdout + result.stderr
for name, before in sorted(originals.items()):
    after = (root / name).read_bytes()
    if after == before:
        continue
    if kinds[name] == 'generated-focus':
        assert token_signature(before.decode('utf-8-sig')) == token_signature(after.decode('utf-8-sig')), name
    assert before.startswith(b'\xef\xbb\xbf') == after.startswith(b'\xef\xbb\xbf'), name
    report['changed'].append({'path': name, 'kind': kinds[name], 'before': hashlib.sha256(before).hexdigest(), 'after': hashlib.sha256(after).hexdigest()})
actual = subprocess.check_output(['git', 'diff', '--name-only'], cwd=root).decode().splitlines()
assert set(actual) == {item['path'] for item in report['changed']}
subprocess.run(['git', 'diff', '--check'], cwd=root, check=True)
report['counts'] = dict(collections.Counter(item['kind'] for item in report['changed']))
report['python_exceptions'].extend(item for item in old['python_exceptions'] if item['path'] not in upstream)
(evidence / 'style-manifest.json').write_text(json.dumps(report, indent=2))
(evidence / 'style.patch').write_bytes(subprocess.check_output(['git', 'diff', '--binary'], cwd=root))
print(json.dumps({'base': base, 'changed': len(report['changed']), 'counts': report['counts'], 'upstream_files_preserved': len(upstream), 'python_exceptions': report['python_exceptions']}, indent=2), flush=True)
