"""Replay reviewed style-only transformations in an isolated checkout."""
from pathlib import Path
import argparse
import ast
import collections
import concurrent.futures
import hashlib
import json
import re
import subprocess
import sys
import black
from style_formatter import format_clausewitz, format_localisation, format_lua_defines, token_signature

BASE = 'ca0125941411ef3798b7e4f051b58755f8210ea6'
ROOTS = {'common', 'events', 'focus_trees', 'history', 'interface', 'gfx', 'music', 'sound', 'tutorial', 'country_metadata', 'portraits', 'map'}
SUFFIXES = {'.txt', '.gfx', '.gui', '.asset', '.mod'}
LUA_TOKENS = re.compile(r'''"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|--[^\n]*|[^\s]''')
LOC_VALUES = re.compile(r'^\s*([^:#\s]+):(\d*)\s*("(?:\\.|[^"\\])*")', re.M)

def python_format(path):
    before = path.read_bytes()
    source = before.decode('utf-8-sig')
    try:
        original = ast.dump(ast.parse(source), include_attributes=False)
    except SyntaxError as exc:
        return str(path), None, 'syntax-error: ' + str(exc)
    mode = black.Mode(line_length=88, string_normalization=False, target_versions={black.TargetVersion.PY313})
    try:
        formatted = black.format_file_contents(source, fast=True, mode=mode)
    except black.NothingChanged:
        formatted = source
    if ast.dump(ast.parse(formatted), include_attributes=False) != original:
        return str(path), None, 'retained: formatter changes a docstring literal'
    try:
        twice = black.format_file_contents(formatted, fast=True, mode=mode)
    except black.NothingChanged:
        twice = formatted
    assert formatted == twice, path
    result = formatted.encode('utf-8')
    if before.startswith(b'\xef\xbb\xbf'):
        result = b'\xef\xbb\xbf' + result
    return str(path), result, None

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('root', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    root, output = args.root.resolve(), args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    names = subprocess.check_output(['git', 'ls-files', '-z'], cwd=root).decode().split('\0')
    names = [name for name in names if name]
    registry = json.loads((root / 'tools/data/generated_output_owners.json').read_text())
    protected = collections.defaultdict(list)
    for family in registry['families']:
        for pattern in family['output_globs']:
            for path in root.glob(pattern):
                if path.is_file():
                    protected[path.relative_to(root).as_posix()].append(family['id'])
    report = {'base': BASE, 'changed': [], 'unchanged': [], 'excluded': [], 'python_exceptions': [], 'counts': {}}
    originals = {}
    kinds = {}
    generated_focus = {name for name in protected if name.startswith('common/national_focus/')}
    for name in sorted(generated_focus):
        originals[name] = (root / name).read_bytes()
        kinds[name] = 'generated-focus'
    python_paths = []
    def write(name, before, after, kind):
        originals.setdefault(name, before)
        kinds[name] = kind
        if before != after:
            (root / name).write_bytes(after)
        else:
            report['unchanged'].append(name)
    for name in sorted(names):
        path = root / name
        if name.startswith('tools/') and path.suffix == '.py':
            python_paths.append(path)
            continue
        is_script = path.suffix in SUFFIXES and (name.split('/')[0] in ROOTS or name == 'descriptor.mod')
        is_loc = name.startswith('localisation/') and path.suffix == '.yml'
        if not (is_script or is_loc or name == 'common/defines/ADISCORD_defines_changes.lua'):
            continue
        before = path.read_bytes()
        try:
            source = before.decode('utf-8-sig')
        except UnicodeDecodeError:
            report['excluded'].append({'path': name, 'reason': 'not UTF-8 text'})
            continue
        if '\0' in source:
            report['excluded'].append({'path': name, 'reason': 'binary content'})
            continue
        reason = None
        if name in protected:
            reason = 'generated: ' + ', '.join(protected[name])
        elif re.search(r'(?im)^#.*(?:generated by|autogenerated|auto-generated|do not edit)', '\n'.join(source.splitlines()[:6])):
            reason = 'generated output header'
        elif name in {'gfx/entities/zz_ADISCORD_country_infantry.asset', 'gfx/entities/ADISCORD_country_infantry.gfx'}:
            reason = 'infantry model generator output'
        elif name.startswith('interface/') and not any(marker in path.name for marker in ['ADISCORD', 'superevents', 'sva.', '_random_portraits']):
            reason = 'vanilla-derived interface'
        elif name.startswith('map/'):
            reason = 'line-sensitive or generated map data'
        elif name.startswith('gfx/') and path.suffix == '.txt':
            reason = 'non-Clausewitz asset documentation'
        if reason:
            report['excluded'].append({'path': name, 'reason': reason})
            continue
        if is_loc:
            formatted = format_localisation(source)
            assert LOC_VALUES.findall(source) == LOC_VALUES.findall(formatted), name
            assert format_localisation(formatted) == formatted, name
            kind = 'localisation'
        elif name.endswith('.lua'):
            formatted = format_lua_defines(source)
            assert LUA_TOKENS.findall(source) == LUA_TOKENS.findall(formatted), name
            assert format_lua_defines(formatted) == formatted, name
            kind = 'lua'
        else:
            indent = 1 if name.startswith('focus_trees/') and '# @section ' in source else 0
            formatted = format_clausewitz(source, base_indent=indent)
            assert token_signature(source) == token_signature(formatted), name
            assert format_clausewitz(formatted, base_indent=indent) == formatted, name
            kind = 'clausewitz'
        after = formatted.encode('utf-8')
        if before.startswith(b'\xef\xbb\xbf'):
            after = b'\xef\xbb\xbf' + after
        write(name, before, after, kind)
    with concurrent.futures.ProcessPoolExecutor(max_workers=2, max_tasks_per_child=1) as pool:
        for filename, after, exception in pool.map(python_format, python_paths):
            path = Path(filename)
            name = path.relative_to(root).as_posix()
            if exception:
                report['python_exceptions'].append({'path': name, 'reason': exception})
            else:
                write(name, path.read_bytes(), after, 'python')
    for stage, option in enumerate(['--check', '--apply', '--check']):
        result = subprocess.run([sys.executable, '-B', '-m', 'tools.builders.build_adiscord_focus_trees', option], cwd=root, capture_output=True, text=True)
        with (output / 'focus-generation.log').open('a') as stream:
            stream.write(option + '\n' + result.stdout + result.stderr)
        if stage > 0:
            assert result.returncode == 0, result.stdout + result.stderr
    for name in sorted(generated_focus):
        after = (root / name).read_bytes()
        assert token_signature(originals[name].decode('utf-8-sig')) == token_signature(after.decode('utf-8-sig')), name
    for name, before in sorted(originals.items()):
        after = (root / name).read_bytes()
        if before == after:
            continue
        assert before.startswith(b'\xef\xbb\xbf') == after.startswith(b'\xef\xbb\xbf'), name
        report['changed'].append({'path': name, 'kind': kinds[name], 'before': hashlib.sha256(before).hexdigest(), 'after': hashlib.sha256(after).hexdigest()})
    actual = subprocess.check_output(['git', 'diff', '--name-only'], cwd=root).decode().splitlines()
    assert set(actual) == {item['path'] for item in report['changed']}, (actual, report['changed'])
    subprocess.run(['git', 'diff', '--check'], cwd=root, check=True)
    report['counts'] = dict(collections.Counter(item['kind'] for item in report['changed']))
    (output / 'style-manifest.json').write_text(json.dumps(report, indent=2))
    (output / 'style.patch').write_bytes(subprocess.check_output(['git', 'diff', '--binary'], cwd=root))
    print(json.dumps({'changed': len(report['changed']), 'counts': report['counts'], 'python_exceptions': report['python_exceptions']}, indent=2), flush=True)

if __name__ == '__main__':
    main()
