NDefines.NGame.START_DATE = "2163.1.1.1";
	NDefines.NGame.END_DATE = "2193.1.1.1";

	NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 20.0;
	NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 3;

	NDefines.NGraphics.POLITICAL_GRID_SMALL_BOX_LIMIT = 50
	NDefines_Graphics.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 3

	NDefines.NMilitary.COMBAT_MINIMUM_TIME = 8
	NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.2
	NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.4
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = -0.15
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.30
	NDefines.NMilitary.BASE_FORT_PENALTY = -0.15
	NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.5
	NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.2
	NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.001
	NDefines.NMilitary.LAND_COMBAT_ORG_DICE_SIZE = 2
	NDefines.NMilitary.LAND_COMBAT_STR_DICE_SIZE = 6
	NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.15
	NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.01
	NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.03
	NDefines.NMilitary.LAND_COMBAT_COLLATERAL_FACTOR = 0.07
	NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.75
	NDefines.NMilitary.STRATEGIC_INFRA_SPEED = 15.0;
	NDefines.NMilitary.HOURLY_ORG_MOVEMENT_IMPACT = -0.1
	NDefines.NMilitary.ZERO_ORG_MOVEMENT_MODIFIER = -0.2
	NDefines.NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT = -0.03
	NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 18
	NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 24
	NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 5
	NDefines.NMilitary.GARRISON_ORDER_ARMY_CAP_FACTOR = 1.0
	NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 5
	NDefines.NMilitary.ATTRITION_DAMAGE_ORG = 0.04
	NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.05
	NDefines.NMilitary.ATTRITION_EQUIPMENT_PER_TYPE_LOSS_CHANCE = 0.05
	NDefines.NMilitary.TACTIC_SWAP_FREQUENCEY = 24
	NDefines.NMilitary.BASE_COMBAT_WIDTH = 120
	NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 60
	NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.5
	NDefines.NMilitary.SLOWEST_SPEED = 4
	NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -0.5
	NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY_MAX = -0.66
	NDefines.NMilitary.RETREAT_SPEED_FACTOR = 1.0
	NDefines.NMilitary.STRATEGIC_SPEED_BASE = 30.0
	NDefines.NMilitary.SUPPLY_GRACE = 336
	NDefines.NMilitary.MAX_OUT_OF_SUPPLY_DAYS = 28
	NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.6
	NDefines.NMilitary.NON_CORE_SUPPLY_SPEED = -0.25
	NDefines.NMilitary.NON_CORE_SUPPLY_AIR_SPEED = -0.125
	NDefines.NMilitary.OUT_OF_SUPPLY_MORALE = -0.15
	NDefines.NMilitary.AIR_SUPPORT_BASE = 0.3
	NDefines.NMilitary.REINFORCE_CHANCE = 0.05
	NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.25
	NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.3
	NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 1000
	NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 1000
	NDefines.NMilitary.MAX_AIR_EXPERIENCE = 1000
	NDefines.NMilitary.ENCIRCLED_PENALTY = -0.15

	NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100
	NDefines.NGame.LAG_DAYS_FOR_PAUSE = 30
	NDefines.NGame.GAME_SPEED_SECONDS = { 1.0, 0.25, 0.1, 0.05, 0.0 }
	NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36
	NDefines.NCountry.EVENT_PROCESS_OFFSET = 30
	NDefines_Graphics.NGraphics.MAPICON_GROUP_PASSES = 10

	NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 4.0
	NDefines.NAI.MIN_PLAN_VALUE_TO_MICRO_INACTIVE = 0.2

	NDefines.NAI.VP_LEVEL_IMPORTANCE_HIGH = 25
	NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 10
	NDefines.NAI.VP_LEVEL_IMPORTANCE_LOW = 1

	NDefines.NAI.MAX_DIST_PORT_RUSH = 40.0
	NDefines.NAI.FORTIFIED_RATIO_TO_CONSIDER_A_FRONT_FORTIFIED = 0.3
	NDefines.NAI.HEAVILY_FORTIFIED_RATIO_TO_CONSIDER_A_FRONT_FORTIFIED = 0.3
	NDefines.NAI.INVASION_DISTANCE_RANDOMNESS = 400
	NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 50.0

	NDefines.NMilitary.PLAN_PORVINCE_PORT_BASE_IMPORTANCE = 15.0
	NDefines.NMilitary.PLAN_PORVINCE_PORT_LEVEL_FACTOR = 0.5
	NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_BASE_IMPORTANCE = 3.0
	NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_POPULATED_FACTOR = 1.5
	NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_LEVEL_FACTOR = 0.25

	NDefines.NMilitary.PLAN_PROVINCE_PORT_BASE_IMPORTANCE = 15.0
	NDefines.NMilitary.PLAN_PROVINCE_PORT_LEVEL_FACTOR = 0.5
	NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_BASE_IMPORTANCE = 3.0
	NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_POPULATED_FACTOR = 1.5
	NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_LEVEL_FACTOR = 0.25

	NDefines.NMilitary.PLAN_AREA_DEFENSE_ENEMY_UNIT_FACTOR = -1.5
	NDefines.NMilitary.PLAN_AREA_DEFENSE_FORT_IMPORTANCE = 0.30
	NDefines.NMilitary.PLAN_AREA_DEFENSE_COASTAL_FORT_IMPORTANCE = 5.0
	NDefines.NMilitary.PLAN_AREA_DEFENSE_COAST_NO_FORT_IMPORTANCE = 2.0

	NDefines.NMilitary.PLAN_STICKINESS_FACTOR = 95.0
	NDefines.NMilitary.PLAN_STICKINESS_IGNORE_STACK_LIMIT = 1

	NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_LIMIT = 6.0
	NDefines.NMilitary.PLAN_EXECUTE_BALANCED_LIMIT = -10.0
	NDefines.NMilitary.PLAN_EXECUTE_RUSH = -200
	NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_MAX_FORT = 4

	NDefines.NMilitary.PLAN_MAX_PROGRESS_TO_JOIN = 0.54

	NDefines.NMilitary.PLAN_BLITZ_OPTIMISM = 0.3

	NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 1 -0.75
	NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 250
	NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 500
	NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 350
	NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 4000
	NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 500
	NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.01
	NDefines.NAir.ACCIDENT_CHANCE_CARRIER_MULT = 1
	NDefines.NAir.ACCIDENT_CHANCE_BALANCE_MULT = 0.5
	NDefines.NAir.AIR_WING_XP_MAX = 1500.0
	NDefines.NAir.AIR_WING_XP_LEVELS = { 300, 600, 900, 1200 }
	NDefines.NAir.AIR_WING_BOMB_DAMAGE_FACTOR = 55
	NDefines.NAir.COMBAT_STAT_IMPORTANCE_SPEED = 0.5
	NDefines.NAir.COMBAT_STAT_IMPORTANCE_AGILITY = 2
	NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0.85
	NDefines.NAir.COMBAT_AMOUNT_DIFF_AFFECT_GANG_CHANCE = 0.4
	NDefines.NAir.COMBAT_ONE_ON_ONE_CHANCE = 0.7
	NDefines.NAir.COMBAT_SITUATION_WIN_CHANCE_FROM_STATS = 1.5
	NDefines.NAir.COMBAT_SITUATION_WIN_CHANCE_FROM_GANG = 0.8
	NDefines.NAir.COMBAT_MAX_WINGS_AT_ONCE = 8500
	NDefines.NAir.COMBAT_MAX_WINGS_AT_GROUND_ATTACK = 6000
	NDefines.NAir.COMBAT_MAX_WINGS_AT_ONCE_PORT_STRIKE = 2500
	NDefines.NAir.DETECT_CHANCE_FROM_AIRCRAFTS_EFFECTIVE_COUNT = 350
	NDefines.NAir.DETECT_CHANCE_FROM_NIGHT = -0.05
	NDefines.NAir.CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 3
	NDefines.NAir.HOURS_DELAY_AFTER_EACH_COMBAT = 3
	NDefines.NAir.NAVAL_STRIKE_TARGETTING_TO_AMOUNT = 0.40
	NDefines.NAir.NAVAL_STRIKE_DETECTION_BALANCE_FACTOR = 0.7
	NDefines.NAir.NAVAL_RECON_DETECTION_BALANCE_FACTOR = 0.7
	NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_STR = 3
	NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 3.50
	NDefines.NAir.AIR_AGILITY_TO_NAVAL_STRIKE_AGILITY = 0.02
	NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_DAMAGE_FACTOR = 50
	NDefines.NAir.AIR_COMBAT_FINAL_DAMAGE_SCALE = 0.025
	NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.02
	NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_CHANCE = 0.03
	NDefines.NAir.AIR_DEPLOYMENT_DAYS = 1
	NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 0.10
	NDefines.NAir.NAVAL_COMBAT_EXTERNAL_PLANES_JOIN_RATIO = 0.02
	NDefines.NAir.NAVAL_COMBAT_EXTERNAL_PLANES_JOIN_RATIO_PER_DAY = 0.2
	NDefines.NAir.NAVAL_COMBAT_EXTERNAL_PLANES_MIN_CAP = 4
	NDefines.NAir.MISSION_COMMAND_POWER_COSTS = {
		0.0,
		0.0,
		0.0,
		0.0,
		0.0,
		1000.0,
		0.0,
		0.0,
        0.0,
		0.0,
		0.05,
		0.0,
		0.0,
		0.0,
		0.0,
		0.0,
	}

	NDefines.NNavy.MAX_SUBMARINES_PER_AUTO_TASK_FORCE = 10
	NDefines.NNavy.BEST_CAPITALS_TO_CARRIER_RATIO = 4
	NDefines.NNavy.BEST_CAPITALS_TO_SCREENS_RATIO = 0.5
	NDefines.NNavy.DETECTION_CHANCE_BALANCE = 1.5
	NDefines.NNavy.DECRYPTION_SPOTTING_BONUS = 0.3
	NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE_TORPEDO_MULT = 30
	NDefines.NNavy.COMBAT_LOW_ORG_HIT_CHANCE_PENALTY = -0.8
	NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_CHANCE = 0.2
	NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_DAMAGE_MULT = 2.0
	NDefines.NNavy.COMBAT_DAMAGE_TO_STR_FACTOR = 1.0
	NDefines.NNavy.COMBAT_DAMAGE_TO_ORG_FACTOR = 1.0
	NDefines.NNavy.COMBAT_DAMAGE_REDUCTION_ON_RETREAT = 0.75
	NDefines.NNavy.COMBAT_ESCAPING_SPEED_BALANCE = 0.9
	NDefines.NNavy.COMBAT_SHIP_SPEED_TO_FIELD_FACTOR = 0.15
	NDefines.NNavy.COMBAT_MAX_DISTANCE_TO_CENTER_LINE = 350
	NDefines.NNavy.COMBAT_MAX_DISTANCE_TO_ARRIVE = 600
	NDefines.NNavy.COMBAT_MIN_DURATION = 16
	NDefines.NNavy.COMBAT_CHASE_RESIGNATION_HOURS = 6
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW = 0.35
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM = 0.55
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_HIGH = 0.85
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW_COMBAT = 0.75
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM_COMBAT = 0.5
	NDefines.NNavy.REPAIR_AND_RETURN_PRIO_HIGH_COMBAT = 0.35
	NDefines.NNavy.REPAIR_AND_RETURN_UNIT_DYING_STR = 0.35
	NDefines.NNavy.NAVY_EXPENSIVE_IC = 18000
	NDefines.NNavy.CONVOY_EFFICIENCY_MIN_VALUE = 0.1
	NDefines.NNavy.AMPHIBIOUS_LANDING_PENALTY = -0.5
	NDefines.NNavy.BASE_CARRIER_SORTIE_EFFICIENCY = 0.5
	NDefines.NNavy.NAVAL_SPEED_MODIFIER = 0.1
	NDefines.NNavy.NAVAL_TRANSFER_BASE_SPEED = 12
	NDefines.NNavy.NAVAL_INVASION_PREPARE_HOURS = 96
	NDefines.NNavy.ANTI_AIR_TARGETING = 1.8
	NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.2
	NDefines.NNavy.ANTI_AIR_ATTACK_TO_AMOUNT = 0.01
	NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO = 0.1
	NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE = 0.2
	NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.35
	NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.99
	NDefines.NNavy.ENEMY_AIR_SUPERIORITY_IMPACT = -0.7

	NDefines.NNavy.MISSION_FUEL_COSTS = {
		0.1,
		0.8,
		1.0,
		1.0,
		0.8,
		1.0,
		1.0,
		0.8,
		0.0,
		1.0,
	}
	NDefines.NNavy.ORG_COST_WHILE_MOVING = {
		0.3,
		0.2,
		0.25,
		0.2,
		0.2,
		0.2,
		0.2,
		0.2,
		0.3,
		0.2,
	}
	NDefines.NNavy.MISSION_SUPREMACY_RATIOS = {
		0.5,
		1.0,
		0.5,
		0.75,
		0.75,
		0.35,
		0.35,
		0.20,
		0.0,
		1.0,
	}
	NDefines.NNavy.MIN_HOURS_TO_SHUFFLE_NEWLY_ASSIGNED_PATROLS = 10 * 24
	NDefines.NNavy.BASE_SPOTTING_FROM_RADAR = 15
	NDefines.NNavy.BASE_SPOTTING = 5
	NDefines.NNavy.SPOTTING_MULTIPLIER_FOR_SUB = 0.60
	NDefines.NNavy.SPOTTING_MULTIPLIER_FOR_SURFACE = 1.2
	NDefines.NNavy.ESCAPE_SPEED_HIDDEN_SUB = 0.45
	NDefines.NNavy.ESCAPE_SPEED_SUB_BASE = 0.30
	NDefines.NNavy.SUB_DETECTION_CHANCE_BASE = 3
	NDefines.NNavy.SUB_DETECTION_CHANCE_BASE_SPOTTING_EFFECT = 0.3
	NDefines.NNavy.SUB_DETECTION_CHANCE_SPOTTING_SPEED_EFFECT = 1.2
	NDefines.NNavy.SUB_DETECTION_CHANCE_BASE_SPOTTING_POW_EFFECT = 1.01
	NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 1
	NDefines.NNavy.HEAVY_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.1
	NDefines.NNavy.LIGHT_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.05
	NDefines.NNavy.COMBAT_MIN_HIT_CHANCE = 0.05
	NDefines.NNavy.MIN_HIT_PROFILE_MULT = 0.1
	NDefines.NNavy.GUN_HIT_PROFILES = {
		40.0,
		50.0,
		20.0,
	}
	NDefines.NNavy.BASE_GUN_COOLDOWNS = {
		2.0,
		4.0,
		2.0,
	}

	NDefines.NNavy.DEPTH_CHARGES_HIT_CHANCE_MULT = 1.5
	NDefines.NNavy.DEPTH_CHARGES_DAMAGE_MULT = 2
	NDefines.NNavy.DEPTH_CHARGES_HIT_PROFILE = 24.0
	NDefines.NNavy.CARRIER_STACK_PENALTY = 2
	NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 0.5
	NDefines.NNavy.CARRIER_ONLY_COMBAT_ACTIVATE_TIME = 0
	NDefines.NNavy.CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 6
	NDefines.NNavy.ALL_SHIPS_ACTIVATE_TIME = 8
	NDefines.NNavy.NAVAL_MINES_DECAY_AT_PEACE_TIME = 0.05
	NDefines.NNavy.ATTRITION_WHILE_MOVING_FACTOR = 2.5
	NDefines.NNavy.ATTRITION_DAMAGE_ORG = 0.03
	NDefines.NNavy.ATTRITION_DAMAGE_STR = 0.09
	NDefines.NNavy.ATTRITION_STR_DAMAGE_CHANCE = 0.4
	NDefines.NNavy.TRAINING_ACCIDENT_CHANCES = 0.005
	NDefines.NNavy.TRAINING_ACCIDENT_STRENGTH_LOSS_FACTOR = 0.02
	NDefines.NNavy.TRAINING_EXPERIENCE_FACTOR = 0.15
	NDefines.NNavy.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 15
	NDefines.NNavy.LEADER_EXPERIENCE_SCALE = 2
	NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT = 0.01
	NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT_FROM_AIR = 0.1
	NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 1.5
	NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 1.5
	NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.25
	NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.1
	NDefines.NNavy.NEW_NAVY_LEADER_LEVEL_CHANCES = {
		0.90,
		0.10
	}
	NDefines.NNavy.CARRIER_TASKFORCE_MAX_CARRIER_COUNT = 1
	NDefines.NNavy.CAPITAL_TASKFORCE_MAX_CAPITAL_COUNT = 6
	NDefines.NNavy.SCREEN_TASKFORCE_MAX_SHIP_COUNT = 2
	NDefines.NNavy.SUB_TASKFORCE_MAX_SHIP_COUNT = 4
	NDefines.NNavy.MAX_SUBMARINES_PER_AUTO_TASK_FORCE = 4
	NDefines.NNavy.MAX_CAPITALS_PER_AUTO_TASK_FORCE = 6

	NDefines.NNavy.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 4
	NDefines.NNavy.CAPITALS_TO_CARRIER_RATIO = 4
	NDefines.NNavy.SCREENS_TO_CAPITAL_RATIO = 2

	NDefines.NNavy.BASE_POSITIONING = 0.70
	NDefines.NNavy.RELATIVE_SURFACE_DETECTION_TO_POSITIONING_FACTOR = 0.01
	NDefines.NNavy.MAX_POSITIONING_BONUS_FROM_SURFACE_DETECTION = 0
	NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 0.5
	NDefines.NNavy.MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 1
	NDefines.NNavy.HIGHER_CARRIER_RATIO_POSITIONING_PENALTY_FACTOR = 0.4
	NDefines.NNavy.MAX_CARRIER_RATIO_POSITIONING_PENALTY_FACTOR = 0.2
	NDefines.NNavy.POSITIONING_PENALTY_FOR_SHIPS_JOINED_COMBAT_AFTER_IT_STARTS = 0.025
	NDefines.NNavy.MAX_POSITIONING_PENALTY_FOR_NEWLY_JOINED_SHIPS = 0.3
	NDefines.NNavy.POSITIONING_PENALTY_HOURLY_DECAY_FOR_NEWLY_JOINED_SHIPS = 0.04
	NDefines.NNavy.DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.9
	NDefines.NNavy.SCREENING_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.65
	NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.9
	NDefines.NNavy.SUBMARINE_REVEAL_ON_MINIMUM_POSITIONING = 3.0

	NDefines.NNavy.NAVAL_COMBAT_SUB_DETECTION_FACTOR = 1.5
	NDefines.NNavy.SUBMARINE_HIDE_TIMEOUT = 20
	NDefines.NNavy.SUBMARINE_REVEALED_TIMEOUT = 16
	NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 8
	NDefines.NNavy.SUBMARINE_REVEAL_POW = 3.0
	NDefines.NNavy.SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.05

	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_MAX = 10.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_SLOPE = 10.0

	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_EXTERNAL_FACTOR = 1
	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_INTERNAL_EFFICIENCY_FACTOR = 1.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_AGILITY_TO_SUB_DETECTION = 0.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_STRIKE_ATTACK_TO_SUB_DETECTION = 0.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_STRIKE_TARGETING_TO_SUB_DETECTION = 0.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_MAX_SPEED_TO_SUB_DETECTION = 0.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_PLANE_COUNT_TO_SUB_DETECTION = 1
	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_DECAY_RATE = 1.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_DETECTION_FACTOR = 0.0

	NDefines.NNavy.NAVAL_COMBAT_AIR_SUB_TARGET_SCORE = 10
	NDefines.NNavy.NAVAL_COMBAT_AIR_CAPITAL_TARGET_SCORE = 25
	NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_SCORE = 200
	NDefines.NNavy.NAVAL_COMBAT_AIR_CONVOY_TARGET_SCORE = 1.0
	NDefines.NNavy.NAVAL_COMBAT_AIR_STRENGTH_TARGET_SCORE = 5
	NDefines.NNavy.NAVAL_COMBAT_AIR_LOW_AA_TARGET_SCORE = 5

	NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.01
	NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.01
	NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_CONVOY = 2
	NDefines.NNavy.WAR_SCORE_DECAY_FOR_BUILT_CONVOY = 1

	NDefines.NAI.BASE_RELUCTANCE = 35
	NDefines.NAI.DIPLOMATIC_ACTION_PROPOSE_SCORE = 25
	NDefines.NAI.DILPOMATIC_ACTION_DECLARE_WAR_WARGOAL_BASE = 75
	NDefines.NAI.DIPLOMACY_IMPROVE_RELATION_COST_FACTOR = 10.0
	NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 75
	NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 75
	NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 40
	NDefines.NAI.RESEARCH_NEW_WEIGHT_FACTOR = 0.5
	NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 4
	NDefines.NAI.RESEARCH_BASE_DAYS = 750
	NDefines.NAI.MIN_DELIVERED_TRADE_FRACTION = 0.6
	NDefines.NAI.PRODUCTION_UNAVAILABLE_RESORCE_FACTORY_FACTOR = 0.4
	NDefines.NAI.MAX_VOLUNTEER_ARMY_FRACTION = 0.5
	NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.60
	NDefines.NAI.CALL_ALLY_BASE_DESIRE = 25
	NDefines.NAI.CALL_ALLY_DEMOCRATIC_DESIRE = 25
	NDefines.NAI.CALL_ALLY_FASCIST_DESIRE = 25
	NDefines.NAI.CALL_ALLY_COMMUNIST_DESIRE = 25
	NDefines.NAI.JOIN_ALLY_BASE_DESIRE = 25
	NDefines.NAI.JOIN_ALLY_DEMOCRATIC_DESIRE = 25
	NDefines.NAI.JOIN_ALLY_FASCIST_DESIRE = 25
	NDefines.NAI.JOIN_ALLY_COMMUNIST_DESIRE = 25
	NDefines.NAI.LENDLEASE_FRACTION_OF_PRODUCTION = 0.6
	NDefines.NAI.PLAN_MOVE_MIN_ORG_TO_ENEMY_PROVINCE = 5.0
	NDefines.NAI.PLAN_FRONTUNIT_DISTANCE_FACTOR = 20
	NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 1.2
	NDefines.NAI.PLAN_STEP_COST_LIMIT = 15
	NDefines.NAI.PLAN_FRONT_SECTION_MAX_LENGTH = 9
	NDefines.NAI.PLAN_FRONT_SECTION_MIN_LENGTH = 4
	NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 1000
	NDefines.NAI.SEND_VOLUNTEER_EVAL_BASE_DISTANCE = 100.0
	NDefines.NAI.SEND_VOLUNTEER_EVAL_CONTAINMENT_FACTOR = 0.05
	NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 7.5
	NDefines.NAI.EASY_TARGET_FRONT_IMPORTANCE = 1.3
	NDefines.NAI.MICRO_POCKET_SIZE = 10
	NDefines.NAI.FRONT_REASSIGN_DISTANCE = 120.0
	NDefines.NAI.OLD_FRONT_IMPORTANCE_FACTOR = 1.80
	NDefines.NAI.FRONT_TERRAIN_DEFENSE_FACTOR = 4.0
	NDefines.NAI.FRONT_TERRAIN_ATTACK_FACTOR = 8.0
	NDefines.NAI.BASE_DISTANCE_TO_CARE = 200.0
	NDefines.NAI.MIN_FORCE_RATIO_TO_PROTECT = 1.5
	NDefines.NAI.STR_UNIT_STRONG = 0.65
	NDefines.NAI.MIN_STATE_VALUE_TO_PROTECT = 3.5
	NDefines.NAI.CALL_ALLY_WT_LIMIT = 0.6
	NDefines.NAI.AIR_WING_REINFORCEMENT_LIMIT = 50
	NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 30
	NDefines.NAI.STRATEGIC_BOMBING_DEFENCE_IMPORTANCE = 500.0
	NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 1.75
	NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 0.2
	NDefines.NAI.NAVAL_MISSION_INVASION_BASE = 5000
	NDefines.NAI.SCARY_LEVEL_AVERAGE_DEFENSE = -0.6
	NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.45
	NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 24
	NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.15
	NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -0.2
	NDefines.NAI.REQUEST_LEND_LEASE_CONTAINS_VALUE = 60
	NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_LAND = 0.5
	NDefines.NAI.REQUEST_LEND_LEASE_PRODUCTION_DAYS_LAND = 500
	NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_AIR = 0.3
	NDefines.NAI.REQUEST_LEND_LEASE_PRODUCTION_DAYS_AIR = 28
	NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_NAVAL = 0.3
	NDefines.NAI.NAVAL_TRANSFER_AIR_IMPORTANCE = 1.0
	NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP = 5
	NDefines.NAI.FOCUS_TREE_CONTINUE_FACTOR = 1
	NDefines.NAI.FALLBACK_LOSING_FACTOR = 0.0

	NDefines.NAI.LAND_DESIGN_ALTERNATIVE_ABSENT = 1
	NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_LESSER_TECH = 1
	NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_EQUAL_TECH = 1
	NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_GREATER_TECH = 1

	NDefines.NAI.LAND_DESIGN_DEMAND_FIELD_DIVISION = 50
	NDefines.NAI.LAND_DESIGN_DEMAND_TRAINING_DIVISION = 50
	NDefines.NAI.LAND_DESIGN_DEMAND_GARRISON_DIVISION = 10
	NDefines.NAI.LAND_DESIGN_DEMAND_UNUSED_TEMPLATE = 10
	NDefines.NAI.LAND_DESIGN_DEMAND_ABSENT = 10

	NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.85
	NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.85

	NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.65
	NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.65

	NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.5
	NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.5

	NDefines.NAI.PLAN_FACTION_STRONG_TO_EXECUTE = 0.65
	NDefines.NAI.ORG_UNIT_STRONG = 0.75
	NDefines.NAI.STR_UNIT_STRONG = 0.75

	NDefines.NAI.PLAN_FACTION_NORMAL_TO_EXECUTE = 0.65
	NDefines.NAI.ORG_UNIT_NORMAL = 0.6
	NDefines.NAI.STR_UNIT_NORMAL = 0.6

	NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.5
	NDefines.NAI.ORG_UNIT_WEAK = 0.45
	NDefines.NAI.STR_UNIT_WEAK = 0.4

	NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.5
	NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.4

	NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.1
	NDefines.NAI.REDEPLOY_DISTANCE_VS_ORDER_SIZE = 1.0
	NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 5.0

	NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 5.0
	NDefines.NAI.DESIRED_UNITS_FACTOR_FRONT_ORDER = 4.5
	NDefines.NAI.MIN_UNITS_FACTOR_FRONT_ORDER = 3.0

	NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.0
	NDefines.NCountry.MIN_STABILITY = -1.0
	NDefines.NCountry.MIN_WAR_SUPPORT = -1.0
	NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.075
	NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 6
	NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 0.5
	NDefines.NCountry.AIR_VOLUNTEER_PLANES_RATIO = 0.4
	NDefines.NCountry.AIR_VOLUNTEER_BASES_CAPACITY_LIMIT = 0.25
	NDefines.NCountry.SCORCHED_EARTH_STATE_COST = 20

	NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1.5

	NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 14

	NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 4.50
	NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 20
	NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 200
	NDefines.NProduction.INFRA_MAX_CONSTRUCTION_COST_EFFECT = 1
	NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 1
	NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0.05

	NDefines.NIndustrialOrganisation.ASSIGN_DESIGN_TEAM_PP_COST_PER_DAY = 0.05

	NDefines.NBuildings.MAX_SHARED_SLOTS = 25
	NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.2
	NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0.1

	NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 30.0
	NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 3

	NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 1.00
	NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 1.15
	NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.0
	NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.1
	NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 1.0

	NDefines.NDiplomacy.PEACE_SCORE_SCALE_FACTOR = 2.15
	NDefines.NDiplomacy.PEACE_SCORE_DISTRIBUTION = { 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 }

	NAI = {

		AIR_DESIGN_ALTERNATIVE_ABSENT = 1000000,
		AIR_DESIGN_ALTERNATIVE_OF_LESSER_TECH = 10000,
		AIR_DESIGN_ALTERNATIVE_OF_EQUAL_TECH = 100,
		AIR_DESIGN_ALTERNATIVE_OF_GREATER_TECH = 1,
		AIR_DESIGN_DEMAND_MAX = 33,
		AIR_DESIGN_DEMAND_MIN = 1,
		AIR_DESIGN_DEMAND_ABSENT = 0,
		AIR_DESIGN_CUTOFF_AS_PERCENTAGE_OF_MAX = 0.34,
		ARMY_LEADER_ASSIGN_OVERCAPACITY = -1000,
	}

	NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
	NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 16384
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 16384

	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_TOP = 100.0
	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_BOTTOM = 100.0
	NDefines.NGraphics.CAMERA_ZOOM_KEY_SCALE = 0.01
	NDefines.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 25.0

	NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 2058.0
	NDefines.NFrontend.CAMERA_MIN_HEIGHT = 30.0

NDefines_Graphics.NMapIcons.STRATEGIC_AIR_PRIORITY_AIR_MISSION = 290

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1500}

NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 100
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 325.0
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 400
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_AREA_HUGE = 220
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_HUGE = 100
NDefines_Graphics.NGraphics.MAPICON_GROUP_STRATEGIC_SIZE = 1000
NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_SPLIT_SELECTED_LIMIT = 10
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 200
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 0

NDefines_Graphics.NGraphics.COMMANDGROUP_PRESET_COLORS_HSV = {
	0.0/360.0, 1.0, 0.75,
	10.0/360.0, 1.0, 0.75,
	60.0/360.0, 1.0, 0.75,
	120.0/360.0, 0.85, 0.75,
	155.0/360.0, 1.0, 0.75,
	180.0/360.0, 1.0, 0.75,
	220.0/360.0, 1.0, 0.75,
	260.0/360.0, 1.0, 0.85,
	330.0/360.0, 0, 0.75
}

NDefines_Graphics.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 20

NDefines_Graphics.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 900
NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 900

NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_BAD = {0.65, 0, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_GOOD = {0, 0.65, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1}

NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 250.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_A = 250
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 250

NDefines_Graphics.NGraphics.RESISTANCE_COLOR_GOOD = {0.0, 0.65, 0, 1}
NDefines_Graphics.NGraphics.RESISTANCE_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines_Graphics.NGraphics.RESISTANCE_COLOR_BAD = {0.65, 0, 0, 1}

NDefines_Graphics.NGraphics.STRATEGIC_NAVY_COLOR_MISSION = {0.65, 0.65, 0.0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_NAVY_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1}

NDefines_Graphics.NGraphics.ROOT_FRONT_OFFSET = 2
