"""Generate the shared native vehicle registries; --check precedes --apply.

Aircraft geometry and textures are packaged by build_country_aircraft.
Existing country vehicles retain their own mesh exports and animations.
"""

import argparse
import json
from pathlib import Path
import re


MOD = Path(__file__).resolve().parents[4]
DEST = MOD / "gfx/models/units/ADISCORD_country_vehicles"
HEADER = "# Generated by tools/assets/source/country_vehicles/package_vehicles.py\n"
TAGS = ("VAL", "NOD", "STP")
FAMILIES = ("DEF", "ARB", "WRK", "RUS", "NAM")
PREFIXES = ("early_", "", "future_")
ARAB_TAGS = ("SHL", "AZH", "GLP", "KDR", "KYZ", "MZR", "RHM", "SDR", "SLF")
VORKERLAND_TAGS = (
    "WRK", "DAN", "EYR", "EGC", "RIV", "YOR", "ZAO", "PWR", "VLA",
    "ROM", "SOL", "TRU", "WCG", "VAD", "WKR", "TVA", "IBA",
)
EXISTING_AIR = {"VAL": "VAL", "NOD": "NOD", "STP": "NOD", "STS": "STP", "SRP": "STP"}
NAMES = tuple(f"{tag}_{role}" for tag in TAGS for role in ("tank", "fighter", "cas"))
NAMES += tuple(f"{tag}_{prefix}{role}" for tag in TAGS for prefix in ("early_", "future_")
               for role in ("fighter", "cas"))
SHARED_NAMES = tuple(f"{family}_{prefix}{role}" for family in FAMILIES
                     for prefix in PREFIXES for role in ("fighter", "cas"))
SPECIAL_NAMES = ("STS_taran",)


def air_routes():
    routes = {}
    for role in ("fighter", "cas"):
        routes[f"ADISCORD_{role}"] = (role, 0)
        routes[f"ADISCORD_{role}_archetype"] = (role, 0)
        for level in range(4):
            routes[f"ADISCORD_{role}_{level}"] = (role, min(level, 2))
    equipment = {
        "fighter": (
            ("fighter_airframe_2163",),
            ("fighter_airframe_2161", "fighter_airframe_2166"),
            ("interceptor_airframe_2183", "fighter_airframe_2170", "fighter_airframe_2175"),
        ),
        "cas": (
            ("cas_airframe_2170",),
            ("attack_airframe_2163", "vtol_airframe_2170"),
            ("drone_airframe_2183", "attack_airframe_2170", "attack_airframe_2175"),
        ),
    }
    for role, tiers in equipment.items():
        for tier, names in enumerate(tiers):
            for name in names:
                routes[f"ADISCORD_{name}"] = (role, tier)
    return routes


def country_families():
    tags = set()
    for path in sorted((MOD / "common/country_tags").glob("*.txt")):
        tags.update(re.findall(r'^\s*([A-Z0-9]{3})\s*=\s*"', path.read_text(encoding="utf-8-sig"), re.M))
    regional = set(ARAB_TAGS) | set(VORKERLAND_TAGS) | {"RUS", "NAM"}
    if not regional <= tags:
        raise ValueError(f"Unregistered aircraft tags: {sorted(regional - tags)}")
    families = dict.fromkeys(sorted(tags), "DEF")
    families.update(dict.fromkeys(ARAB_TAGS, "ARB"))
    families.update(dict.fromkeys(VORKERLAND_TAGS, "WRK"))
    families.update(EXISTING_AIR)
    families.update({"RUS": "RUS", "NAM": "NAM"})
    # A cosmetic name takes priority over the real country in native entity lookup.
    for path in sorted((MOD / "common/countries").glob("*.txt")):
        for name in re.findall(r'^([A-Z][A-Za-z0-9_]+)\s*=\s*\{', path.read_text(encoding="utf-8-sig"), re.M):
            tag = name.split("_", 1)[0]
            if tag in families and "_" in name:
                families[name] = families[tag]
    # Confederation identities are also used directly from country history.
    for path in sorted((MOD / "history/countries").glob("*.txt")):
        for name in re.findall(r'\bset_cosmetic_tag\s*=\s*([A-Za-z0-9_]+)', path.read_text(encoding="utf-8-sig")):
            tag = name.split("_", 1)[0]
            if tag in families:
                families[name] = families[tag]
    return families


def alias(parent, name):
    return f'entity = {{ clone = "{parent}" name = "{name}" }}\n'


def registry():
    gfx = HEADER + "objectTypes = {\n"
    assets = HEADER
    animations = HEADER
    for name in NAMES + SHARED_NAMES + SPECIAL_NAMES:
        tank = name.endswith("_tank") or name == "STS_taran"
        clips = ("idle", "move", "attack") if tank else ("idle",)
        gfx += f'\tpdxmesh = {{\n\t\tname = "ADISCORD_{name}_mesh"\n'
        gfx += f'\t\tfile = "gfx/models/units/ADISCORD_country_vehicles/{name}.mesh"\n'
        scale = 0.50 if name == "STS_taran" else 0.55 if tank else 1.0
        gfx += f'\t\tscale = {scale}\n'
        for clip in clips:
            gfx += f'\t\tanimation = {{ id = "{clip}" type = "ADISCORD_{name}_{clip}_animation" }}\n'
            animations += f'animation = {{ name = "ADISCORD_{name}_{clip}_animation" file = "{name}_{clip}.anim" }}\n'
        gfx += "\t}\n"
        parent = "medium_armor_entity" if tank else "light_plane_entity"
        assets += f'\nentity = {{\n\tclone = "{parent}"\n\tname = "ADISCORD_{name}_entity"\n'
        assets += f'\tpdxmesh = "ADISCORD_{name}_mesh"\n\tdefault_state = "idle"\n'
        if not tank:
            assets += "\tscale = 0.20\n"
        assets += "}\n"
    gfx += "}\n"
    routes = air_routes()
    assets += "\n"
    for name, (role, tier) in routes.items():
        assets += alias(f"ADISCORD_DEF_{PREFIXES[tier]}{role}_entity", f"{name}_entity")
    tank_routes = (
        "medium_armor", *[f"medium_armor_{level}" for level in range(5)],
        "ADISCORD_combat_platform", "ADISCORD_combat_platform_archetype",
        *[f"ADISCORD_combat_platform_{year}" for year in (2170, 2183, 2200)],
    )
    for tag in (*TAGS, "STS", "SRP"):
        family = "STP" if tag in ("STS", "SRP") else tag
        for name in tank_routes:
            assets += alias(f"ADISCORD_{family}_tank_entity", f"{tag}_{name}_entity")
    for tag, family in country_families().items():
        assets += "\n"
        for name, (role, tier) in routes.items():
            assets += alias(f"ADISCORD_{family}_{PREFIXES[tier]}{role}_entity", f"{tag}_{name}_entity")
        # Native carrier and medium-aircraft sprites share the country's design language.
        for sprite, role in (("light_plane", "fighter"), ("medium_plane", "cas")):
            assets += alias(f"ADISCORD_{family}_early_{role}_entity", f"{tag}_{sprite}_entity")
            for level in range(4):
                prefix = PREFIXES[min(level, 2)]
                assets += alias(f"ADISCORD_{family}_{prefix}{role}_entity", f"{tag}_{sprite}_{level}_entity")
    assets += "\n"
    for prefix in ("", "STS_", "STS_steland_", "STS_hegemony_"):
        for name in ("STP_taran", "STP_taran_0", "STP_taran_equipment", "STP_taran_equipment_1"):
            assets += alias("ADISCORD_STS_taran_entity", f"{prefix}{name}_entity")
    return gfx, assets, animations


def package(apply=False):
    gfx, assets, animations = registry()
    files = {
        MOD / "gfx/entities/ADISCORD_country_vehicles.gfx": gfx.encode(),
        MOD / "gfx/entities/zz_ADISCORD_country_vehicles.asset": assets.encode(),
        DEST / "animation.asset": animations.encode(),
    }
    changed = [str(path.relative_to(MOD)) for path, data in files.items()
               if not path.is_file() or path.read_bytes() != data]
    if apply:
        for path, data in files.items():
            if str(path.relative_to(MOD)) in changed:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
    return changed


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true")
    action.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    changed = package(args.apply)
    print(json.dumps({"changed": changed, "applied": args.apply}, indent=2))
    if args.check and changed:
        raise SystemExit(1)
