"""Prepare technical atlases and package the nine country vehicle assets."""
import argparse
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MOD = ROOT.parents[3]
DEST = MOD / "gfx/models/units/ADISCORD_country_vehicles"
TAGS = ("VAL", "NOD", "STP")
ROLES = ("tank", "fighter", "cas")
NAMES = tuple(f"{tag}_{role}" for tag in TAGS for role in ROLES)
HEADER = "# Generated by tools/assets/source/country_vehicles/package_vehicles.py\n"


def prepare():
    from PIL import Image, ImageDraw, ImageOps, ImageStat
    sys.path.insert(0, str(ROOT.parent / "WRK_unity_tower"))
    from package_tower import mip_chain
    paints = {"VAL": ((77, 75, 59), (44, 47, 40), (126, 99, 53)),
              "NOD": ((52, 65, 67), (31, 42, 45), (103, 124, 119)),
              "STP": ((76, 83, 65), (43, 50, 40), (117, 58, 45))}
    source = Image.open(ROOT / "weathering_source.png").convert("RGB")
    w, h = source.size
    surfaces = [source.crop(box).resize((256,256), Image.Resampling.LANCZOS)
                for box in ((0,0,w//2,h//2),(w//2,0,w,h//2),(0,h//2,w//2,h),(w//2,h//2,w,h))]
    # DDS compilation uses separate tank/air atlases: airframes never receive
    # the heavy mud layer intended for tracks and lower armor.
    for tag, (base, dark, accent) in paints.items():
        for family in ("tank", "air"):
            rng = random.Random(tag + family)
            palette = [base, dark, (30, 32, 31), (111, 115, 113), (164, 167, 154),
                       (29, 71, 84), accent, (18, 22, 23), (170, 171, 157),
                       tuple(min(255, c + 17) for c in base), (156, 43, 29), (176, 92, 49),
                       (62, 66, 64), (207, 208, 191), (78, 87, 69), (207, 210, 199)]
            atlas = Image.new("RGBA", (1024, 1024))
            for index, color in enumerate(palette):
                tile = Image.new("RGBA", (256, 256))
                pixels = []
                surface = surfaces[2 if index == 2 else 3 if index in (3,7,11,12) else 1 if family == "air" else 0]
                luminance = ImageOps.grayscale(surface)
                mean = max(1, ImageStat.Stat(luminance).mean[0])
                for y in range(256):
                    for x in range(256):
                        noise = rng.randrange(-3, 4)
                        wear = luminance.getpixel((x,y)) / mean
                        # Broad material variation survives texture minification;
                        # tiny per-pixel noise alone disappears at map zoom.
                        factor = .35 + wear*.65
                        panel = -14 if index in (0, 1, 9) and (x % 128 < 2 or y % 128 < 2) else 0
                        if index == 7:
                            noise += 15 if y % 18 < 4 else 0
                        if index == 2:
                            noise += 12 if (x + y // 8) % 28 < 4 else 0
                        if index == 5:
                            factor = .65 + .25*y/256
                        pixels.append(tuple(max(0, min(255, round(c*factor) + noise + panel)) for c in color) + (255,))
                tile.putdata(pixels)
                draw = ImageDraw.Draw(tile)
                if index in (0, 9):
                    for _ in range(30):
                        x, y = rng.randrange(256), rng.randrange(256)
                        draw.line((x, y, x + rng.randrange(2, 9), y + 1), fill=(*dark, 255), width=1)
                if index == 8:
                    flag = Image.open(MOD / f"gfx/flags/{tag}.tga").convert("RGBA")
                    flag = flag.resize((200,124),Image.Resampling.LANCZOS)
                    # Treat the white field as unpainted hull, leaving only a worn stencil.
                    flag.putdata([(*tuple(round(c*.64) for c in p[:3]),
                                   0 if min(p[:3]) > 190 else 170) for p in flag.getdata()])
                    tile = surfaces[0 if family == "tank" else 1].copy().convert("RGBA")
                    tile.putdata([(*tuple(round(base[i]*(sum(p[:3])/3/mean)*.8) for i in range(3)),255) for p in tile.getdata()])
                    tile.paste(flag, ((256 - flag.width) // 2, (256 - flag.height) // 2), flag)
                atlas.paste(tile, ((index % 4) * 256, (index // 4) * 256))
            maps = {"diffuse": atlas,
                    "normal": Image.new("RGBA", (1024, 1024), (128, 128, 0, 128)),
                    "specular": Image.new("RGBA", (1024, 1024), (0, 17, 0, 18))}
            # The glass swatch is opaque: transparency sorting is unnecessary at map scale.
            ImageDraw.Draw(maps["specular"]).rectangle((256, 256, 511, 511), fill=(0, 72, 0, 90))
            for channel, image in maps.items():
                (ROOT / f"{tag}_{family}_{channel}.dds").write_bytes(mip_chain(image))


def registry():
    gfx, assets, animations = HEADER + "objectTypes = {\n", HEADER, HEADER
    for role in ("fighter", "cas"):
        assets += f'entity = {{ clone = "light_plane_entity" name = "ADISCORD_{role}_entity" }}\n'
    for name in NAMES:
        role = name.split("_")[1]
        clips = ("idle", "move", "attack") if role == "tank" else ("idle",)
        gfx += f'\tpdxmesh = {{\n\t\tname = "ADISCORD_{name}_mesh"\n\t\tfile = "gfx/models/units/ADISCORD_country_vehicles/{name}.mesh"\n'
        gfx += f'\t\tscale = {0.55 if role == "tank" else 1.0}\n'
        for clip in clips:
            gfx += f'\t\tanimation = {{ id = "{clip}" type = "ADISCORD_{name}_{clip}_animation" }}\n'
            animations += f'animation = {{ name = "ADISCORD_{name}_{clip}_animation" file = "{name}_{clip}.anim" }}\n'
        gfx += "\t}\n"
        parent = "medium_armor_entity" if role == "tank" else "light_plane_entity"
        assets += f'\nentity = {{\n\tclone = "{parent}"\n\tname = "ADISCORD_{name}_entity"\n\tpdxmesh = "ADISCORD_{name}_mesh"\n\tdefault_state = "idle"\n'
        if role != "tank":
            assets += '\tscale = 0.20\n'
        assets += "}\n"
    gfx += "}\n"
    # Role sprites separate fighter and CAS even when the map requests a subunit
    # instead of a concrete equipment id. Other countries keep the native fallback.
    routes = {
        "tank": ["medium_armor", *[f"medium_armor_{i}" for i in range(0, 5)],
                 "ADISCORD_combat_platform", "ADISCORD_combat_platform_archetype",
                 *[f"ADISCORD_combat_platform_{year}" for year in (2170, 2183, 2200)]],
        "fighter": ["ADISCORD_fighter", "ADISCORD_fighter_0", "ADISCORD_fighter_1", "ADISCORD_fighter_2", "ADISCORD_fighter_3",
                    "ADISCORD_fighter_archetype", "ADISCORD_fighter_airframe_2163", "ADISCORD_interceptor_airframe_2183"],
        "cas": ["ADISCORD_cas", "ADISCORD_cas_0", "ADISCORD_cas_1", "ADISCORD_cas_archetype", "ADISCORD_cas_airframe_2170"],
    }
    for tag in (*TAGS, "STS", "SRP"):
        source = "STP" if tag in ("STS", "SRP") else tag
        for role, aliases in routes.items():
            for alias in aliases:
                assets += f'entity = {{ clone = "ADISCORD_{source}_{role}_entity" name = "{tag}_{alias}_entity" }}\n'
    return gfx, assets, animations


def package(apply=False):
    files = {}
    for name in NAMES:
        clips = ("idle", "move", "attack") if name.endswith("_tank") else ("idle",)
        filenames = [name + ".mesh"] + [f"{name}_{clip}.anim" for clip in clips]
        for filename in filenames:
            files[DEST / filename] = (ROOT / filename).read_bytes()
    for tag in TAGS:
        for family in ("tank", "air"):
            for channel in ("diffuse", "normal", "specular"):
                filename = f"{tag}_{family}_{channel}.dds"
                files[DEST / filename] = (ROOT / filename).read_bytes()
    gfx, assets, animations = registry()
    files[MOD / "gfx/entities/ADISCORD_country_vehicles.gfx"] = gfx.encode()
    files[MOD / "gfx/entities/zz_ADISCORD_country_vehicles.asset"] = assets.encode()
    files[DEST / "animation.asset"] = animations.encode()
    changed = [str(p.relative_to(MOD)) for p, content in files.items() if not p.is_file() or p.read_bytes() != content]
    if apply:
        for path, content in files.items():
            if str(path.relative_to(MOD)) in changed:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    print(json.dumps({"files": len(files), "changed": changed, "applied": apply}))
    return changed


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    for option in ("prepare", "apply", "check"):
        parser.add_argument("--" + option, action="store_true")
    args = parser.parse_args()
    if args.prepare:
        prepare()
    elif package(args.apply) and args.check:
        raise SystemExit(1)
