"""Own the officer mesh package, native HQ entity family and model selection pools."""
import argparse
import hashlib
import json
import re
from pathlib import Path

from PIL import Image
from package_regulars import named_blocks, dds_mips, resize_channels

ROOT=Path(__file__).resolve().parent
MOD=ROOT.parents[3]
GAME=Path('Z:/SteamLibrary/steamapps/common/Hearts of Iron IV')
CONFIG=json.loads((ROOT/'headquarters.json').read_text())
DEST=MOD/'gfx/models/units/ADISCORD_headquarters'
HEADER='# Generated by tools/assets/source/STP_regulars/package_headquarters.py\n'


def prepare():
    donor=GAME/'gfx/models/units/army_headquarters'
    for label in CONFIG:
        for part in ('body','gear'):
            source=ROOT/(f'{label}_body_source.png' if part=='body' else f'{label}_gear_diffuse.png')
            Image.open(source).convert('RGBA').save(ROOT/f'{label}_{part}_diffuse.dds',pixel_format='DXT5')
            for kind in ('normal','specular'):
                path=donor/f'generic_army_headquarters_{kind}.dds' if part=='body' else ROOT/f'{label}_gear_{kind}.png'
                if part=='body':
                    (ROOT/f'{label}_{part}_{kind}.dds').write_bytes(path.read_bytes())
                else:
                    resize_channels(Image.open(path).convert('RGBA'),(1024,1024)).save(
                        ROOT/f'{label}_{part}_{kind}.dds',pixel_format='DXT5')


def bindings():
    source=named_blocks((GAME/'gfx/entities/army_headquarters.gfx').read_text(),'pdxmesh')['generic_army_headquarters_mesh']
    base=named_blocks((GAME/'gfx/entities/units_army_headquarters.asset').read_text(),'entity')['army_headquarters_entity']
    base=re.sub(r'\bname\s*=\s*"army_headquarters_entity"',
                'name = "ADISCORD_army_headquarters_base_entity"',base,count=1)
    meshes=[];entities=[base];pools=[]
    for label,config in CONFIG.items():
        mesh=re.sub(r'\bname\s*=\s*"[^"]+"',f'name = "ADISCORD_{label}_mesh"',source,count=1)
        mesh=re.sub(r'\bfile\s*=\s*"[^"]+"',f'file = "gfx/models/units/ADISCORD_headquarters/{label}.mesh"',mesh,count=1)
        meshes.append(mesh)
        entity=(config['tag']+'_' if config['tag'] else '')+'army_headquarters_entity'
        entities.append(f'entity = {{ clone = "ADISCORD_army_headquarters_base_entity" name = "{entity}" pdxmesh = "ADISCORD_{label}_mesh" }}')
        scope=config['tag'] or 'default';weight=3000 if config['tag'] else 1000
        pools.append(f'{scope} = {{\n\tinfantry_equipment = {{\n\t\tpool = {{\n'
                     f'\t\t\tsub_units = {{ hq_support_company }}\n\t\t\tweight = {weight}\n'
                     f'\t\t\tmodels = {{ {entity} }}\n\t\t}}\n\t}}\n}}')
    return {
        MOD/'gfx/entities/ADISCORD_army_headquarters.gfx':(HEADER+'objectTypes = {\n'+'\n'.join(meshes)+'\n}\n').encode(),
        MOD/'gfx/entities/zz_ADISCORD_army_headquarters.asset':(HEADER+'\n'.join(entities)+'\n').encode(),
        MOD/'gfx/interface/equipmentdesigner/graphic_db/ADISCORD_army_headquarters.txt':(HEADER+'\n\n'.join(pools)+'\n').encode(),
    }


def package(apply=False,preview=None):
    files=bindings()
    for label in CONFIG:
        files[DEST/f'{label}.mesh']=(ROOT/f'{label}.mesh').read_bytes()
        for part in ('body','gear'):
            for kind in ('diffuse','normal','specular'):
                name=f'{label}_{part}_{kind}.dds'
                files[DEST/name]=dds_mips(ROOT/name,packed_channels=kind!='diffuse')
    changed=[path for path,data in files.items() if not path.is_file() or path.read_bytes()!=data]
    if preview:
        preview=Path(preview).resolve()
        assert preview!=MOD and MOD not in preview.parents
        for path,data in files.items():
            target=preview/path.relative_to(MOD);target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
    if apply:
        for path in changed:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(files[path])
        (ROOT/'hq_package_report.json').write_text(json.dumps({str(path.relative_to(MOD)):{'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)} for path,data in files.items()},indent=2)+'\n')
    print(json.dumps({'files':len(files),'changed':[str(p.relative_to(MOD)) for p in changed],'applied':apply},indent=2))
    return changed


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--prepare',action='store_true')
    parser.add_argument('--apply',action='store_true');parser.add_argument('--check',action='store_true')
    parser.add_argument('--preview',type=Path);args=parser.parse_args()
    if args.prepare:prepare()
    elif package(args.apply,args.preview) and args.check:raise SystemExit(1)
