"""Assemble authored focus sources into flat native national_focus files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from tools.lib.paths import repository_root


ROOT = repository_root()
SOURCE_ROOT = ROOT / "focus_trees"
OUTPUT_ROOT = ROOT / "common/national_focus"
SOURCES = {
    "RUS/main/focuses.txt": "ADISCORD_national_focus_RUS.txt",
    "VAL/main/focuses.txt": "ADISCORD_national_focus_VAL.txt",
    "shared/bookmark/focuses.txt": "ADISCORD_national_focus_bookmark.txt",
    "shared/generic/focuses.txt": "generic.txt",
    "STP/preparation/focuses.txt": "ADISCORD_STP_preparation.txt",
    "STP/civil_war/focuses.txt": "ADISCORD_STP_civil_war.txt",
    "STP/postwar/focuses.txt": "ADISCORD_STP_exile_return.txt",
    "VAL/defeated/focuses.txt": "ADISCORD_VAL_defeated.txt",
    "VAL/administration/focuses.txt": "ADISCORD_VAL_administration.txt",
    "Vorkerland/civil_war/focuses.txt": "ADISCORD_Vorkerland_civil_war.txt",
    "Vorkerland/iba_norvane/focuses.txt": "ADISCORD_Vorkerland_iba_norvane.txt",
    "Vorkerland/zao/focuses.txt": "ADISCORD_Vorkerland_zao.txt",
}
INCLUDE = re.compile(r"(?m)^# @include ([\w/.-]+)#(\w+)\n")
SECTION = re.compile(r"(?m)^# @section (\w+)\n")


def render_source(relative: str, used_sections: set[tuple[Path, str]] | None = None) -> str:
    """Expand named fragments without changing their native scope or order."""
    source = (SOURCE_ROOT / relative).read_text(encoding="utf-8")

    def expand(match: re.Match[str]) -> str:
        path = (SOURCE_ROOT / match[1]).resolve()
        if not path.is_relative_to(SOURCE_ROOT.resolve()):
            raise ValueError(f"Include escapes focus sources: {match[1]}")
        text = path.read_text(encoding="utf-8")
        sections = list(SECTION.finditer(text))
        selected = [i for i, item in enumerate(sections) if item[1] == match[2]]
        if len(selected) != 1:
            raise ValueError(f"Expected one section {match[0].strip()}")
        if used_sections is not None:
            key = (path, match[2])
            if key in used_sections:
                raise ValueError(f"Focus section included more than once: {key}")
            used_sections.add(key)
        index = selected[0]
        end = sections[index + 1].start() if index + 1 < len(sections) else len(text)
        fragment = text[sections[index].end():end]
        if "# @include" in fragment:
            raise ValueError("Focus fragments cannot include other fragments")
        return fragment

    rendered = INCLUDE.sub(expand, source)
    if "# @include" in rendered:
        raise ValueError(f"Malformed include in {relative}")
    if rendered.startswith("\ufeff"):
        raise ValueError(f"Gameplay source has a BOM: {relative}")
    return rendered


def expected_outputs() -> dict[Path, bytes]:
    outputs = {}
    used_sections: set[tuple[Path, str]] = set()
    for source, filename in SOURCES.items():
        header = (
            "# Generated by tools/builders/build_adiscord_focus_trees.py; do not edit.\n"
            f"# Source: focus_trees/{source}\n\n"
        )
        outputs[OUTPUT_ROOT / filename] = (header + render_source(source, used_sections)).encode("utf-8")
    for path in SOURCE_ROOT.rglob("*.txt"):
        text = path.read_text(encoding="utf-8")
        if text.startswith("\ufeff"):
            raise ValueError(f"Gameplay source has a BOM: {path}")
        sections = list(SECTION.finditer(text))
        if not sections and path.relative_to(SOURCE_ROOT).as_posix() not in SOURCES:
            raise ValueError(f"Unregistered focus source: {path}")
        for section in sections:
            if (path.resolve(), section[1]) not in used_sections:
                raise ValueError(f"Unused focus section: {path}#{section[1]}")
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true")
    actions.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, data in expected_outputs().items():
        if path.is_file() and path.read_bytes() == data:
            continue
        stale.append(path)
        if args.apply:
            path.write_bytes(data)
        print(f"{'WROTE' if args.apply else 'STALE'}: {path.relative_to(ROOT)}")
    if not stale:
        print("Focus tree outputs are current.")
    return int(bool(stale) and not args.apply)


if __name__ == "__main__":
    raise SystemExit(main())
