"""Build national-focus chrome while retaining the current native widget tree."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

from tools.lib.adiscord_ui_contracts import replace_gui_block, SpriteContract, render_gfx_entry
from tools.lib.adiscord_ui_surfaces import (
    PALETTES, apply_or_check, button_strip, dds_bytes, framed_panel,
    load_surface_source, metal_surface, partial_rails, recessed_well, replace_counted,
)
from tools.lib.paths import repository_root


ROOT = repository_root()
BASE_GAME = Path("Z:/SteamLibrary/steamapps/common/Hearts of Iron IV")
VANILLA_GUI = BASE_GAME / "interface/nationalfocusview.gui"
SOURCE = ROOT / "gfx/interface/production/source/production_surface_source.png"
OUTPUT_DIR = ROOT / "gfx/interface/focusview"
GUI_OUTPUT = ROOT / "interface/nationalfocusview.gui"
GFX_OUTPUT = ROOT / "interface/ADISCORD_focus_ui.gfx"
HEADER = "# Generated by tools/builders/build_adiscord_focus_ui_assets.py; do not edit.\n"


def render_gui() -> str:
    text = VANILLA_GUI.read_text(encoding="utf-8-sig")
    for old, new, count in (
        ("GFX_tiled_plain_bg2", "window", 1),
        ("GFX_tiled_bg", "panel", 1),
        ("GFX_tiled_focus_bg", "tree", 1),
        ("GFX_tiled_window_thin_border2", "window", 4),
        ("GFX_tiled_paper_bg2", "panel", 3),
        ("GFX_tiled_window_transparent", "panel", 2),
        ("GFX_tech_info_top_win", "detail_header", 2),
        ("GFX_generic_bg_307x113", "requirements", 2),
        ("GFX_unit_list_header", "reward_header", 2),
        ("GFX_button_123x34", "button", 3),
    ):
        text = replace_counted(text, old, f"GFX_ADISCORD_focus_{new}", count)

    # These children are looked up by the native focus handler. Keep them as
    # direct children; the text widgets own their independent scroll viewports.
    for name in ("national_focus_detail_view", "coninuous_focus_detail_view"):
        text = replace_gui_block(text, "containerWindowType", name, (
            (r"position = \{ x=500 y=100 \}", "position = { x=500 y=80 }"),
            (r"size = \{ width = 550 height = 550 \}", "size = { width = 660 height = 640 }"),
            (r"maxWidth = 450", "maxWidth = 560"),
        ))
    text = replace_gui_block(text, "containerWindowType", "statsarea", (
        (r"size = \{ width = 97%% height = 98%% \}", "size = { width = 620 height = 400 }"),
        (r'\s*horizontalScrollbar = "bottom_horizontal_slider"', ""),
        (r'\s*verticalScrollbar = "right_vertical_slider"', ""),
    ), expected=2)
    text = replace_gui_block(text, "instantTextboxType", "desc", (
        (r"position = \{ x = 34 y = 250 \}", "position = { x = 36 y = 236 }"),
        (r"maxWidth = 485", "maxWidth = 580"),
        (r"maxHeight = 70", "maxHeight = 174\n\t\t\tscrollbarType = standardtext_slider"),
        (r"format = center", "format = left"),
    ), expected=2)
    text = replace_gui_block(text, "instantTextboxType", "prerequisites", (
        (r"maxWidth = 287", "maxWidth = 405"),
    ), expected=2)
    text = replace_gui_block(text, "iconType", "reward_bg", (
        (r"position = \{ x = 84 y = 363 \}", "position = { x = 20 y = 422 }"),
    ), expected=2)
    text = replace_gui_block(text, "instantTextboxType", "reward_label", (
        (r"position = \{ x = 34 y = 370 \}", "position = { x = 36 y = 428 }"),
        (r"maxWidth = 485", "maxWidth = 580"),
        (r"maxHeight = 70", "maxHeight = 22"),
    ), expected=2)
    text = replace_gui_block(text, "instantTextboxType", "reward", (
        (r"position = \{ x = 50 y = 397 \}", "position = { x = 36 y = 462 }"),
        (r"maxWidth = 455", "maxWidth = 580"),
        (r"maxHeight = 138", "maxHeight = 144"),
    ), expected=2)
    text = replace_gui_block(text, "buttonType", "start", (
        (r"position = \{ x=390 y=53 \}", "position = { x=510 y=53 }"),
    ), expected=2)
    text = replace_gui_block(text, "buttonType", "stop", (
        (r"position = \{ x=390 y=53 \}", "position = { x=510 y=53 }"),
    ))
    return HEADER + "\n".join(line.rstrip() for line in text.splitlines()) + "\n"


def surfaces() -> dict[str, tuple[Image.Image, int | None, int]]:
    source = load_surface_source(SOURCE)
    palette = PALETTES["technology"]
    tree = Image.new("RGBA", (256, 256), palette.deep)
    draw = ImageDraw.Draw(tree)
    # A periodic, low-contrast grid stays seamless at every tree zoom level.
    for coord in range(0, 256, 64):
        draw.line((coord, 0, coord, 255), fill=(16, 23, 25, 255))
        draw.line((0, coord, 255, coord), fill=(16, 23, 25, 255))
        for other in range(0, 256, 64):
            draw.point((coord, other), fill=(28, 39, 41, 255))
    panel = Image.new("RGBA", (96, 96), palette.panel)
    recessed_well(panel, (0, 0, 95, 95), palette)
    requirements = Image.new("RGBA", (435, 113), palette.panel)
    recessed_well(requirements, (0, 0, 434, 112), palette)
    header = metal_surface(source, (658, 46), palette, 0.74)
    partial_rails(header, (8, 4, 649, 44), palette)
    reward = metal_surface(source, (620, 32), palette, 0.60)
    partial_rails(reward, (0, 0, 619, 31), palette)
    return {
        "window": (framed_panel(source, (192, 192), palette, 0.66), 24, 1),
        "panel": (panel, 4, 1),
        "tree": (tree, 0, 1),
        "detail_header": (header, None, 1),
        "requirements": (requirements, None, 1),
        "reward_header": (reward, None, 1),
        "button": (button_strip(source, (123, 34), palette), None, 3),
    }


def expected_outputs() -> dict[Path, bytes]:
    outputs = {GUI_OUTPUT: render_gui().encode("utf-8")}
    entries = []
    for role, (image, border, frames) in surfaces().items():
        filename = f"ADISCORD_focus_{role}.dds"
        path = OUTPUT_DIR / filename
        contract = SpriteContract(
            source_name="", target_name=f"GFX_ADISCORD_focus_{role}", filename=filename,
            kind="spriteType" if border is None else "corneredTileSpriteType",
            total_size=image.size, frames=frames,
            border_size=None if border is None else (border, border),
            tiling_center=border is not None,
            # Container backgrounds retain hit testing for native wheel zoom
            # and drag scrolling. Only decorative icons pass input through.
            always_transparent=role in {"detail_header", "requirements", "reward_header"},
            effect_file=None if role == "button" else "gfx/FX/buttonstate_onlydisable.lua",
        )
        outputs[path] = dds_bytes(image)
        entries.append(render_gfx_entry(contract, path.relative_to(ROOT).as_posix()))
    outputs[GFX_OUTPUT] = (HEADER + "spriteTypes = {\n" + "".join(entries) + "}\n").encode("utf-8")
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true")
    actions.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    return apply_or_check(expected_outputs(), args.apply, "National-focus UI")


if __name__ == "__main__":
    raise SystemExit(main())
