"""Format event artwork for COUNTRY (507x184) and NEWS (396x153).

Owns standardized artwork, its GFX extension, and the review contact sheet.
Story assignments remain hand-authored in events/*.txt. Original artwork is
preserved; only aspect-preserving crops and resampling are applied here.
"""

from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageOps

from tools.lib.adiscord_ui_surfaces import apply_or_check
from tools.lib.paths import repository_root


ROOT = repository_root()
ART_ROOT = ROOT / "gfx/event_pictures"
GFX = ROOT / "interface/ADISCORD_event_art.gfx"
PREVIEW = ROOT / "gfx/interface/events/preview/ADISCORD_event_art_contact_sheet.png"
SIZES = {"country": (507, 184), "news": (396, 153)}
# The old explosion source includes a beveled perimeter; keep only the artwork.
SOURCE_CROPS = {"vorkerland_explosion": (7, 7, 500, 177)}

# scene: (source relative to gfx/event_pictures, required window formats).
# New formats are explicit: a COUNTRY sprite must never be reused in NEWS.
ART = {
    "parliament_chamber": ("source/parliament_chamber.png", ("country", "news")),
    "negotiation_table": ("source/negotiation_table.png", ("country", "news")),
    "military_headquarters": ("event_adiscord_ui_test.png", ("country",)),
    "nectar_of_the_gods": ("source/nectar_of_the_gods.png", ("country",)),
    "city_in_civil_war": ("source/news/city_in_civil_war.png", ("news",)),
    "vorkerland_explosion": ("event_vorkerland_explosion.png", ("country", "news")),
    "vorkerland_northern_settlement": ("event_vorkerland_civilwar_is_over.png", ("news",)),
    "army_formation": ("source/news/army_formation.dds", ("news",)),
    "treaty_signing": ("source/news/treaty_signing.dds", ("news",)),
    "peace_negotiations": ("source/news/peace_negotiations.dds", ("news",)),
    "military_planning": ("source/news/military_planning.dds", ("country", "news")),
    "urban_resistance": ("source/news/urban_resistance.dds", ("news",)),
    "troops_marching": ("source/news/troops_marching.dds", ("news",)),
    "armed_uprising": ("source/news/armed_uprising.dds", ("news",)),
}


def sprite_name(scene: str, kind: str) -> str:
    prefix = "GFX_news_event" if kind == "news" else "GFX_event"
    return f"{prefix}_adiscord_{scene}"


def texture_path(scene: str, kind: str) -> Path:
    return ART_ROOT / "standard" / kind / f"{scene}.png"


def formatted_art(scene: str, kind: str) -> Image.Image:
    source, formats = ART[scene]
    if kind not in formats:
        raise ValueError(f"unsupported event artwork format: {scene}/{kind}")
    with Image.open(ART_ROOT / source) as image:
        artwork = image.convert("RGB")
        if scene in SOURCE_CROPS:
            artwork = artwork.crop(SOURCE_CROPS[scene])
        # No stretching, added frames, tint, blur bars, or artificial sharpening.
        return ImageOps.fit(artwork, SIZES[kind],
                            method=Image.Resampling.LANCZOS)


def _png(image: Image.Image) -> bytes:
    stream = BytesIO()
    image.save(stream, format="PNG", compress_level=9)
    return stream.getvalue()


def expected_outputs() -> dict[Path, bytes]:
    outputs = {}
    entries = []
    images = []
    for scene, (_, formats) in ART.items():
        for kind in formats:
            path = texture_path(scene, kind)
            artwork = formatted_art(scene, kind)
            outputs[path] = _png(artwork)
            images.append((f"{kind.upper()} / {scene}", artwork))
            entries.append(
                '\tspriteType = {\n'
                f'\t\tname = "{sprite_name(scene, kind)}"\n'
                f'\t\ttexturefile = "{path.relative_to(ROOT).as_posix()}"\n'
                '\t}\n'
            )
    outputs[GFX] = (
        '# Generated by tools/builders/build_adiscord_event_pictures.py.\n'
        'spriteTypes = {\n' + ''.join(entries) + '}\n'
    ).encode("utf-8")
    # Native pixel-size contact sheet; labels are preview-only.
    sheet = Image.new("RGB", (1094, ((len(images) + 1) // 2) * 222 + 20), (18, 23, 24))
    draw = ImageDraw.Draw(sheet)
    for index, (label, artwork) in enumerate(images):
        x, y = 20 + index % 2 * 537, 20 + index // 2 * 222
        draw.text((x, y), label, fill=(219, 226, 223))
        sheet.paste(artwork, (x, y + 20))
    outputs[PREVIEW] = _png(sheet)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true")
    actions.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    return apply_or_check(expected_outputs(), args.apply, "Event artwork")


if __name__ == "__main__":
    raise SystemExit(main())
