"""Build the fixed-size campaign briefing skin; country artwork is source art."""

from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw

from tools.lib.adiscord_ui_surfaces import apply_or_check
from tools.lib.paths import repository_root


ROOT = repository_root()
OUTPUT = ROOT / 'gfx/interface/startup'
SIZES = {'background': (1000, 620), 'tab': (221, 36), 'page': (359, 36),
         'launcher': (98, 26), 'close': (36, 36)}


def frame(size: tuple[int, int], button: bool = False) -> Image.Image:
    width, height = size
    image = Image.new('RGBA', size, (19, 23, 29, 255))
    draw = ImageDraw.Draw(image)
    for y in range(height):
        grain = ((y * 37 + 11) % 7) - 3
        shade = (32 if button else 23) + grain
        draw.line((0, y, width - 1, y), fill=(shade, shade + 4, shade + 9, 255))
    draw.rectangle((0, 0, width - 1, height - 1), outline=(5, 7, 9), width=2)
    draw.rectangle((2, 2, width - 3, height - 3), outline=(92, 101, 111))
    draw.line((4, 4, width - 5, 4), fill=(123, 131, 139))
    draw.line((4, height - 5, width - 5, height - 5), fill=(8, 10, 13))
    if button:
        draw.line((6, 8, 6, height - 9), fill=(177, 151, 103), width=2)
    else:
        # The central recess keeps text contrast independent of frame texture.
        draw.rectangle((18, 54, 981, 555), fill=(13, 17, 22), outline=(57, 66, 76))
        draw.line((24, 55, 975, 55), fill=(5, 8, 11))
        draw.line((34, 49, 190, 49), fill=(177, 151, 103), width=2)
        for x, y in ((11, 11), (988, 11), (11, 608), (988, 608)):
            draw.ellipse((x - 2, y - 2, x + 2, y + 2), fill=(8, 10, 13), outline=(81, 90, 100))
    return image


def expected_outputs() -> dict[Path, bytes]:
    outputs = {}
    definitions = ['# Generated by tools/builders/build_adiscord_startup_ui_assets.py.', 'spriteTypes = {']
    for role, size in SIZES.items():
        stream = BytesIO()
        frame(size, role != 'background').save(stream, 'PNG')
        outputs[OUTPUT / f'{role}.png'] = stream.getvalue()
        kind = 'spriteType' if role == 'background' else 'textSpriteType'
        definitions.extend([
            f'\t{kind} = {{', f'\t\tname = "GFX_ADISCORD_startup_{role}"',
            f'\t\ttexturefile = "gfx/interface/startup/{role}.png"', '\t\tnoOfFrames = 1',
        ])
        if role != 'background':
            definitions.append('\t\teffectFile = "gfx/FX/buttonstate.lua"')
        definitions.append('\t}')
    for tag in ('stp', 'val'):
        definitions.extend([
            '\tspriteType = {', f'\t\tname = "GFX_ADISCORD_startup_{tag}"',
            f'\t\ttexturefile = "gfx/interface/startup/{tag}.png"', '\t}',
        ])
    definitions.append('}')
    outputs[ROOT / 'interface/ADISCORD_startup_menu.gfx'] = ('\n'.join(definitions) + '\n').encode('utf-8')
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--check', action='store_true')
    modes.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    return apply_or_check(expected_outputs(), args.apply, 'Campaign briefing UI')


if __name__ == '__main__':
    raise SystemExit(main())
