#!/usr/bin/env python3
"""Split the old catch-all state 23 into coarse, climate-coherent state shells.

The detailed northern/right and provisional left-continent shells are handled
by ``build_adiscord_outer_states.py``.  This pass only handles what remains in
state 23.  Provinces are first separated by latitude band and then by physical
connectivity, so no generated state joins islands or continents that are not
actual neighbours.

State 23 is retained as one real connected shell; the other shells use IDs
551 and above.  Re-running the tool folds its own marked files back into the
source pool before rebuilding them.
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from tools.builders.build_adiscord_map_buildings import synchronize_buildings
from tools.builders.build_adiscord_outer_states import (
    ProvinceData,
    build_province_data,
    cluster_statistics,
    format_provinces,
    parse_state,
)
from tools.builders.build_adiscord_strategic_regions import (
    connected_components,
    load_province_adjacency,
    load_province_definitions,
)
from tools.lib.paths import repository_root


ROOT = repository_root()
STATE_DIR = ROOT / "history" / "states"
LOCALISATION = ROOT / "localisation" / "russian" / "ADISCORD_remainder_states_l_russian.yml"
BASE_STATE_LOCALISATION = ROOT / "localisation" / "russian" / "state_names_l_russian.yml"
GENERATED_MARKER = "# Generated by tools/build_adiscord_remainder_states.py"
CLIMATE_MARKER = "# adiscord_climate_region = "
STRATEGIC_NAME_MARKER = "# adiscord_strategic_name = "
FIRST_NEW_STATE_ID = 551
EXPECTED_PROVINCE_COUNT = 1004

LATITUDE_EDGES = (350.0, 650.0, 1050.0, 1450.0, 1750.0)
LONGITUDE_EDGES = (1408.0, 2816.0, 4224.0)

# Each broad cell has one stable toponym.  Subregions of the same place use
# geographical qualifiers rather than technical numerals.
WORLD_TOPONYMS = {
    (0, 0): "Ардрен", (0, 1): "Бельнор", (0, 2): "Келмар", (0, 3): "Дорвик",
    (1, 0): "Эльвен", (1, 1): "Фарден", (1, 2): "Гальнор", (1, 3): "Хеллер",
    (2, 0): "Ирвен", (2, 1): "Кальден", (2, 2): "Лавер", (2, 3): "Морвен",
    (3, 0): "Неллар", (3, 1): "Ольден", (3, 2): "Перрин", (3, 3): "Равен",
    (4, 0): "Селдар", (4, 1): "Терен", (4, 2): "Ульвен", (4, 3): "Фалор",
    (5, 0): "Хаврен", (5, 1): "Цельмар", (5, 2): "Шарден", (5, 3): "Эвенор",
}

HORIZONTAL_QUALIFIERS = {
    2: ("Западный", "Восточный"),
    3: ("Западный", "Центральный", "Восточный"),
}
VERTICAL_QUALIFIERS = {
    2: ("Северный", "Южный"),
    3: ("Северный", "Центральный", "Южный"),
}
GRID_QUALIFIERS = {
    4: ("Северо-западный", "Северо-восточный", "Юго-западный", "Юго-восточный"),
    5: ("Северный", "Западный", "Центральный", "Восточный", "Южный"),
    6: ("Северо-западный", "Северный", "Северо-восточный", "Юго-западный", "Южный", "Юго-восточный"),
    7: ("Северо-западный", "Северный", "Северо-восточный", "Западный", "Восточный", "Юго-западный", "Юго-восточный"),
    8: ("Северо-западный", "Северный", "Северо-восточный", "Западный", "Восточный", "Юго-западный", "Южный", "Юго-восточный"),
    9: ("Северо-западный", "Северный", "Северо-восточный", "Западный", "Центральный", "Восточный", "Юго-западный", "Южный", "Юго-восточный"),
}
EXTENDED_QUALIFIERS = (
    "Крайний северо-западный", "Дальний северо-западный", "Северо-западный",
    "Северный", "Северо-восточный", "Дальний северо-восточный",
    "Крайний западный", "Дальний западный", "Западный",
    "Восточный", "Дальний восточный", "Крайний восточный",
    "Крайний юго-западный", "Дальний юго-западный", "Юго-западный",
    "Южный", "Юго-восточный", "Дальний юго-восточный",
)


@dataclass
class PlannedState:
    state_id: int
    provinces: set[int]
    climate_region: str
    name: str
    strategic_name: str


def state_23_path() -> Path:
    matches = sorted(STATE_DIR.glob("23-*.txt"))
    if len(matches) != 1:
        raise RuntimeError(f"state 23: expected one file, found {len(matches)}")
    return matches[0]


def load_source_pool() -> tuple[set[int], str, list[Path]]:
    base_path = state_23_path()
    _state_id, base_provinces, base_source = parse_state(base_path)
    pool = set(base_provinces)
    generated_paths: list[Path] = []
    for path in sorted(STATE_DIR.glob("*.txt")):
        if path == base_path:
            continue
        source = path.read_text(encoding="utf-8-sig", errors="strict")
        if not source.startswith(GENERATED_MARKER):
            continue
        state_id, provinces, _source = parse_state(path)
        if state_id < FIRST_NEW_STATE_ID:
            raise RuntimeError(f"{path.name}: remainder marker on reserved state id {state_id}")
        overlap = pool & provinces
        if overlap:
            raise RuntimeError(f"remainder states overlap at provinces {sorted(overlap)[:20]}")
        pool.update(provinces)
        generated_paths.append(path)
    if len(pool) != EXPECTED_PROVINCE_COUNT:
        raise RuntimeError(
            f"remainder source pool changed: expected {EXPECTED_PROVINCE_COUNT} provinces, found {len(pool)}"
        )
    return pool, base_source, generated_paths


def band_for_y(y: float) -> int:
    return next((index for index, edge in enumerate(LATITUDE_EDGES) if y < edge), len(LATITUDE_EDGES))


def sector_for_x(x: float) -> int:
    return next((index for index, edge in enumerate(LONGITUDE_EDGES) if x < edge), len(LONGITUDE_EDGES))


def climate_region(band: int, stats: dict[str, object]) -> str:
    highland = float(stats["highland_share"]) >= 0.42 or float(stats["height"]) >= 13.5
    maritime = float(stats["coastal_share"]) >= 0.35
    wet = float(stats["wet_share"]) >= 0.52
    if band == 0:
        return "world_polar"
    if band == 1:
        if highland:
            return "world_cold_highlands"
        return "world_subarctic_maritime" if maritime else "world_subarctic_continental"
    if band == 2:
        if highland:
            return "world_cool_highlands"
        if maritime:
            return "world_cool_maritime"
        return "world_boreal_wet" if wet else "world_cool_continental"
    if band == 3:
        if highland:
            return "world_temperate_highland"
        return "world_temperate_wet" if wet else "world_temperate_continental"
    if band == 4:
        if highland:
            return "world_hot_highland"
        return "world_warm_maritime" if maritime else "world_warm_interior"
    return "world_tropical_maritime" if maritime or wet else "world_hot_arid"


def spatial_qualifiers(
    count: int, rows: list[tuple[set[int], dict[str, object]]]
) -> list[str]:
    if count == 1:
        return [""]
    x_span = max(float(stats["x"]) for _provinces, stats in rows) - min(
        float(stats["x"]) for _provinces, stats in rows
    )
    y_span = max(float(stats["y"]) for _provinces, stats in rows) - min(
        float(stats["y"]) for _provinces, stats in rows
    )
    if count <= 3:
        source = HORIZONTAL_QUALIFIERS if x_span >= y_span else VERTICAL_QUALIFIERS
        return list(source[count])
    if count <= 9:
        return list(GRID_QUALIFIERS[count])
    if count > len(EXTENDED_QUALIFIERS):
        raise RuntimeError(f"cannot name {count} subregions in one macro-toponym")
    if count == len(EXTENDED_QUALIFIERS):
        return list(EXTENDED_QUALIFIERS)
    indices = [round(index * (len(EXTENDED_QUALIFIERS) - 1) / (count - 1)) for index in range(count)]
    if len(set(indices)) != count:
        raise RuntimeError(f"could not select {count} unique geographic qualifiers")
    return [EXTENDED_QUALIFIERS[index] for index in indices]


def plan_states(
    pool: set[int], adjacency: dict[int, set[int]], data: dict[int, ProvinceData]
) -> list[PlannedState]:
    rows: list[tuple[int, int, set[int], dict[str, object]]] = []
    for band in range(len(LATITUDE_EDGES) + 1):
        band_provinces = {province_id for province_id in pool if band_for_y(data[province_id].y) == band}
        for component in connected_components(band_provinces, adjacency):
            stats = cluster_statistics(component, data)
            rows.append((band, sector_for_x(float(stats["x"])), component, stats))

    grouped: dict[tuple[int, int], list[tuple[set[int], dict[str, object]]]] = defaultdict(list)
    for band, sector, provinces, stats in rows:
        grouped[(band, sector)].append((provinces, stats))

    names_by_min_province: dict[int, str] = {}
    for cell, cell_rows in grouped.items():
        ordered = sorted(
            cell_rows,
            key=lambda row: (float(row[1]["y"]), float(row[1]["x"]), min(row[0])),
        )
        qualifiers = spatial_qualifiers(len(ordered), ordered)
        root = WORLD_TOPONYMS[cell]
        for (provinces, _stats), qualifier in zip(ordered, qualifiers):
            names_by_min_province[min(provinces)] = f"{qualifier} {root}".strip()

    ordered_rows = sorted(rows, key=lambda row: (row[0], float(row[3]["x"]), float(row[3]["y"]), min(row[2])))
    # Preserve legacy state ID 23 on the largest connected shell; every other
    # component receives a new contiguous ID.
    base_index = max(range(len(ordered_rows)), key=lambda index: (len(ordered_rows[index][2]), -min(ordered_rows[index][2])))
    state_ids: list[int | None] = [None] * len(ordered_rows)
    state_ids[base_index] = 23
    next_state_id = FIRST_NEW_STATE_ID
    for index in range(len(ordered_rows)):
        if state_ids[index] is None:
            state_ids[index] = next_state_id
            next_state_id += 1

    planned: list[PlannedState] = []
    for state_id, (band, _sector, provinces, stats) in zip(state_ids, ordered_rows):
        assert state_id is not None
        name = names_by_min_province[min(provinces)]
        planned.append(
            PlannedState(
                state_id=state_id,
                provinces=provinces,
                climate_region=climate_region(band, stats),
                name=name,
                strategic_name=name,
            )
        )
    return sorted(planned, key=lambda state: state.state_id)


def render_state(state: PlannedState, data: dict[int, ProvinceData]) -> str:
    stats = cluster_statistics(state.provinces, data)
    band = band_for_y(float(stats["y"]))
    category = "wasteland" if band == 0 or float(stats["highland_share"]) >= 0.70 else "rural"
    return (
        f"{GENERATED_MARKER}\n"
        f"{CLIMATE_MARKER}{state.climate_region}\n"
        f"{STRATEGIC_NAME_MARKER}{state.strategic_name}\n"
        "state = {\n"
        f"\tid = {state.state_id}\n"
        f'\tname = "STATE_{state.state_id}"\n'
        "\tmanpower = 1\n"
        f"\tstate_category = {category}\n"
        "\tprovinces = {\n"
        f"{format_provinces(state.provinces)}\n"
        "\t}\n"
        "\tbuildings_max_level_factor = 1.000\n"
        "\tlocal_supplies = 0.0\n"
        "}\n"
    )


def update_state_23_localisation(name: str) -> None:
    source = BASE_STATE_LOCALISATION.read_text(encoding="utf-8-sig", errors="strict")
    updated, count = re.subn(
        r'(?m)^(\s*STATE_23\s*:\s*)"[^"]*"',
        lambda match: f'{match.group(1)}"{name}"',
        source,
    )
    if count != 1:
        raise RuntimeError(f"STATE_23 localisation: expected one row, found {count}")
    BASE_STATE_LOCALISATION.write_text("\ufeff" + updated, encoding="utf-8", newline="\n")


def validate_plan(planned: list[PlannedState], pool: set[int]) -> None:
    assigned: set[int] = set()
    for state in planned:
        overlap = assigned & state.provinces
        if overlap:
            raise RuntimeError(f"planned remainder states overlap at {sorted(overlap)[:20]}")
        assigned.update(state.provinces)
    if assigned != pool:
        raise RuntimeError(
            f"planned remainder coverage mismatch: missing {len(pool-assigned)}, unexpected {len(assigned-pool)}"
        )
    expected_ids = {23, *range(FIRST_NEW_STATE_ID, FIRST_NEW_STATE_ID + len(planned) - 1)}
    actual_ids = {state.state_id for state in planned}
    if actual_ids != expected_ids:
        raise RuntimeError(f"planned remainder IDs differ: expected {sorted(expected_ids)}, found {sorted(actual_ids)}")
    names = Counter(state.name for state in planned)
    duplicates = sorted(name for name, count in names.items() if count > 1)
    if duplicates:
        raise RuntimeError(f"duplicate remainder names: {duplicates}")
    technical = [state.name for state in planned if re.search(r"\s[IVXLCDM]+$", state.name)]
    if technical:
        raise RuntimeError(f"technical numeral names remain: {technical}")


def apply_plan(planned: list[PlannedState], data: dict[int, ProvinceData], generated_paths: list[Path]) -> None:
    for path in generated_paths:
        path.unlink()
    for state in planned:
        path = state_23_path() if state.state_id == 23 else STATE_DIR / f"{state.state_id}-outer-remainder.txt"
        path.write_text(render_state(state, data), encoding="utf-8", newline="\n")

    generated = [state for state in planned if state.state_id != 23]
    localisation = ["\ufeffl_russian:"]
    localisation.extend(f' STATE_{state.state_id}: "{state.name}"' for state in generated)
    LOCALISATION.write_text("\n".join(localisation) + "\n", encoding="utf-8", newline="\n")
    state_23 = next(state for state in planned if state.state_id == 23)
    update_state_23_localisation(state_23.name)
    print(
        f"Applied {len(planned)} connected remainder shells: state 23 plus "
        f"{len(generated)} states {FIRST_NEW_STATE_ID}-{generated[-1].state_id}."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true", help="validate current generated outputs (default)")
    actions.add_argument("--apply", action="store_true", help="write generated state files and localisation")
    args = parser.parse_args()

    if not args.apply:
        from tools.validators.validate_adiscord_remainder_states import main as validate_main

        return validate_main()

    pool, _base_source, generated_paths = load_source_pool()
    province_types, color_to_province = load_province_definitions()
    data = build_province_data(province_types, color_to_province)
    if not pool <= set(data):
        raise RuntimeError(f"remainder pool contains non-land provinces {sorted(pool-set(data))[:20]}")
    adjacency = load_province_adjacency(
        province_types, color_to_province, include_special_adjacencies=False
    )
    planned = plan_states(pool, adjacency, data)
    validate_plan(planned, pool)
    climate_counts = Counter(state.climate_region for state in planned)
    print(f"Planned {len(planned)} connected climate shells from {len(pool)} provinces.")
    print(f"Climate groups: {dict(sorted(climate_counts.items()))}")
    apply_plan(planned, data, generated_paths)
    mismatches = synchronize_buildings(ROOT, apply=True)
    print(f"Synchronized {len(mismatches)} map-building state assignments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
