#!/usr/bin/env python3
"""Build A-Discord land and sea strategic regions with seasonal weather."""

from __future__ import annotations

import argparse
import csv
import math
import re
from collections import Counter, deque
from dataclasses import dataclass
from pathlib import Path

from PIL import Image
from tools.lib.paths import repository_root


ROOT = repository_root()
STATE_DIR = ROOT / "history" / "states"
REGION_DIR = ROOT / "map" / "strategicregions"
# Load after the vanilla strategic-region file so duplicate numeric keys are
# overridden by A-Discord names instead of showing names such as "Прибалтика".
LOCALISATION = ROOT / "localisation" / "replace" / "strategic_region_names_l_russian.yml"
WEATHER_POSITIONS = ROOT / "map" / "weatherpositions.txt"
GENERATED_MARKER = "# Generated by tools/build_adiscord_strategic_regions.py"
OUTER_STATE_MARKER = "# Generated by tools/build_adiscord_outer_states.py"
REMAINDER_STATE_MARKER = "# Generated by tools/build_adiscord_remainder_states.py"


@dataclass(frozen=True)
class Region:
    region_id: int
    slug: str
    russian_name: str
    climate: str
    states: tuple[int, ...]


@dataclass(frozen=True)
class SeaRegion:
    region_id: int
    slug: str
    russian_name: str
    climate: str
    latitude_band: int
    longitude_band: int
    naval_terrain: str = "water_deep_ocean"


SEA_REGIONS = (
    SeaRegion(1, "northwestern-polar-ocean", "Северо-западный полярный океан", "polar_ocean", 0, 0),
    SeaRegion(26, "northern-polar-ocean", "Северный полярный океан", "polar_ocean", 0, 1),
    SeaRegion(27, "northeastern-polar-ocean", "Северо-восточный полярный океан", "polar_ocean", 0, 2),
    SeaRegion(28, "northwestern-sea", "Северо-западное море", "subpolar_ocean", 1, 0),
    SeaRegion(29, "northern-inner-sea", "Северное внутреннее море", "subpolar_ocean", 1, 1),
    SeaRegion(30, "northeastern-sea", "Северо-восточное море", "subpolar_ocean", 1, 2),
    SeaRegion(31, "western-ocean", "Западный океан", "temperate_ocean", 2, 0),
    SeaRegion(32, "central-seas", "Центральные моря", "temperate_ocean", 2, 1),
    SeaRegion(33, "eastern-ocean", "Восточный океан", "temperate_ocean", 2, 2),
    SeaRegion(34, "southwestern-seas", "Юго-западные моря", "warm_ocean", 3, 0),
    SeaRegion(35, "southern-inner-sea", "Южное внутреннее море", "warm_ocean", 3, 1),
    SeaRegion(36, "southeastern-seas", "Юго-восточные моря", "warm_ocean", 3, 2),
    SeaRegion(37, "southwestern-ocean", "Юго-западный океан", "tropical_ocean", 4, 0),
    SeaRegion(38, "southern-ocean", "Южный океан", "tropical_ocean", 4, 1),
    SeaRegion(39, "southeastern-ocean", "Юго-восточный океан", "tropical_ocean", 4, 2),
)

# The enclosed Antolla basin is a separate, shallow inland sea.  It must not
# be swallowed by the eastern-ocean partition or treated like a landlocked
# lake: all six provinces form one navigable component around the inner
# frontier countries.
DEDICATED_SEA_REGIONS = (
    SeaRegion(228, "antolla-sea", "Антолльское море", "temperate_ocean", 2, 2, "water_shallow_sea"),
)
DEDICATED_SEA_PROVINCES = {
    228: frozenset({16258, 16262, 16264, 16265, 16266, 16268}),
}
ALL_SEA_REGIONS = (*SEA_REGIONS, *DEDICATED_SEA_REGIONS)

SEA_REGION_GRID = (
    (1, 26, 27),
    (28, 29, 30),
    (31, 32, 33),
    (34, 35, 36),
    (37, 38, 39),
)


BASE_REGIONS = (
    # Region 2 now only catches unassigned inland-water/non-state provinces.
    # The former catch-all state 23 is rebuilt as one connected climate shell.
    Region(2, "inland-waters", "Внутренние воды", "warm_maritime", ()),
    Region(3, "polar-islands", "Полярные острова", "polar", (47,)),
    Region(4, "western-archipelago", "Западный архипелаг", "cool_maritime", (77,)),
    Region(5, "far-west", "Дальний запад", "cool_maritime", (78,)),
    Region(6, "northern-march", "Северная марка", "cool_maritime", (89, 127, 128, 129, 130, 131, 132, 164)),
    Region(7, "ivan-plains", "Иванские равнины", "cool_continental", (25, 92, 95, 97, 98, 126, 135, 139, 140, 141, 142, 143)),
    Region(8, "western-lowlands", "Западные равнины", "temperate_continental", (26, 71, 90, 91, 93, 94, 96, 99, 100, 101, 103, 194, 202, 328)),
    Region(9, "vych-country", "Вычский край", "warm_semiarid", (75, 102, 106, 107, 108, 109, 110, 111, 121, 122, 123, 124, 201, 307, 324, 325)),
    Region(10, "upper-watershed", "Верхний водораздел", "cool_highland", (72, 73, 133, 134, 136, 137, 138, 144, 145, 146, 147, 148, 149, 150, 151, 195, 196, 319, 321, 322)),
    Region(11, "zlatoriver", "Златоречье", "temperate_wet", (80, 82, 157, 158, 159, 161, 162, 163, 199, 315, 316, 317, 318)),
    Region(12, "vorkernsberg", "Воркенсберг", "temperate_continental", (27, 32, 33, 34, 35, 36, 37, 38, 39, 40, 79, 81, 104, 105, 306, 308, 309, 320, 323, 327)),
    Region(13, "southern-dry-arc", "Южная сухая дуга", "hot_arid", (52, 74, 76, 113, 114, 197, 198, 310, 311, 312, 313, 314, 326)),
    Region(14, "reing-heights", "Рейнгские высоты", "hot_highland", (112, 115, 116, 117)),
    Region(15, "northeastern-forests", "Северо-восточные леса", "cool_maritime", (13, 14, 17, 18, 19, 20, 21, 22, 83, 84, 85, 86, 87, 118, 119, 120, 303)),
    Region(16, "eastern-riverlands", "Восточное междуречье", "temperate_wet", (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 28, 29, 30, 31, 41, 53)),
    Region(17, "antolla-heights", "Антолльские высоты", "cool_highland", (43, 44, 45, 46, 58, 59, 60, 61, 62, 63, 64, 65, 88, 179)),
    Region(18, "zoilong-frontier", "Зойлонгский рубеж", "temperate_highland", (24, 42, 48, 54, 55, 56, 57, 168)),
    Region(19, "grey-belt", "Серая полоса", "arid_highland", (49, 50, 51, 66, 125, 176, 180, 181, 191, 192, 193, 233, 329, 330)),
    Region(20, "irem-wastes", "Иримская пустошь", "arid", (177, 178, 182, 183, 184, 185, 186, 187, 188, 189, 190, 206, 207, 208, 220, 221)),
    Region(21, "western-reactor-zone", "Западная реакторная зона", "arid", (152, 153, 154, 155, 156, 160, 223, 224)),
    Region(22, "loren-corridor", "Лоренский коридор", "arid", (167, 169, 170, 171, 172, 173, 203, 204, 205, 211, 216, 217)),
    Region(23, "southern-reactor-zone", "Южная реакторная зона", "hot_arid", (165, 166, 209, 210, 212, 213, 214, 215, 218, 219, 222)),
    Region(24, "mardar-lowlands", "Мардарская низина", "hot_arid", (67, 68, 69, 70, 174, 175, 688, 689, 690, 691, 692)),
    Region(25, "southern-islands", "Южные острова", "tropical_maritime", (200, 225, 226, 227, 228, 229, 230, 231, 232)),
    Region(40, "kadir-coast", "Кадирское побережье", "hot_arid", tuple(range(234, 265))),
    Region(41, "mazar-oases", "Мазарские оазисы", "hot_arid", tuple(range(265, 287))),
    Region(42, "shahrabad-saltlands", "Шахрабадские солончаки", "hot_highland", (*range(287, 303), 304, 305)),
)


# Neutral state shells produced by build_adiscord_outer_states.py carry one of
# these climate keys in a file comment. Keeping the keys here lets the state
# pass remain idempotent while strategic regions and weather are rebuilt from
# the current state files rather than a copied province manifest.
OUTER_REGION_SPECS = {
    "left_polar": ("left-polar-coast", "Левое полярное побережье", "polar"),
    "left_subarctic_maritime": ("left-subarctic-coast", "Левые субарктические берега", "subarctic_maritime"),
    "left_subarctic_continental": ("left-subarctic-interior", "Левый субарктический материк", "subarctic_continental"),
    "left_cold_highlands": ("left-cold-highlands", "Левые холодные нагорья", "cold_highland"),
    "left_cool_maritime": ("left-cool-coast", "Левое прохладное побережье", "cool_maritime"),
    "left_cool_continental": ("left-cool-interior", "Левый прохладный материк", "cool_continental"),
    "left_cool_highlands": ("left-cool-highlands", "Левые прохладные нагорья", "cool_highland"),
    "left_temperate_wet": ("left-temperate-riverlands", "Левые умеренные речные земли", "temperate_wet"),
    "left_temperate_continental": ("left-temperate-interior", "Левый умеренный материк", "temperate_continental"),
    "left_temperate_highlands": ("left-temperate-highlands", "Левое умеренное нагорье", "temperate_highland"),
    "left_warm_interior": ("left-warm-interior", "Левые тёплые внутренние земли", "warm_semiarid"),
    "left_southern_coast": ("left-southern-coast", "Левое южное побережье", "warm_maritime"),
    "right_polar": ("right-polar-lands", "Правый полярный край", "polar"),
    "right_subarctic_maritime": ("right-subarctic-coast", "Правые субарктические берега", "subarctic_maritime"),
    "right_subarctic_continental": ("right-subarctic-interior", "Правый субарктический материк", "subarctic_continental"),
    "right_cold_highlands": ("right-cold-highlands", "Правые холодные нагорья", "cold_highland"),
    "right_cool_maritime": ("right-cool-coast", "Правое прохладное побережье", "cool_maritime"),
    "right_boreal_wet": ("right-boreal-forests", "Правые бореальные леса", "boreal_wet"),
    "right_cool_continental": ("right-cool-interior", "Правый прохладный материк", "cool_continental"),
    "right_cool_highlands": ("right-cool-highlands", "Правые прохладные нагорья", "cool_highland"),
    "right_temperate_wet": ("right-temperate-riverlands", "Правые умеренные речные земли", "temperate_wet"),
    "right_temperate_continental": ("right-temperate-interior", "Правый умеренный материк", "temperate_continental"),
    "right_temperate_highlands": ("right-temperate-highlands", "Правое умеренное нагорье", "temperate_highland"),
    "world_polar": ("world-polar", "Полярные земли", "polar"),
    "world_subarctic_maritime": ("world-subarctic-coast", "Субарктическое побережье", "subarctic_maritime"),
    "world_subarctic_continental": ("world-subarctic-interior", "Субарктическая тайга", "subarctic_continental"),
    "world_cold_highlands": ("world-cold-highlands", "Холодное нагорье", "cold_highland"),
    "world_cool_maritime": ("world-cool-coast", "Прохладное побережье", "cool_maritime"),
    "world_boreal_wet": ("world-boreal-forests", "Северные леса", "boreal_wet"),
    "world_cool_continental": ("world-cool-interior", "Прохладная тайга", "cool_continental"),
    "world_cool_highlands": ("world-cool-highlands", "Прохладное нагорье", "cool_highland"),
    "world_temperate_wet": ("world-temperate-riverlands", "Умеренное междуречье", "temperate_wet"),
    "world_temperate_continental": ("world-temperate-interior", "Умеренные равнины", "temperate_continental"),
    "world_temperate_highland": ("world-temperate-highland", "Умеренное нагорье", "temperate_highland"),
    "world_warm_maritime": ("world-warm-coast", "Тёплое побережье", "warm_maritime"),
    "world_warm_interior": ("world-warm-interior", "Тёплые степи", "warm_semiarid"),
    "world_hot_highland": ("world-hot-highland", "Жаркое нагорье", "hot_highland"),
    "world_tropical_maritime": ("world-tropical-coast", "Тропическое побережье", "tropical_maritime"),
    "world_hot_arid": ("world-hot-arid", "Жаркие сухие земли", "hot_arid"),
}

# Player-facing names stay deliberately geographic. The left/right prefixes in
# climate keys and file slugs are implementation details and must never leak
# into localisation.
OUTER_REGION_NAMES = {
    "left_polar": "Северо-западная тундра",
    "left_subarctic_maritime": "Северо-западное побережье",
    "left_subarctic_continental": "Северо-западная тайга",
    "left_cold_highlands": "Северо-западное нагорье",
    "left_cool_maritime": "Западное побережье",
    "left_cool_continental": "Западные леса",
    "left_cool_highlands": "Западное нагорье",
    "left_temperate_wet": "Западное междуречье",
    "left_temperate_continental": "Западные равнины",
    "left_temperate_highlands": "Западное умеренное нагорье",
    "left_warm_interior": "Юго-западные степи",
    "left_southern_coast": "Юго-западное побережье",
    "right_polar": "Северо-восточная тундра",
    "right_subarctic_maritime": "Северо-восточное побережье",
    "right_subarctic_continental": "Северо-восточная тайга",
    "right_cold_highlands": "Северо-восточное нагорье",
    "right_cool_maritime": "Восточное побережье",
    "right_boreal_wet": "Северо-восточные леса",
    "right_cool_continental": "Восточная тайга",
    "right_cool_highlands": "Восточное нагорье",
    "right_temperate_wet": "Восточное междуречье",
    "right_temperate_continental": "Восточные равнины",
    "right_temperate_highlands": "Восточное умеренное нагорье",
}

OUTER_CLIMATE_BELTS = {
    "left_polar": 0,
    "left_subarctic_maritime": 1,
    "left_subarctic_continental": 1,
    "left_cold_highlands": 1,
    "left_cool_maritime": 2,
    "left_cool_continental": 2,
    "left_cool_highlands": 2,
    "left_temperate_wet": 3,
    "left_temperate_continental": 3,
    "left_temperate_highlands": 3,
    "left_warm_interior": 4,
    "left_southern_coast": 4,
    "right_polar": 0,
    "right_subarctic_maritime": 1,
    "right_subarctic_continental": 1,
    "right_cold_highlands": 1,
    "right_cool_maritime": 2,
    "right_boreal_wet": 2,
    "right_cool_continental": 2,
    "right_cool_highlands": 2,
    "right_temperate_wet": 3,
    "right_temperate_continental": 3,
    "right_temperate_highlands": 3,
    "world_polar": 0,
    "world_subarctic_maritime": 1,
    "world_subarctic_continental": 1,
    "world_cold_highlands": 1,
    "world_cool_maritime": 2,
    "world_boreal_wet": 2,
    "world_cool_continental": 2,
    "world_cool_highlands": 2,
    "world_temperate_wet": 3,
    "world_temperate_continental": 3,
    "world_temperate_highland": 3,
    "world_warm_maritime": 4,
    "world_warm_interior": 4,
    "world_hot_highland": 4,
    "world_tropical_maritime": 5,
    "world_hot_arid": 5,
}

# A small set of coherent macro-toponyms. States inside one area use the same
# root with geographical qualifiers, so names read as parts of one place rather
# than 220 unrelated procedurally spliced words.
OUTER_MACRO_TOPONYMS = {
    ("right", 0, 0): ("Скарв", "Скарвский", "Скарвская", "Скарвское", "Скарвские"),
    ("right", 0, 1): ("Нордваль", "Нордвальский", "Нордвальская", "Нордвальское", "Нордвальские"),
    ("right", 0, 2): ("Кальвик", "Кальвикский", "Кальвикская", "Кальвикское", "Кальвикские"),
    ("right", 1, 0): ("Вардена", "Варденский", "Варденская", "Варденское", "Варденские"),
    ("right", 1, 1): ("Хольмер", "Хольмерский", "Хольмерская", "Хольмерское", "Хольмерские"),
    ("right", 1, 2): ("Эйрен", "Эйренский", "Эйренская", "Эйренское", "Эйренские"),
    ("right", 2, 0): ("Вельден", "Вельденский", "Вельденская", "Вельденское", "Вельденские"),
    ("right", 2, 1): ("Ровен", "Ровенский", "Ровенская", "Ровенское", "Ровенские"),
    ("right", 2, 2): ("Тарвик", "Тарвикский", "Тарвикская", "Тарвикское", "Тарвикские"),
    ("right", 3, 0): ("Дравен", "Дравенский", "Дравенская", "Дравенское", "Дравенские"),
    ("right", 3, 1): ("Келвор", "Келворский", "Келворская", "Келворское", "Келворские"),
    ("right", 3, 2): ("Бастар", "Бастарский", "Бастарская", "Бастарское", "Бастарские"),
    ("left", 0, 0): ("Хаверн", "Хавернский", "Хавернская", "Хавернское", "Хавернские"),
    ("left", 0, 1): ("Нордмар", "Нордмарский", "Нордмарская", "Нордмарское", "Нордмарские"),
    ("left", 0, 2): ("Эльмарк", "Эльмаркский", "Эльмаркская", "Эльмаркское", "Эльмаркские"),
    ("left", 1, 0): ("Дорвей", "Дорвейский", "Дорвейская", "Дорвейское", "Дорвейские"),
    ("left", 1, 1): ("Остер", "Остерский", "Остерская", "Остерское", "Остерские"),
    ("left", 1, 2): ("Брейн", "Брейнский", "Брейнская", "Брейнское", "Брейнские"),
    ("left", 2, 0): ("Лорн", "Лорнский", "Лорнская", "Лорнское", "Лорнские"),
    ("left", 2, 1): ("Дален", "Даленский", "Даленская", "Даленское", "Даленские"),
    ("left", 2, 2): ("Верна", "Верненский", "Верненская", "Верненское", "Верненские"),
    ("left", 3, 0): ("Сельвен", "Сельвенский", "Сельвенская", "Сельвенское", "Сельвенские"),
    ("left", 3, 1): ("Альба", "Альбинский", "Альбинская", "Альбинское", "Альбинские"),
    ("left", 3, 2): ("Мерет", "Меретский", "Меретская", "Меретское", "Меретские"),
    ("left", 4, 0): ("Солвен", "Солвенский", "Солвенская", "Солвенское", "Солвенские"),
    ("left", 4, 1): ("Эллар", "Элларский", "Элларская", "Элларское", "Элларские"),
    ("left", 4, 2): ("Кастель", "Кастельский", "Кастельская", "Кастельское", "Кастельские"),
    ("right", 0, 3): ("Илмар", "Илмарский", "Илмарская", "Илмарское", "Илмарские"),
    ("right", 0, 4): ("Рунн", "Руннский", "Руннская", "Руннское", "Руннские"),
    ("right", 1, 3): ("Фальск", "Фальский", "Фальская", "Фальское", "Фальские"),
    ("right", 1, 4): ("Тромен", "Троменский", "Троменская", "Троменское", "Троменские"),
    ("right", 2, 3): ("Линдор", "Линдорский", "Линдорская", "Линдорское", "Линдорские"),
    ("right", 2, 4): ("Острен", "Остренский", "Остренская", "Остренское", "Остренские"),
    ("right", 3, 3): ("Эстен", "Эстенский", "Эстенская", "Эстенское", "Эстенские"),
    ("right", 3, 4): ("Лаэрн", "Лаэрнский", "Лаэрнская", "Лаэрнское", "Лаэрнские"),
    ("left", 0, 3): ("Скейл", "Скейльский", "Скейльская", "Скейльское", "Скейльские"),
    ("left", 0, 4): ("Кервик", "Кервикский", "Кервикская", "Кервикское", "Кервикские"),
    ("left", 1, 3): ("Левен", "Левенский", "Левенская", "Левенское", "Левенские"),
    ("left", 1, 4): ("Фарн", "Фарнский", "Фарнская", "Фарнское", "Фарнские"),
    ("left", 2, 3): ("Мелвен", "Мелвенский", "Мелвенская", "Мелвенское", "Мелвенские"),
    ("left", 2, 4): ("Торен", "Торенский", "Торенская", "Торенское", "Торенские"),
    ("left", 3, 3): ("Реймар", "Реймарский", "Реймарская", "Реймарское", "Реймарские"),
    ("left", 3, 4): ("Валлен", "Валленский", "Валленская", "Валленское", "Валленские"),
    ("left", 4, 3): ("Кадвен", "Кадвенский", "Кадвенская", "Кадвенское", "Кадвенские"),
    ("left", 4, 4): ("Сайлен", "Сайленский", "Сайленская", "Сайленское", "Сайленские"),
}

OUTER_X_BOUNDS = {
    "left": (1000.0, 1350.0, 1700.0, 2050.0, 2400.0, 2900.0),
    "right": (2800.0, 3200.0, 3550.0, 3900.0, 4250.0, 4800.0),
}
OUTER_Y_BOUNDS = {
    "left": ((0.0, 300.0), (300.0, 650.0), (650.0, 900.0), (900.0, 1550.0), (1550.0, 2048.0)),
    "right": ((0.0, 300.0), (300.0, 520.0), (520.0, 780.0), (780.0, 1200.0)),
}


def outer_macro_toponym(climate_key: str, x: float) -> tuple[str, str, str, str, str]:
    landmass = "left" if climate_key.startswith("left_") else "right"
    edges = OUTER_X_BOUNDS[landmass]
    sector = next(
        (index for index in range(len(edges) - 1) if x < edges[index + 1]),
        len(edges) - 2,
    )
    return OUTER_MACRO_TOPONYMS[(landmass, OUTER_CLIMATE_BELTS[climate_key], sector)]


def outer_macro_bounds(climate_key: str, x: float) -> tuple[float, float, float, float]:
    landmass = "left" if climate_key.startswith("left_") else "right"
    edges = OUTER_X_BOUNDS[landmass]
    sector = next(
        (index for index in range(len(edges) - 1) if x < edges[index + 1]),
        len(edges) - 2,
    )
    y_min, y_max = OUTER_Y_BOUNDS[landmass][OUTER_CLIMATE_BELTS[climate_key]]
    return edges[sector], edges[sector + 1], y_min, y_max


def outer_region_name(climate_key: str, x: float) -> str:
    _root, masculine, feminine, neuter, plural = outer_macro_toponym(climate_key, x)
    if climate_key.endswith("_polar"):
        return f"{feminine} тундра"
    if climate_key.endswith("_maritime") or climate_key.endswith("_coast"):
        return f"{neuter} побережье"
    if climate_key.endswith("_highlands"):
        return f"{neuter} нагорье"
    if climate_key.endswith("_boreal_wet"):
        return f"{plural} леса"
    if climate_key.endswith("_wet"):
        return f"{neuter} междуречье"
    if climate_key.endswith("_warm_interior"):
        return f"{plural} степи"
    if climate_key.endswith("_continental"):
        if OUTER_CLIMATE_BELTS[climate_key] <= 2:
            return f"{feminine} тайга"
        return f"{plural} равнины"
    return f"{masculine} край"


def outer_region_name_gender(climate_key: str) -> int:
    """Return 0 masculine, 1 feminine, 2 neuter, or 3 plural."""
    if climate_key.endswith("_polar"):
        return 1
    if climate_key.endswith(("_boreal_wet", "_warm_interior")):
        return 3
    if climate_key.endswith(("_maritime", "_coast", "_highlands", "_wet")):
        return 2
    if climate_key.endswith("_continental"):
        return 1 if OUTER_CLIMATE_BELTS[climate_key] <= 2 else 3
    return 0


HORIZONTAL_REGION_QUALIFIERS = {
    2: (("Западный", "Западная", "Западное", "Западные"), ("Восточный", "Восточная", "Восточное", "Восточные")),
    3: (("Западный", "Западная", "Западное", "Западные"), ("Центральный", "Центральная", "Центральное", "Центральные"), ("Восточный", "Восточная", "Восточное", "Восточные")),
}
VERTICAL_REGION_QUALIFIERS = {
    2: (("Северный", "Северная", "Северное", "Северные"), ("Южный", "Южная", "Южное", "Южные")),
    3: (("Северный", "Северная", "Северное", "Северные"), ("Центральный", "Центральная", "Центральное", "Центральные"), ("Южный", "Южная", "Южное", "Южные")),
}


MONTH_RANGES = (
    "0.0 30.0", "0.1 27.1", "0.2 30.2", "0.3 29.3",
    "0.4 30.4", "0.5 29.5", "0.6 30.6", "0.7 30.7",
    "0.8 29.8", "0.9 30.9", "0.10 29.10", "0.11 30.11",
)


TEMPERATURES = {
    "polar_ocean": ((-26, -8), (-25, -7), (-21, -4), (-14, 2), (-7, 7), (-2, 12), (1, 15), (0, 13), (-4, 8), (-11, 2), (-19, -4), (-24, -7)),
    "subpolar_ocean": ((-15, 2), (-14, 3), (-9, 7), (-3, 12), (2, 17), (7, 21), (10, 24), (9, 23), (5, 19), (0, 13), (-6, 7), (-12, 3)),
    "temperate_ocean": ((-4, 12), (-3, 13), (1, 16), (5, 20), (9, 24), (13, 27), (16, 30), (16, 30), (12, 26), (7, 21), (2, 16), (-2, 13)),
    "warm_ocean": ((10, 23), (11, 24), (14, 27), (17, 30), (20, 33), (23, 35), (25, 37), (25, 37), (23, 35), (19, 32), (15, 27), (11, 24)),
    "tropical_ocean": ((20, 31), (20, 31), (21, 32), (22, 33), (23, 34), (24, 35), (25, 36), (25, 36), (24, 35), (23, 34), (22, 33), (21, 32)),
    "polar": ((-32, -15), (-30, -13), (-25, -8), (-16, 0), (-8, 6), (-2, 11), (1, 14), (0, 12), (-5, 7), (-13, 1), (-22, -7), (-29, -12)),
    "subarctic_maritime": ((-21, -6), (-19, -4), (-13, 2), (-6, 9), (0, 15), (6, 20), (9, 23), (8, 22), (3, 17), (-3, 10), (-10, 2), (-17, -4)),
    "subarctic_continental": ((-27, -10), (-24, -7), (-16, 1), (-7, 11), (1, 18), (7, 24), (10, 27), (8, 25), (2, 18), (-5, 9), (-14, -2), (-23, -8)),
    "cold_highland": ((-29, -12), (-27, -10), (-20, -4), (-11, 5), (-3, 13), (3, 18), (6, 21), (5, 19), (-1, 14), (-8, 5), (-17, -5), (-26, -10)),
    "cool_maritime": ((-12, 3), (-11, 4), (-7, 8), (-1, 14), (4, 19), (9, 23), (12, 26), (11, 25), (7, 20), (2, 14), (-4, 8), (-9, 4)),
    "boreal_wet": ((-16, -2), (-14, 0), (-8, 7), (-1, 14), (5, 20), (10, 25), (13, 28), (12, 27), (7, 21), (1, 13), (-6, 6), (-13, 0)),
    "cool_continental": ((-18, -3), (-16, 0), (-9, 7), (-1, 15), (5, 21), (10, 27), (13, 30), (11, 28), (6, 22), (-1, 14), (-8, 6), (-15, 0)),
    "temperate_continental": ((-4, 8), (-3, 9), (0, 13), (4, 19), (8, 24), (13, 29), (16, 32), (14, 30), (9, 25), (3, 18), (0, 11), (-3, 8)),
    "temperate_wet": ((-1, 9), (0, 10), (2, 14), (6, 19), (10, 24), (14, 28), (17, 31), (16, 30), (12, 26), (7, 20), (2, 13), (0, 9)),
    "cool_highland": ((-18, -2), (-16, 0), (-10, 6), (-4, 12), (1, 17), (6, 22), (9, 25), (8, 23), (3, 18), (-3, 11), (-9, 5), (-15, 0)),
    "temperate_highland": ((-7, 5), (-6, 6), (-2, 11), (2, 16), (6, 21), (10, 25), (13, 28), (12, 27), (8, 22), (3, 16), (-2, 10), (-6, 6)),
    "warm_semiarid": ((1, 16), (3, 19), (7, 23), (11, 28), (15, 33), (19, 37), (22, 40), (21, 39), (17, 34), (11, 28), (6, 22), (2, 18)),
    "arid_highland": ((-5, 12), (-3, 15), (2, 20), (7, 25), (12, 30), (16, 34), (19, 37), (18, 36), (13, 31), (7, 25), (1, 18), (-3, 13)),
    "arid": ((2, 18), (4, 21), (9, 27), (14, 33), (19, 38), (23, 42), (26, 45), (25, 44), (20, 39), (14, 32), (8, 25), (3, 19)),
    "hot_arid": ((7, 23), (9, 26), (14, 31), (19, 36), (24, 41), (28, 45), (30, 47), (29, 46), (25, 42), (19, 36), (13, 29), (8, 24)),
    "hot_highland": ((2, 17), (4, 19), (8, 23), (12, 27), (16, 31), (20, 35), (22, 37), (21, 36), (17, 32), (12, 27), (7, 22), (3, 18)),
    "tropical_maritime": ((18, 30), (19, 31), (20, 32), (21, 33), (22, 34), (23, 34), (24, 35), (24, 35), (23, 34), (22, 33), (20, 32), (19, 31)),
    "warm_maritime": ((8, 21), (9, 22), (12, 25), (15, 28), (18, 31), (21, 33), (23, 35), (23, 35), (20, 32), (16, 29), (12, 25), (9, 22)),
}


def phenomenon(climate: str, month: int) -> tuple[float, float, float, float, float, float, float]:
    """Return independent weather weights plus mud and sandstorm intensity.

    Clausewitz does not treat these values as one normalized probability
    distribution.  In particular, vanilla commonly combines a clear-weather
    weight around 0.5 with rain_light at 0.4-1.0, while mud may exceed 1.0.
    Keeping the values independent is important: normalizing their sum makes
    every climate unnaturally dry and suppresses the gameplay weather effects.
    """
    winter = month in (11, 0, 1)
    shoulder = month in (2, 3, 9, 10)
    summer = month in (5, 6, 7)

    if climate == "polar_ocean":
        return (0.30, 0.10, 0.03, 0.55, 0.30, 0.0, 0.0) if winter else (0.38, 0.35, 0.12, 0.30, 0.12, 0.0, 0.0)
    if climate == "subpolar_ocean":
        if winter:
            return (0.35, 0.30, 0.12, 0.35, 0.15, 0.0, 0.0)
        return (0.40, 0.55, 0.22, 0.05, 0.01, 0.0, 0.0)
    if climate == "temperate_ocean":
        return (0.45, 0.60, 0.25, 0.10 if winter else 0.0, 0.03 if winter else 0.0, 0.0, 0.0)
    if climate == "warm_ocean":
        return (0.50, 0.45, 0.25, 0.0, 0.0, 0.0, 0.0)
    if climate == "tropical_ocean":
        return (0.30, 0.45, 0.45, 0.0, 0.0, 0.0, 0.0) if month in (4, 5, 6, 7, 8) else (0.50, 0.40, 0.25, 0.0, 0.0, 0.0, 0.0)
    if climate == "polar":
        if winter:
            return (0.32, 0.05, 0.01, 0.55, 0.30, 0.35, 0.0)
        if shoulder:
            return (0.40, 0.15, 0.05, 0.35, 0.15, 0.55, 0.0)
        return (0.45, 0.25, 0.08, 0.12, 0.03, 0.45, 0.0)
    if climate == "subarctic_maritime":
        if winter:
            return (0.36, 0.20, 0.08, 0.45, 0.18, 0.60, 0.0)
        if shoulder:
            return (0.35, 0.45, 0.18, 0.18, 0.05, 1.00, 0.0)
        return (0.42, 0.45, 0.18, 0.03, 0.0, 0.70, 0.0)
    if climate == "subarctic_continental":
        if winter:
            return (0.42, 0.08, 0.02, 0.50, 0.22, 0.45, 0.0)
        if shoulder:
            return (0.45, 0.25, 0.08, 0.25, 0.06, 1.10, 0.0)
        return (0.54, 0.35, 0.12, 0.03, 0.0, 0.70, 0.0)
    if climate == "cold_highland":
        if winter:
            return (0.34, 0.10, 0.03, 0.55, 0.25, 0.40, 0.0)
        if shoulder:
            return (0.39, 0.28, 0.10, 0.30, 0.08, 0.90, 0.0)
        return (0.48, 0.35, 0.12, 0.10, 0.02, 0.55, 0.0)
    if climate == "cool_maritime":
        if winter:
            return (0.40, 0.75, 0.18, 0.24, 0.05, 0.55, 0.0)
        if shoulder:
            return (0.36, 0.85, 0.22, 0.08, 0.02, 0.90, 0.0)
        return (0.43, 0.75, 0.20, 0.0, 0.0, 0.65, 0.0)
    if climate == "boreal_wet":
        if winter:
            return (0.38, 0.30, 0.10, 0.32, 0.08, 0.70, 0.0)
        if shoulder:
            return (0.34, 0.50, 0.20, 0.15, 0.03, 1.20, 0.0)
        return (0.40, 0.55, 0.25, 0.0, 0.0, 0.90, 0.0)
    if climate in ("cool_continental", "cool_highland"):
        if winter:
            return (0.42, 0.12, 0.04, 0.34, 0.10, 0.65, 0.0)
        if shoulder:
            return (0.43, 0.35, 0.12, 0.12, 0.03, 1.15, 0.0)
        return (0.51, 0.40, 0.15, 0.0, 0.0, 0.75, 0.0)
    if climate in ("temperate_continental", "temperate_highland"):
        if winter:
            return (0.52, 0.18, 0.06, 0.14, 0.02, 0.60, 0.0)
        if shoulder:
            return (0.46, 0.40, 0.14, 0.03, 0.0, 1.10, 0.0)
        return (0.50, 0.45, 0.18, 0.0, 0.0, 0.80, 0.0)
    if climate == "temperate_wet":
        if winter:
            return (0.42, 0.45, 0.16, 0.08, 0.01, 0.75, 0.0)
        if shoulder:
            return (0.35, 0.65, 0.28, 0.01, 0.0, 1.25, 0.0)
        return (0.38, 0.60, 0.30, 0.0, 0.0, 1.00, 0.0)
    if climate == "warm_semiarid":
        return (0.64, 0.12, 0.04, 0.03 if winter else 0.0, 0.0, 0.35 if shoulder else 0.12, 0.25 if summer else 0.15)
    if climate in ("arid", "arid_highland", "hot_arid"):
        rain_light = 0.04 if winter or shoulder else 0.02
        rain_heavy = 0.01 if winter or shoulder else 0.0
        snow = 0.12 if climate == "arid_highland" and winter else 0.0
        sand = 0.40 if summer else 0.25
        return (0.67, rain_light, rain_heavy, snow, 0.02 if snow else 0.0, 0.12 if shoulder else 0.04, sand)
    if climate == "hot_highland":
        return (0.55, 0.22, 0.08, 0.02 if winter else 0.0, 0.0, 0.50 if shoulder else 0.25, 0.15 if summer else 0.08)
    if climate == "tropical_maritime":
        if month in (4, 5, 6, 7, 8):
            return (0.28, 0.45, 0.50, 0.0, 0.0, 1.25, 0.0)
        return (0.47, 0.35, 0.25, 0.0, 0.0, 0.75, 0.0)
    if climate == "warm_maritime":
        return (0.42, 0.60, 0.25, 0.0, 0.0, 0.90 if shoulder else 0.60, 0.0)
    raise ValueError(f"unknown climate profile: {climate}")


def arctic_water(climate: str, month: int) -> float:
    if climate == "polar_ocean":
        return 0.70 if month in (11, 0, 1) else 0.35 if month in (2, 3, 9, 10) else 0.08
    if climate == "subpolar_ocean":
        return 0.25 if month in (11, 0, 1) else 0.05 if month in (2, 10) else 0.0
    return 0.0


def minimum_snow_level(climate: str, month: int) -> float:
    """Use vanilla-scale floors; startup accumulation is handled globally.

    This value is not a deterministic initial snow layer.  Raising it above
    vanilla's usual 0.1-0.3 range only distorts weather after a snowy state has
    already been selected, while leaving the initial region-shaped gaps intact.
    """
    winter = month in (11, 0, 1)
    shoulder = month in (2, 3, 9, 10)
    if climate == "polar_ocean":
        return 0.20 if winter else 0.10 if shoulder else 0.0
    if climate == "polar":
        return 0.30 if winter else 0.20 if shoulder else 0.0
    if climate == "subpolar_ocean":
        return 0.10 if winter else 0.03 if shoulder else 0.0
    if climate in ("subarctic_maritime", "subarctic_continental"):
        return 0.20 if winter else 0.10 if shoulder else 0.0
    if climate == "cold_highland":
        return 0.30 if winter else 0.15 if shoulder else 0.0
    if climate in ("cool_maritime", "boreal_wet", "cool_continental", "cool_highland"):
        return 0.10 if winter else 0.0
    if climate == "temperate_highland":
        return 0.10 if winter else 0.0
    if climate == "arid_highland":
        return 0.05 if winter else 0.0
    return 0.0


def load_states() -> dict[int, set[int]]:
    states: dict[int, set[int]] = {}
    for path in STATE_DIR.glob("*.txt"):
        text = path.read_text(encoding="utf-8-sig", errors="strict")
        state_match = re.search(r"\bid\s*=\s*(\d+)", text)
        province_match = re.search(r"\bprovinces\s*=\s*\{([^}]*)\}", text, re.DOTALL)
        if not state_match or not province_match:
            continue
        state_id = int(state_match.group(1))
        if state_id in states:
            raise ValueError(f"duplicate state id {state_id}")
        states[state_id] = {int(value) for value in re.findall(r"\d+", province_match.group(1))}
    return states


def load_province_definitions() -> tuple[dict[int, str], dict[int, int]]:
    provinces: dict[int, str] = {}
    colors: dict[int, int] = {}
    with (ROOT / "map" / "definition.csv").open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.reader(handle, delimiter=";"):
            if len(row) >= 5 and row[0].isdigit() and int(row[0]) > 0:
                province_id = int(row[0])
                provinces[province_id] = row[4]
                color = (int(row[1]) << 16) | (int(row[2]) << 8) | int(row[3])
                if color in colors:
                    raise ValueError(f"duplicate province color in definition.csv: {row[1:4]}")
                colors[color] = province_id
    return provinces, colors


def load_province_types() -> dict[int, str]:
    return load_province_definitions()[0]


def load_province_adjacency(
    province_types: dict[int, str],
    color_to_province: dict[int, int],
    include_special_adjacencies: bool = True,
) -> dict[int, set[int]]:
    """Read physical borders and, optionally, special links into a province graph."""
    adjacency = {province_id: set() for province_id in province_types}
    with Image.open(ROOT / "map" / "provinces.bmp") as source:
        image = source.convert("RGB")
        width, height = image.size
        red, green, blue = (band.tobytes() for band in image.split())

    previous_row = [-1] * width
    for y in range(height):
        row_start = y * width
        first = -1
        left = -1
        for x in range(width):
            offset = row_start + x
            color = (red[offset] << 16) | (green[offset] << 8) | blue[offset]
            try:
                province_id = color_to_province[color]
            except KeyError as exc:
                raise ValueError(
                    f"provinces.bmp uses undefined color {color >> 16};{(color >> 8) & 255};{color & 255} at {x},{y}"
                ) from exc
            if x == 0:
                first = province_id
            elif province_id != left:
                adjacency[province_id].add(left)
                adjacency[left].add(province_id)
            above = previous_row[x]
            if above != -1 and province_id != above:
                adjacency[province_id].add(above)
                adjacency[above].add(province_id)
            previous_row[x] = province_id
            left = province_id

        # Clausewitz maps wrap horizontally, so the two map edges are adjacent.
        if first != left:
            adjacency[first].add(left)
            adjacency[left].add(first)

    adjacency_path = ROOT / "map" / "adjacencies.csv"
    if include_special_adjacencies and adjacency_path.exists():
        with adjacency_path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.reader(handle, delimiter=";"):
                if len(row) < 2 or not row[0].isdigit() or not row[1].isdigit():
                    continue
                first, second = int(row[0]), int(row[1])
                if first in adjacency and second in adjacency:
                    adjacency[first].add(second)
                    adjacency[second].add(first)
    return adjacency


def connected_components(nodes: set[int], adjacency: dict[int, set[int]]) -> list[set[int]]:
    remaining = set(nodes)
    components: list[set[int]] = []
    while remaining:
        start = min(remaining)
        component = {start}
        queue = deque((start,))
        remaining.remove(start)
        while queue:
            province_id = queue.popleft()
            for neighbour in adjacency[province_id]:
                if neighbour in remaining:
                    remaining.remove(neighbour)
                    component.add(neighbour)
                    queue.append(neighbour)
        components.append(component)
    return sorted(components, key=lambda component: (-len(component), min(component)))


def partition_connected_sea(
    sea: set[int],
    adjacency: dict[int, set[int]],
    positions: dict[int, tuple[float, float, float]],
) -> dict[int, set[int]]:
    """Partition one connected ocean with a seeded BFS, preserving connectivity."""
    seeds: dict[int, int] = {}
    for sea_region in SEA_REGIONS:
        candidates = [
            province_id
            for province_id in sea
            if sea_region_id_for(positions[province_id]) == sea_region.region_id
        ]
        if not candidates:
            raise ValueError(f"sea strategic region {sea_region.region_id} has no seed candidates")
        center_x = sum(positions[province_id][0] for province_id in candidates) / len(candidates)
        center_z = sum(positions[province_id][2] for province_id in candidates) / len(candidates)
        seeds[sea_region.region_id] = min(
            candidates,
            key=lambda province_id: (
                (positions[province_id][0] - center_x) ** 2 + (positions[province_id][2] - center_z) ** 2,
                province_id,
            ),
        )

    assignments = {province_id: region_id for region_id, province_id in seeds.items()}
    queue = deque(seeds[region_id] for region_id in sorted(seeds))
    while queue:
        province_id = queue.popleft()
        region_id = assignments[province_id]
        for neighbour in sorted(adjacency[province_id]):
            if neighbour in sea and neighbour not in assignments:
                assignments[neighbour] = region_id
                queue.append(neighbour)
    if set(assignments) != sea:
        raise ValueError("main ocean component could not be fully partitioned")

    partition = {region.region_id: set() for region in SEA_REGIONS}
    for province_id, region_id in assignments.items():
        partition[region_id].add(province_id)
    return partition


def load_province_positions() -> dict[int, tuple[float, float, float]]:
    positions: dict[int, tuple[float, float, float]] = {}
    with (ROOT / "map" / "unitstacks.txt").open(encoding="utf-8-sig", errors="strict") as handle:
        for line in handle:
            fields = line.strip().split(";")
            if len(fields) < 5 or not fields[0].isdigit() or fields[1] != "0":
                continue
            province_id = int(fields[0])
            positions.setdefault(province_id, (float(fields[2]), float(fields[3]), float(fields[4])))
    return positions


def build_state_adjacency(
    states: dict[int, set[int]], province_adjacency: dict[int, set[int]]
) -> dict[int, set[int]]:
    """Collapse physical province borders into a state-neighbour graph."""
    state_by_province = {
        province_id: state_id
        for state_id, provinces in states.items()
        for province_id in provinces
    }
    adjacency = {state_id: set() for state_id in states}
    for province_id, state_id in state_by_province.items():
        for neighbour in province_adjacency.get(province_id, set()):
            other_state = state_by_province.get(neighbour)
            if other_state is not None and other_state != state_id:
                adjacency[state_id].add(other_state)
    return adjacency


def _partition_connected_states(
    nodes: set[int],
    parts: int,
    adjacency: dict[int, set[int]],
    weights: dict[int, float],
    centers: dict[int, tuple[float, float]],
) -> list[set[int]]:
    """Split a connected state graph via cuts that keep both sides connected."""
    if parts <= 1:
        return [set(nodes)]
    if len(nodes) < parts:
        raise ValueError(f"cannot split {len(nodes)} states into {parts} connected parts")

    total_weight = sum(weights[node] for node in nodes)
    center_x = sum(centers[node][0] * weights[node] for node in nodes) / total_weight
    center_z = sum(centers[node][1] * weights[node] for node in nodes) / total_weight
    root = min(
        nodes,
        key=lambda node: (
            (centers[node][0] - center_x) ** 2 + (centers[node][1] - center_z) ** 2,
            node,
        ),
    )

    parent: dict[int, int | None] = {root: None}
    order: list[int] = []
    queue = deque((root,))
    while queue:
        node = queue.popleft()
        order.append(node)
        neighbours = sorted(
            adjacency[node] & nodes,
            key=lambda other: (
                (centers[other][0] - centers[node][0]) ** 2
                + (centers[other][1] - centers[node][1]) ** 2,
                other,
            ),
        )
        for neighbour in neighbours:
            if neighbour not in parent:
                parent[neighbour] = node
                queue.append(neighbour)
    if len(order) != len(nodes):
        raise ValueError("attempted to partition a disconnected state graph")

    subtrees = {node: {node} for node in nodes}
    subtree_weights = {node: weights[node] for node in nodes}
    for node in reversed(order[1:]):
        ancestor = parent[node]
        assert ancestor is not None
        subtrees[ancestor].update(subtrees[node])
        subtree_weights[ancestor] += subtree_weights[node]

    ideal_weight = total_weight / parts
    candidates: list[tuple[float, int, int, set[int]]] = []
    for branch_root in order[1:]:
        branch = subtrees[branch_root]
        remainder_size = len(nodes) - len(branch)
        minimum_branch_parts = max(1, parts - remainder_size)
        maximum_branch_parts = min(parts - 1, len(branch))
        for branch_parts in range(minimum_branch_parts, maximum_branch_parts + 1):
            branch_weight = subtree_weights[branch_root]
            remainder_parts = parts - branch_parts
            score = (
                abs(branch_weight - ideal_weight * branch_parts)
                + abs((total_weight - branch_weight) - ideal_weight * remainder_parts)
            ) / total_weight
            candidates.append((score, branch_root, branch_parts, branch))
    if not candidates:
        raise ValueError(f"no connected cut can split {len(nodes)} states into {parts} parts")

    _score, _branch_root, branch_parts, branch = min(
        candidates, key=lambda row: (row[0], row[1], row[2])
    )
    remainder = nodes - branch
    return (
        _partition_connected_states(branch, branch_parts, adjacency, weights, centers)
        + _partition_connected_states(remainder, parts - branch_parts, adjacency, weights, centers)
    )


def _roman(value: int) -> str:
    numerals = ((10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"))
    result = ""
    for number, glyph in numerals:
        while value >= number:
            result += glyph
            value -= number
    return result


def load_generated_outer_regions() -> tuple[Region, ...]:
    generated_states: dict[int, set[int]] = {}
    climate_by_state: dict[int, str] = {}
    preferred_names: dict[int, str] = {}
    for path in STATE_DIR.glob("*.txt"):
        source = path.read_text(encoding="utf-8-sig", errors="strict")
        if not source.startswith((OUTER_STATE_MARKER, REMAINDER_STATE_MARKER)):
            continue
        state_match = re.search(r"\bid\s*=\s*(\d+)", source)
        climate_match = re.search(r"(?m)^# adiscord_climate_region = ([a-z_]+)\s*$", source)
        preferred_name_match = re.search(r"(?m)^# adiscord_strategic_name = (.+?)\s*$", source)
        province_match = re.search(r"\bprovinces\s*=\s*\{([^}]*)\}", source, re.DOTALL)
        if not state_match or not climate_match or not province_match:
            raise ValueError(f"{path.name}: generated outer state lacks id, provinces, or climate marker")
        state_id = int(state_match.group(1))
        climate_key = climate_match.group(1)
        if climate_key not in OUTER_REGION_SPECS:
            raise ValueError(f"{path.name}: unknown outer climate key {climate_key}")
        generated_states[state_id] = {int(value) for value in re.findall(r"\d+", province_match.group(1))}
        climate_by_state[state_id] = climate_key
        if source.startswith(REMAINDER_STATE_MARKER):
            if not preferred_name_match:
                raise ValueError(f"{path.name}: remainder state lacks a strategic-name marker")
            preferred_names[state_id] = preferred_name_match.group(1).strip()

    if not generated_states:
        return ()

    province_types, color_to_province = load_province_definitions()
    physical_adjacency = load_province_adjacency(
        province_types, color_to_province, include_special_adjacencies=False
    )
    state_adjacency = build_state_adjacency(generated_states, physical_adjacency)
    province_positions = load_province_positions()
    province_weights = {state_id: len(provinces) for state_id, provinces in generated_states.items()}
    centers: dict[int, tuple[float, float]] = {}
    for state_id, provinces in generated_states.items():
        available = [province_positions[province_id] for province_id in provinces if province_id in province_positions]
        if not available:
            raise ValueError(f"generated state {state_id} has no map positions")
        centers[state_id] = (
            sum(position[0] for position in available) / len(available),
            sum(position[2] for position in available) / len(available),
        )

    cluster_rows: list[tuple[str, set[int], str]] = []
    climate_zones: dict[tuple[str, int], set[int]] = {}
    for state_id, climate_key in climate_by_state.items():
        landmass = climate_key.split("_", 1)[0]
        if landmass not in ("left", "right", "world"):
            raise ValueError(f"state {state_id}: cannot infer landmass from climate key {climate_key}")
        climate_zones.setdefault((landmass, OUTER_CLIMATE_BELTS[climate_key]), set()).add(state_id)

    for (landmass, belt), zone_states in sorted(climate_zones.items()):
        if landmass == "world":
            # Remainder shells are maximal physically connected components of
            # one latitude band, so they intentionally remain one region each.
            target_provinces = 1.0
        elif landmass == "left":
            target_provinces = (180.0, 180.0, 220.0, 420.0, 520.0)[belt]
        else:
            target_provinces = (220.0, 200.0, 220.0, 250.0)[belt]
        partition_weights = {
            state_id: (1.0 if landmass == "world" else province_weights[state_id] / target_provinces)
            for state_id in zone_states
        }

        for component in connected_components(zone_states, state_adjacency):
            part_count = min(
                len(component),
                max(1, math.ceil(sum(partition_weights[state_id] for state_id in component))),
            )
            clusters = _partition_connected_states(
                component, part_count, state_adjacency, partition_weights, centers
            )
            for cluster in clusters:
                climate_counts = Counter(
                    {
                        key: sum(
                            province_weights[state_id]
                            for state_id in cluster
                            if climate_by_state[state_id] == key
                        )
                        for key in OUTER_REGION_SPECS
                    }
                )
                climate_key = min(
                    climate_counts,
                    key=lambda key: (-climate_counts[key], key),
                )
                cluster_rows.append((landmass, cluster, climate_key))

    cluster_rows.sort(
        key=lambda row: (
            {"right": 0, "left": 1, "world": 2}[row[0]],
            -sum(centers[state_id][1] * province_weights[state_id] for state_id in row[1])
            / sum(province_weights[state_id] for state_id in row[1]),
            sum(centers[state_id][0] * province_weights[state_id] for state_id in row[1])
            / sum(province_weights[state_id] for state_id in row[1]),
            min(row[1]),
        )
    )
    region_centers = [
        (
            sum(centers[state_id][0] * province_weights[state_id] for state_id in cluster)
            / sum(province_weights[state_id] for state_id in cluster),
            sum(centers[state_id][1] * province_weights[state_id] for state_id in cluster)
            / sum(province_weights[state_id] for state_id in cluster),
        )
        for _landmass, cluster, _climate_key in cluster_rows
    ]
    base_names: list[str] = []
    for index, (landmass, cluster, climate_key) in enumerate(cluster_rows):
        if landmass == "world":
            if len(cluster) != 1:
                raise ValueError(f"world remainder region unexpectedly groups states {sorted(cluster)}")
            state_id = next(iter(cluster))
            try:
                base_names.append(preferred_names[state_id])
            except KeyError as exc:
                raise ValueError(f"world remainder state {state_id} lacks a preferred region name") from exc
        else:
            base_names.append(outer_region_name(climate_key, region_centers[index][0]))
    display_names = list(base_names)
    duplicate_groups: dict[str, list[int]] = {}
    for index, base_name in enumerate(base_names):
        duplicate_groups.setdefault(base_name, []).append(index)
    for base_name, indices in duplicate_groups.items():
        if len(indices) == 1:
            continue
        x_span = max(region_centers[index][0] for index in indices) - min(region_centers[index][0] for index in indices)
        z_span = max(region_centers[index][1] for index in indices) - min(region_centers[index][1] for index in indices)
        horizontal = x_span >= z_span
        qualifiers_by_count = HORIZONTAL_REGION_QUALIFIERS if horizontal else VERTICAL_REGION_QUALIFIERS
        if len(indices) not in qualifiers_by_count:
            raise ValueError(f"cannot geographically disambiguate {len(indices)} regions named {base_name}")
        ordered_indices = sorted(
            indices,
            key=(
                (lambda index: region_centers[index][0])
                if horizontal
                else (lambda index: -region_centers[index][1])
            ),
        )
        if cluster_rows[indices[0]][0] == "world":
            raise ValueError(f"duplicate remainder strategic name {base_name}")
        gender = outer_region_name_gender(cluster_rows[indices[0]][2])
        for index, qualifier in zip(ordered_indices, qualifiers_by_count[len(indices)]):
            display_names[index] = f"{qualifier[gender]} {base_name}"

    file_indices: Counter[str] = Counter()
    regions: list[Region] = []
    for region_id, ((_landmass, cluster, climate_key), base_name, display_name) in enumerate(
        zip(cluster_rows, base_names, display_names), 43
    ):
        slug, _old_name, climate = OUTER_REGION_SPECS[climate_key]
        file_indices[base_name] += 1
        file_suffix = "" if len(duplicate_groups[base_name]) == 1 else f"-{file_indices[base_name]}"
        regions.append(
            Region(
                region_id,
                slug + file_suffix,
                display_name,
                climate,
                tuple(sorted(cluster)),
            )
        )
    return tuple(regions)


REGIONS = (*BASE_REGIONS, *load_generated_outer_regions())


def format_provinces(provinces: set[int]) -> str:
    values = sorted(provinces)
    lines = []
    for start in range(0, len(values), 24):
        lines.append("\t\t" + " ".join(str(value) for value in values[start:start + 24]))
    return "\n".join(lines)


def format_weather(climate: str) -> str:
    lines = ["\tweather={"]
    for month, date_range in enumerate(MONTH_RANGES):
        low, high = TEMPERATURES[climate][month]
        clear, light, heavy, snow, blizzard, mud, sandstorm = phenomenon(climate, month)
        lines.extend((
            "\t\tperiod={",
            f"\t\t\tbetween={{ {date_range} }}",
            f"\t\t\ttemperature={{ {low:.1f} {high:.1f} }}",
            f"\t\t\tno_phenomenon={clear:.2f}",
            f"\t\t\train_light={light:.2f}",
            f"\t\t\train_heavy={heavy:.2f}",
            f"\t\t\tsnow={snow:.2f}",
            f"\t\t\tblizzard={blizzard:.2f}",
            f"\t\t\tarctic_water={arctic_water(climate, month):.2f}",
            f"\t\t\tmud={mud:.2f}",
            f"\t\t\tsandstorm={sandstorm:.2f}",
            f"\t\t\tmin_snow_level={minimum_snow_level(climate, month):.2f}",
            "\t\t}",
        ))
    lines.append("\t}")
    return "\n".join(lines)


def representative_positions(
    provinces: set[int],
    positions: dict[int, tuple[float, float, float]],
    adjacency: dict[int, set[int]] | None = None,
) -> list[tuple[float, float, float]]:
    available = [positions[province_id] for province_id in provinces if province_id in positions]
    if not available and adjacency is not None:
        # Non-state inland-water provinces have no unit-stack coordinates.
        # Place their weather marker on the immediately surrounding shore
        # instead of inventing a map coordinate or attaching distant land.
        shore = {
            neighbour
            for province_id in provinces
            for neighbour in adjacency.get(province_id, set())
            if neighbour in positions
        }
        available = [positions[province_id] for province_id in sorted(shore)]
    if not available:
        raise ValueError("strategic region has no unit-stack positions")
    if len(available) == 1:
        return available

    x_span = max(point[0] for point in available) - min(point[0] for point in available)
    z_span = max(point[2] for point in available) - min(point[2] for point in available)
    axis = 0 if x_span >= z_span else 2
    ordered = sorted(available, key=lambda point: point[axis])
    if len(available) < 24:
        return [ordered[len(ordered) // 2]]
    return [ordered[len(ordered) // 3], ordered[(2 * len(ordered)) // 3]]


def sea_region_id_for(position: tuple[float, float, float]) -> int:
    x, _height, z = position
    latitude_band = 0 if z >= 1600 else 1 if z >= 1250 else 2 if z >= 900 else 3 if z >= 550 else 4
    longitude_band = 0 if x < 1800 else 1 if x < 3800 else 2
    return SEA_REGION_GRID[latitude_band][longitude_band]


def validate_manifest(states: dict[int, set[int]]) -> None:
    assigned: dict[int, int] = {}
    for region in REGIONS:
        if region.climate not in TEMPERATURES:
            raise ValueError(f"region {region.region_id} uses unknown climate {region.climate}")
        for state_id in region.states:
            if state_id not in states:
                raise ValueError(f"region {region.region_id} references missing state {state_id}")
            if state_id in assigned:
                raise ValueError(f"state {state_id} is in regions {assigned[state_id]} and {region.region_id}")
            assigned[state_id] = region.region_id
    missing = sorted(set(states) - set(assigned))
    if missing:
        raise ValueError(f"states without a strategic region: {missing}")


def build() -> None:
    states = load_states()
    validate_manifest(states)
    province_types, color_to_province = load_province_definitions()
    non_sea = {province_id for province_id, province_type in province_types.items() if province_type != "sea"}
    sea = {province_id for province_id, province_type in province_types.items() if province_type == "sea"}
    state_provinces = set().union(*states.values())
    unknown = state_provinces - non_sea
    if unknown:
        raise ValueError(f"state provinces absent from non-sea definition rows: {sorted(unknown)}")

    for path in REGION_DIR.glob("*.txt"):
        text = path.read_text(encoding="utf-8-sig", errors="strict")
        if path.name in ("1-sea.txt", "2-land.txt") or text.startswith(GENERATED_MARKER):
            path.unlink()

    province_positions = load_province_positions()
    for province_id in sea:
        if province_id not in province_positions:
            raise ValueError(f"sea province {province_id} has no unit-stack position")

    adjacency = load_province_adjacency(province_types, color_to_province)
    sea_components = connected_components(sea, adjacency)
    if not sea_components:
        raise ValueError("map contains no sea provinces")
    main_ocean = sea_components[0]

    dedicated_union: set[int] = set()
    for region in DEDICATED_SEA_REGIONS:
        provinces = set(DEDICATED_SEA_PROVINCES[region.region_id])
        if provinces - sea:
            raise ValueError(
                f"dedicated sea region {region.region_id} contains non-sea provinces: {sorted(provinces - sea)}"
            )
        overlap = dedicated_union & provinces
        if overlap:
            raise ValueError(f"dedicated sea provinces assigned more than once: {sorted(overlap)}")
        if not provinces <= main_ocean:
            raise ValueError(
                f"dedicated sea region {region.region_id} must belong to the navigable ocean component"
            )
        if len(connected_components(provinces, adjacency)) != 1:
            raise ValueError(f"dedicated sea region {region.region_id} is not internally connected")
        dedicated_union.update(provinces)

    region_provinces: dict[int, set[int]] = {}
    land_region_by_province: dict[int, int] = {}
    for region in REGIONS:
        provinces = set().union(*(states[state_id] for state_id in region.states))
        if region.region_id == 2:
            provinces |= non_sea - state_provinces
        region_provinces[region.region_id] = provinces
        for province_id in provinces:
            land_region_by_province[province_id] = region.region_id

    for region_id, provinces in DEDICATED_SEA_PROVINCES.items():
        region_provinces[region_id] = set(provinces)

    # Inland lakes must belong to their surrounding land region. Combining them
    # with the ocean makes Clausewitz report a fractioned naval strategic region.
    for component in sea_components[1:]:
        neighbouring_land = Counter(
            land_region_by_province[neighbour]
            for province_id in component
            for neighbour in adjacency[province_id]
            if neighbour in land_region_by_province
        )
        if not neighbouring_land:
            raise ValueError(f"isolated sea component {sorted(component)} has no neighbouring land region")
        region_id = min(neighbouring_land, key=lambda candidate: (-neighbouring_land[candidate], candidate))
        region_provinces[region_id].update(component)

    # Partition the complete navigable ocean first, then cut the local basin out
    # of its macro region.  This keeps every unrelated ocean boundary stable.
    macro_partition = partition_connected_sea(main_ocean, adjacency, province_positions)
    for region_id, provinces in DEDICATED_SEA_PROVINCES.items():
        source_regions = {
            macro_region_id
            for macro_region_id, macro_provinces in macro_partition.items()
            if macro_provinces & set(provinces)
        }
        if len(source_regions) != 1:
            raise ValueError(
                f"dedicated sea region {region_id} crosses macro-ocean boundaries: {sorted(source_regions)}"
            )
        macro_partition[next(iter(source_regions))].difference_update(provinces)
    region_provinces.update(macro_partition)

    sea_by_id = {region.region_id: region for region in ALL_SEA_REGIONS}
    for region_id, region in sorted(sea_by_id.items()):
        provinces = region_provinces.get(region_id, set())
        if not provinces:
            raise ValueError(f"sea strategic region {region_id} is empty")
        content = (
            f"{GENERATED_MARKER}\n"
            "strategic_region={\n"
            f"\tid={region.region_id}\n"
            f"\tname=\"STRATEGICREGION_{region.region_id}\"\n"
            "\tprovinces={\n"
            f"{format_provinces(provinces)}\n"
            "\t}\n"
            f"\tnaval_terrain={region.naval_terrain}\n"
            f"{format_weather(region.climate)}\n"
            "}\n"
        )
        path = REGION_DIR / f"{region.region_id}-{region.slug}.txt"
        path.write_text(content, encoding="utf-8", newline="\n")

    for region in REGIONS:
        provinces = region_provinces[region.region_id]
        content = (
            f"{GENERATED_MARKER}\n"
            "strategic_region={\n"
            f"\tid={region.region_id}\n"
            f"\tname=\"STRATEGICREGION_{region.region_id}\"\n"
            "\tprovinces={\n"
            f"{format_provinces(provinces)}\n"
            "\t}\n"
            f"{format_weather(region.climate)}\n"
            "}\n"
        )
        path = REGION_DIR / f"{region.region_id}-{region.slug}.txt"
        path.write_text(content, encoding="utf-8", newline="\n")

    LOCALISATION.parent.mkdir(parents=True, exist_ok=True)
    localisation_lines = ["\ufeffl_russian:"]
    for region in sorted((*ALL_SEA_REGIONS, *REGIONS), key=lambda item: item.region_id):
        localisation_lines.append(f' STRATEGICREGION_{region.region_id}: "{region.russian_name}"')
    LOCALISATION.write_text("\n".join(localisation_lines) + "\n", encoding="utf-8", newline="\n")

    weather_lines = []
    for region_id in sorted(region_provinces):
        size = "big" if len(region_provinces[region_id]) >= 100 else "small"
        for x, height, z in representative_positions(
            region_provinces[region_id], province_positions, adjacency
        ):
            weather_lines.append(f"{region_id};{x:.2f};{height:.2f};{z:.2f};{size}")
    WEATHER_POSITIONS.write_text("\n".join(weather_lines) + "\n", encoding="utf-8", newline="\n")

    print(f"Built {len(REGIONS)} land and {len(ALL_SEA_REGIONS)} sea strategic regions for {len(states)} states.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate A-Discord strategic regions and weather positions.")
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true", help="validate current generated outputs (default)")
    actions.add_argument("--apply", action="store_true", help="write strategic regions, localisation and weather positions")
    args = parser.parse_args()
    if args.apply:
        build()
        return 0
    from tools.validators.validate_adiscord_strategic_regions import main as validate_main

    return validate_main()


if __name__ == "__main__":
    raise SystemExit(main())
