#!/usr/bin/env python3
"""Cut the unfinished northern/eastern and western landmasses into state shells.

The detailed southern/eastern state work (IDs 1-330) remains authoritative.
This pass only removes provinces from the catch-all state 23, creates neutral
state shells, and records a climate key for the strategic-region builder.

The split is deliberately asymmetric:

* the unfinished upper half of the right continent is medium-fine;
* the far north becomes progressively coarser;
* the main left continent receives a coarse provisional split;
* the separate far-eastern continent and minor western islands are untouched.

Run without ``--apply`` for a read-only summary.  Generated state files are
idempotent: a later run first folds the marked files back into the source pool.
"""

from __future__ import annotations

import argparse
import heapq
import math
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

from tools.builders.build_adiscord_map_buildings import synchronize_buildings
from tools.builders.build_adiscord_strategic_regions import (
    connected_components,
    load_province_adjacency,
    load_province_definitions,
    load_province_positions,
    outer_macro_bounds,
    outer_macro_toponym,
)
from tools.lib.paths import repository_root


ROOT = repository_root()
STATE_DIR = ROOT / "history" / "states"
LOCALISATION = ROOT / "localisation" / "russian" / "ADISCORD_outer_states_l_russian.yml"
GENERATED_MARKER = "# Generated by tools/build_adiscord_outer_states.py"
CLIMATE_MARKER = "# adiscord_climate_region = "
FIRST_STATE_ID = 331


@dataclass(frozen=True)
class ProvinceData:
    province_id: int
    x: float
    y: float
    height: float
    pixels: int
    terrain: str
    coastal: bool


@dataclass
class PlannedState:
    state_id: int
    landmass: str
    provinces: set[int]
    climate_region: str
    name: str


def state_path(state_id: int) -> Path:
    matches = sorted(STATE_DIR.glob(f"{state_id}-*.txt"))
    if len(matches) != 1:
        raise RuntimeError(f"state {state_id}: expected one file, found {len(matches)}")
    return matches[0]


def parse_state(path: Path) -> tuple[int, set[int], str]:
    source = path.read_text(encoding="utf-8-sig", errors="strict")
    state_match = re.search(r"\bid\s*=\s*(\d+)", source)
    province_match = re.search(r"\bprovinces\s*=\s*\{([^}]*)\}", source, re.DOTALL)
    if not state_match or not province_match:
        raise RuntimeError(f"{path.relative_to(ROOT)}: missing id or provinces block")
    return (
        int(state_match.group(1)),
        {int(value) for value in re.findall(r"\d+", province_match.group(1))},
        source,
    )


def load_source_pool() -> tuple[set[int], set[int], str, list[Path]]:
    outer_path = state_path(23)
    _state_id, outer_provinces, outer_source = parse_state(outer_path)
    generated_paths: list[Path] = []
    generated_provinces: set[int] = set()
    for path in sorted(STATE_DIR.glob("*.txt")):
        source = path.read_text(encoding="utf-8-sig", errors="strict")
        if not source.startswith(GENERATED_MARKER):
            continue
        state_id, provinces, _source = parse_state(path)
        if state_id < FIRST_STATE_ID:
            raise RuntimeError(f"generated marker is not allowed on legacy state {state_id}")
        overlap = generated_provinces & provinces
        if overlap:
            raise RuntimeError(f"generated states duplicate provinces {sorted(overlap)[:20]}")
        generated_provinces.update(provinces)
        generated_paths.append(path)
    overlap = outer_provinces & generated_provinces
    if overlap:
        raise RuntimeError(f"state 23 overlaps generated states at provinces {sorted(overlap)[:20]}")
    return outer_provinces | generated_provinces, outer_provinces, outer_source, generated_paths


def load_definition_details() -> tuple[dict[int, str], dict[int, bool]]:
    terrain: dict[int, str] = {}
    coastal: dict[int, bool] = {}
    for line in (ROOT / "map" / "definition.csv").read_text(encoding="utf-8-sig").splitlines():
        fields = line.split(";")
        if len(fields) < 7 or not fields[0].isdigit():
            continue
        province_id = int(fields[0])
        terrain[province_id] = fields[6]
        coastal[province_id] = fields[5].lower() == "true"
    return terrain, coastal


def load_pixel_areas(color_to_province: dict[int, int]) -> dict[int, int]:
    with Image.open(ROOT / "map" / "provinces.bmp") as source:
        image = source.convert("RGB")
        colors = image.getcolors(maxcolors=image.width * image.height)
    if colors is None:
        raise RuntimeError("could not enumerate province colours")
    areas: dict[int, int] = {}
    for count, (red, green, blue) in colors:
        color = (red << 16) | (green << 8) | blue
        province_id = color_to_province.get(color)
        if province_id is None:
            raise RuntimeError(f"provinces.bmp uses undefined colour {red};{green};{blue}")
        areas[province_id] = count
    return areas


def build_province_data(
    province_types: dict[int, str], color_to_province: dict[int, int]
) -> dict[int, ProvinceData]:
    positions = load_province_positions()
    areas = load_pixel_areas(color_to_province)
    terrain, coastal = load_definition_details()
    data: dict[int, ProvinceData] = {}
    for province_id, province_type in province_types.items():
        if province_type != "land":
            continue
        if province_id not in positions or province_id not in areas:
            raise RuntimeError(f"land province {province_id} lacks a map position or pixel area")
        x, height, z = positions[province_id]
        data[province_id] = ProvinceData(
            province_id=province_id,
            x=x,
            y=2048.0 - z,
            height=height,
            pixels=areas[province_id],
            terrain=terrain.get(province_id, "plains"),
            coastal=coastal.get(province_id, False),
        )
    return data


def component_center(component: set[int], data: dict[int, ProvinceData]) -> tuple[float, float]:
    total = sum(data[province_id].pixels for province_id in component)
    return (
        sum(data[province_id].x * data[province_id].pixels for province_id in component) / total,
        sum(data[province_id].y * data[province_id].pixels for province_id in component) / total,
    )


def select_landmasses(
    pool: set[int], adjacency: dict[int, set[int]], data: dict[int, ProvinceData]
) -> tuple[set[int], set[int], list[set[int]]]:
    land_pool = set(pool) & set(data)
    components = connected_components(land_pool, adjacency)

    left_candidates = [
        component
        for component in components
        if len(component) >= 5000 and component_center(component, data)[0] < 2900
    ]
    if len(left_candidates) != 1:
        raise RuntimeError(f"expected one coarse left-continent component, found {len(left_candidates)}")
    left = left_candidates[0]

    right_components: list[set[int]] = []
    for component in components:
        center_x, center_y = component_center(component, data)
        if component is left:
            continue
        if len(component) >= 300 and 2900 <= center_x < 4800 and center_y < 1200:
            right_components.append(component)
            continue
        # Nearby islands belong to the northern right-continent archipelagos.
        if len(component) < 300 and 2800 <= center_x < 4700 and center_y < 1100:
            right_components.append(component)

    right = set().union(*right_components) if right_components else set()
    if len(right) < 2500:
        raise RuntimeError(f"right-continent selection is unexpectedly small: {len(right)} provinces")
    return left, right, right_components


def target_pixels(landmass: str, y: float) -> float:
    if landmass == "right":
        if y < 280:
            return 18_000.0
        if y < 520:
            return 9_000.0
        if y < 760:
            return 5_000.0
        return 3_500.0
    if y < 300:
        return 50_000.0
    if y < 650:
        return 35_000.0
    if y < 1050:
        return 25_000.0
    if y < 1450:
        return 18_000.0
    return 14_000.0


def province_mass(landmass: str, province: ProvinceData) -> float:
    return province.pixels / target_pixels(landmass, province.y)


def principal_axis(nodes: set[int], data: dict[int, ProvinceData]) -> str:
    xs = [data[province_id].x for province_id in nodes]
    ys = [data[province_id].y for province_id in nodes]
    return "x" if max(xs) - min(xs) >= max(ys) - min(ys) else "y"


def edge_cost(first: int, second: int, data: dict[int, ProvinceData], scale: float) -> float:
    a, b = data[first], data[second]
    distance = math.hypot(a.x - b.x, a.y - b.y) / max(scale, 1.0)
    terrain_penalty = 0.10 if a.terrain != b.terrain else 0.0
    height_penalty = min(abs(a.height - b.height) / 20.0, 0.18)
    return 0.05 + distance + terrain_penalty + height_penalty


def bisect_connected(
    nodes: set[int],
    left_parts: int,
    total_parts: int,
    landmass: str,
    adjacency: dict[int, set[int]],
    data: dict[int, ProvinceData],
) -> tuple[set[int], set[int]]:
    axis = principal_axis(nodes, data)
    key = (lambda province_id: (data[province_id].x, data[province_id].y, province_id)) if axis == "x" else (
        lambda province_id: (data[province_id].y, data[province_id].x, province_id)
    )
    seed_a = min(nodes, key=key)
    seed_b = max(nodes, key=key)
    if seed_a == seed_b:
        raise RuntimeError("cannot bisect a one-province component")

    mass = {province_id: province_mass(landmass, data[province_id]) for province_id in nodes}
    total_mass = sum(mass.values())
    target_a = total_mass * left_parts / total_parts
    target_b = total_mass - target_a
    groups = ({seed_a}, {seed_b})
    group_mass = [mass[seed_a], mass[seed_b]]
    assigned = {seed_a: 0, seed_b: 1}
    spans = (
        max(data[province_id].x for province_id in nodes) - min(data[province_id].x for province_id in nodes),
        max(data[province_id].y for province_id in nodes) - min(data[province_id].y for province_id in nodes),
    )
    scale = max(spans)
    frontiers: list[list[tuple[float, int, int]]] = [[], []]

    def push_neighbours(side: int, province_id: int, base_cost: float) -> None:
        for neighbour in adjacency[province_id]:
            if neighbour not in nodes or neighbour in assigned:
                continue
            heapq.heappush(
                frontiers[side],
                (base_cost + edge_cost(province_id, neighbour, data, scale), neighbour, province_id),
            )

    push_neighbours(0, seed_a, 0.0)
    push_neighbours(1, seed_b, 0.0)
    remaining = len(nodes) - 2
    while remaining:
        ratios = (group_mass[0] / max(target_a, 1e-9), group_mass[1] / max(target_b, 1e-9))
        preferred = 0 if ratios[0] <= ratios[1] else 1
        chosen: tuple[float, int, int] | None = None
        side = preferred
        for candidate_side in (preferred, 1 - preferred):
            while frontiers[candidate_side] and frontiers[candidate_side][0][1] in assigned:
                heapq.heappop(frontiers[candidate_side])
            if frontiers[candidate_side]:
                side = candidate_side
                chosen = heapq.heappop(frontiers[candidate_side])
                break
        if chosen is None:
            raise RuntimeError("connected split exhausted both frontiers")
        cost, province_id, _parent = chosen
        if province_id in assigned:
            continue
        assigned[province_id] = side
        groups[side].add(province_id)
        group_mass[side] += mass[province_id]
        remaining -= 1
        push_neighbours(side, province_id, cost)

    if len(groups[0]) < left_parts or len(groups[1]) < total_parts - left_parts:
        raise RuntimeError(
            f"unbalanced graph split cannot support {left_parts}+{total_parts-left_parts} parts: "
            f"{len(groups[0])}+{len(groups[1])} provinces"
        )
    return groups


def partition_connected(
    nodes: set[int],
    parts: int,
    landmass: str,
    adjacency: dict[int, set[int]],
    data: dict[int, ProvinceData],
) -> list[set[int]]:
    if parts <= 1:
        return [set(nodes)]
    left_parts = parts // 2
    first, second = bisect_connected(nodes, left_parts, parts, landmass, adjacency, data)
    return (
        partition_connected(first, left_parts, landmass, adjacency, data)
        + partition_connected(second, parts - left_parts, landmass, adjacency, data)
    )


def partition_disconnected(
    components: list[set[int]], landmass: str, data: dict[int, ProvinceData]
) -> list[set[int]]:
    if not components:
        return []
    items = []
    for component in components:
        center_x, center_y = component_center(component, data)
        mass = sum(province_mass(landmass, data[province_id]) for province_id in component)
        items.append((component, center_x, center_y, mass))
    parts = max(1, round(sum(item[3] for item in items)))
    parts = min(parts, len(items))

    def split(group: list[tuple[set[int], float, float, float]], count: int) -> list[list[tuple[set[int], float, float, float]]]:
        if count <= 1:
            return [group]
        x_span = max(item[1] for item in group) - min(item[1] for item in group)
        y_span = max(item[2] for item in group) - min(item[2] for item in group)
        axis = 1 if x_span >= y_span else 2
        ordered = sorted(group, key=lambda item: (item[axis], item[2 if axis == 1 else 1], min(item[0])))
        left_count = count // 2
        target = sum(item[3] for item in ordered) * left_count / count
        running = 0.0
        cut = 1
        best = float("inf")
        for index in range(1, len(ordered)):
            running += ordered[index - 1][3]
            difference = abs(running - target)
            if difference < best and index >= left_count and len(ordered) - index >= count - left_count:
                best = difference
                cut = index
        return split(ordered[:cut], left_count) + split(ordered[cut:], count - left_count)

    return [set().union(*(item[0] for item in group)) for group in split(items, parts)]


def plan_clusters(
    left: set[int],
    right_components: list[set[int]],
    adjacency: dict[int, set[int]],
    data: dict[int, ProvinceData],
) -> list[tuple[str, set[int]]]:
    clusters: list[tuple[str, set[int]]] = []

    left_parts = max(1, round(sum(province_mass("left", data[p]) for p in left)))
    left_parts = min(left_parts, max(1, len(left) // 18))
    clusters.extend(("left", group) for group in partition_connected(left, left_parts, "left", adjacency, data))

    mainland = [component for component in right_components if len(component) >= 100]
    islands = [component for component in right_components if len(component) < 100]
    for component in mainland:
        parts = max(1, round(sum(province_mass("right", data[p]) for p in component)))
        parts = min(parts, max(1, len(component) // 4))
        clusters.extend(("right", group) for group in partition_connected(component, parts, "right", adjacency, data))
    clusters.extend(("right", group) for group in partition_disconnected(islands, "right", data))
    return merge_small_clusters(clusters, adjacency, data)


def merge_small_clusters(
    clusters: list[tuple[str, set[int]]],
    adjacency: dict[int, set[int]],
    data: dict[int, ProvinceData],
) -> list[tuple[str, set[int]]]:
    """Absorb accidental slivers into a neighbour or the nearest island group."""
    working = [(landmass, set(provinces)) for landmass, provinces in clusters]
    while True:
        masses = [
            sum(province_mass(landmass, data[province_id]) for province_id in provinces)
            for landmass, provinces in working
        ]
        candidates = [index for index, mass in enumerate(masses) if mass < 0.45]
        if not candidates:
            break
        source_index = min(candidates, key=lambda index: (masses[index], min(working[index][1])))
        landmass, source = working[source_index]
        source_x, source_y = component_center(source, data)
        choices: list[tuple[int, float, float, int]] = []
        for target_index, (target_landmass, target) in enumerate(working):
            if target_index == source_index or target_landmass != landmass:
                continue
            shared_edges = sum(1 for province_id in source for neighbour in adjacency[province_id] if neighbour in target)
            target_x, target_y = component_center(target, data)
            distance = math.hypot(source_x - target_x, source_y - target_y)
            combined_mass = masses[source_index] + masses[target_index]
            choices.append((-shared_edges, distance, combined_mass, target_index))
        if not choices:
            break
        _shared, _distance, _combined, target_index = min(choices)
        working[target_index][1].update(source)
        del working[source_index]
    return working


def cluster_statistics(provinces: set[int], data: dict[int, ProvinceData]) -> dict[str, object]:
    total_pixels = sum(data[p].pixels for p in provinces)
    x = sum(data[p].x * data[p].pixels for p in provinces) / total_pixels
    y = sum(data[p].y * data[p].pixels for p in provinces) / total_pixels
    average_height = sum(data[p].height * data[p].pixels for p in provinces) / total_pixels
    terrain_pixels: Counter[str] = Counter()
    coastal_pixels = 0
    for province_id in provinces:
        province = data[province_id]
        terrain_pixels[province.terrain] += province.pixels
        if province.coastal:
            coastal_pixels += province.pixels
    dominant = terrain_pixels.most_common(1)[0][0]
    highland_share = sum(terrain_pixels[name] for name in ("hills", "mountain")) / total_pixels
    wet_share = sum(terrain_pixels[name] for name in ("forest", "marsh")) / total_pixels
    return {
        "pixels": total_pixels,
        "x": x,
        "y": y,
        "height": average_height,
        "dominant": dominant,
        "highland_share": highland_share,
        "wet_share": wet_share,
        "coastal_share": coastal_pixels / total_pixels,
    }


def climate_region(landmass: str, stats: dict[str, object]) -> str:
    y = float(stats["y"])
    highland = float(stats["highland_share"]) >= 0.42 or float(stats["height"]) >= 13.5
    maritime = float(stats["coastal_share"]) >= 0.35
    wet = float(stats["wet_share"]) >= 0.52

    if landmass == "right":
        if y < 300:
            return "right_polar"
        if y < 520:
            if highland:
                return "right_cold_highlands"
            return "right_subarctic_maritime" if maritime else "right_subarctic_continental"
        if y < 780:
            if highland:
                return "right_cool_highlands"
            if maritime:
                return "right_cool_maritime"
            return "right_boreal_wet" if wet else "right_cool_continental"
        if highland:
            return "right_temperate_highlands"
        return "right_temperate_wet" if wet else "right_temperate_continental"

    if y < 300:
        return "left_polar"
    if y < 650:
        if highland:
            return "left_cold_highlands"
        return "left_subarctic_maritime" if maritime else "left_subarctic_continental"
    if y < 900:
        if highland:
            return "left_cool_highlands"
        return "left_cool_maritime" if maritime else "left_cool_continental"
    if y < 1550:
        if highland:
            return "left_temperate_highlands"
        return "left_temperate_wet" if wet else "left_temperate_continental"
    return "left_southern_coast" if maritime else "left_warm_interior"


DIRECTION_FORMS = {
    (0, 0): ("Северо-западный", "Северо-западная", "Северо-западное", "Северо-западные"),
    (0, 1): ("Северный", "Северная", "Северное", "Северные"),
    (0, 2): ("Северо-восточный", "Северо-восточная", "Северо-восточное", "Северо-восточные"),
    (1, 0): ("Западный", "Западная", "Западное", "Западные"),
    (1, 1): ("Центральный", "Центральная", "Центральное", "Центральные"),
    (1, 2): ("Восточный", "Восточная", "Восточное", "Восточные"),
    (2, 0): ("Юго-западный", "Юго-западная", "Юго-западное", "Юго-западные"),
    (2, 1): ("Южный", "Южная", "Южное", "Южные"),
    (2, 2): ("Юго-восточный", "Юго-восточная", "Юго-восточное", "Юго-восточные"),
}


def state_name_parts(
    climate_key: str, provinces: set[int], data: dict[int, ProvinceData]
) -> tuple[str, int, str]:
    stats = cluster_statistics(provinces, data)
    dominant = str(stats["dominant"])
    x = float(stats["x"])
    y = float(stats["y"])
    x_min, x_max, y_min, y_max = outer_macro_bounds(climate_key, x)
    row = min(2, max(0, int(3.0 * (y - y_min) / max(1.0, y_max - y_min))))
    column = min(2, max(0, int(3.0 * (x - x_min) / max(1.0, x_max - x_min))))
    direction = DIRECTION_FORMS[(row, column)]
    _root, topo_masculine, topo_feminine, topo_neuter, topo_plural = outer_macro_toponym(climate_key, x)

    if float(stats["coastal_share"]) >= 0.70:
        gender, feature, base_name = 3, "острова", f"{topo_plural} острова"
    elif dominant == "mountain" or float(stats["highland_share"]) >= 0.55:
        gender, feature, base_name = 2, "нагорье", f"{topo_neuter} нагорье"
    elif dominant == "hills":
        gender, feature, base_name = 3, "холмы", f"{topo_plural} холмы"
    elif dominant == "forest":
        gender, feature, base_name = 3, "леса", f"{topo_plural} леса"
    elif dominant == "marsh":
        gender, feature, base_name = 3, "топи", f"{topo_plural} топи"
    elif float(stats["coastal_share"]) >= 0.35:
        gender, feature, base_name = 2, "побережье", f"{topo_neuter} побережье"
    elif dominant == "plains":
        gender, feature, base_name = 1, "равнина", f"{topo_feminine} равнина"
    else:
        gender, feature, base_name = 0, "край", f"{topo_masculine} край"

    if (row, column) == (1, 1):
        return base_name, gender, feature
    return f"{direction[gender]} {base_name}", gender, feature


LOCAL_TOPONYM_ROOTS = (
    "Аверн", "Альдор", "Арвек", "Белран", "Борден", "Бревар", "Вельтар", "Гарлен",
    "Гевран", "Гольден", "Дарвен", "Дельвар", "Дорген", "Эльвар", "Эрден", "Жаврен",
    "Зеллар", "Зорвен", "Иверан", "Ильден", "Каврен", "Келлан", "Кердор", "Лаврен",
    "Левард", "Лирвен", "Лорден", "Маверн", "Мейдар", "Мелран", "Невард", "Нелвен",
    "Нордар", "Ольвен", "Орлан", "Пелдар", "Перван", "Равден", "Рейвен", "Рендар",
    "Салвен", "Севард", "Селлан", "Таврен", "Таллер", "Тейвар", "Терлан", "Ульвар",
    "Фаллен", "Фейвар", "Хеллан", "Целвар", "Черден", "Шаврен", "Шелдар", "Эвард",
    "Эльден", "Ярвен", "Альвер", "Бердан", "Веглар", "Гальвен", "Дейран", "Зейлар",
    "Кольвен", "Марден", "Найвен", "Пейлар", "Росвен", "Сайдар", "Тейрен", "Фольвар",
    "Хейден", "Эймар", "Ялден", "Бейвар", "Гельден", "Дальвен", "Кейлар", "Мордан",
)


def local_toponym_forms(root: str) -> tuple[str, str, str, str]:
    return root + "ский", root + "ская", root + "ское", root + "ские"


def assign_ids_and_metadata(
    clusters: list[tuple[str, set[int]]], data: dict[int, ProvinceData]
) -> list[PlannedState]:
    ordered = sorted(
        clusters,
        key=lambda item: (
            0 if item[0] == "right" else 1,
            cluster_statistics(item[1], data)["y"],
            cluster_statistics(item[1], data)["x"],
            min(item[1]),
        ),
    )
    statistics = [cluster_statistics(provinces, data) for _landmass, provinces in ordered]
    climate_keys = [
        climate_region(landmass, stats)
        for (landmass, _provinces), stats in zip(ordered, statistics)
    ]
    name_parts = [
        state_name_parts(climate_key, provinces, data)
        for (_landmass, provinces), climate_key in zip(ordered, climate_keys)
    ]
    base_names = [parts[0] for parts in name_parts]
    name_totals = Counter(base_names)
    local_toponym_index = 0
    planned: list[PlannedState] = []
    for index, ((landmass, provinces), stats, climate_key, parts) in enumerate(
        zip(ordered, statistics, climate_keys, name_parts)
    ):
        state_id = FIRST_STATE_ID + index
        base_name, gender, feature = parts
        if name_totals[base_name] == 1:
            name = base_name
        else:
            if local_toponym_index >= len(LOCAL_TOPONYM_ROOTS):
                raise RuntimeError("not enough local toponyms to disambiguate generated state names")
            forms = local_toponym_forms(LOCAL_TOPONYM_ROOTS[local_toponym_index])
            local_toponym_index += 1
            name = f"{forms[gender]} {feature}"
        planned.append(
            PlannedState(
                state_id=state_id,
                landmass=landmass,
                provinces=provinces,
                climate_region=climate_key,
                name=name,
            )
        )
    return planned


def format_provinces(provinces: set[int], indent: str = "\t\t", width: int = 16) -> str:
    values = sorted(provinces)
    return "\n".join(
        indent + " ".join(str(value) for value in values[start:start + width])
        for start in range(0, len(values), width)
    )


def render_state(state: PlannedState, data: dict[int, ProvinceData]) -> str:
    stats = cluster_statistics(state.provinces, data)
    category = "wasteland" if float(stats["y"]) < 300 or float(stats["highland_share"]) >= 0.70 else "rural"
    return (
        f"{GENERATED_MARKER}\n"
        f"{CLIMATE_MARKER}{state.climate_region}\n"
        "state = {\n"
        f"\tid = {state.state_id}\n"
        f'\tname = "STATE_{state.state_id}"\n'
        "\tmanpower = 1\n"
        f"\tstate_category = {category}\n"
        "\tprovinces = {\n"
        f"{format_provinces(state.provinces)}\n"
        "\t}\n"
        "\tbuildings_max_level_factor = 1.000\n"
        "\tlocal_supplies = 0.0\n"
        "}\n"
    )


def replace_outer_provinces(source: str, provinces: set[int]) -> str:
    match = re.search(r"\bprovinces\s*=\s*\{([^}]*)\}", source, re.DOTALL)
    if not match:
        raise RuntimeError("state 23: missing provinces block")
    replacement = "provinces={\n" + format_provinces(provinces, indent="\t\t", width=24) + "\n\t}"
    return source[:match.start()] + replacement + source[match.end():]


def validate_plan(
    planned: list[PlannedState], source_pool: set[int], left: set[int], right: set[int]
) -> None:
    expected = left | right
    assigned: set[int] = set()
    for state in planned:
        if not state.provinces:
            raise RuntimeError(f"state {state.state_id} is empty")
        overlap = assigned & state.provinces
        if overlap:
            raise RuntimeError(f"new states duplicate provinces {sorted(overlap)[:20]}")
        assigned.update(state.provinces)
    if assigned != expected:
        raise RuntimeError(
            f"planned coverage mismatch: missing {len(expected-assigned)}, unexpected {len(assigned-expected)}"
        )
    if not assigned <= source_pool:
        raise RuntimeError("planned states use provinces outside state 23/generated source pool")


def print_summary(planned: list[PlannedState], data: dict[int, ProvinceData]) -> None:
    by_landmass = Counter(state.landmass for state in planned)
    by_climate = Counter(state.climate_region for state in planned)
    print(f"Planned {len(planned)} states: {dict(sorted(by_landmass.items()))}")
    print("Climate groups:")
    for climate, count in sorted(by_climate.items()):
        print(f"- {climate}: {count}")
    for landmass in ("right", "left"):
        rows = [cluster_statistics(state.provinces, data) | {"provinces": len(state.provinces)} for state in planned if state.landmass == landmass]
        province_counts = sorted(int(row["provinces"]) for row in rows)
        pixel_counts = sorted(int(row["pixels"]) for row in rows)
        if rows:
            middle = len(rows) // 2
            print(
                f"{landmass}: provinces median={province_counts[middle]}, range={province_counts[0]}..{province_counts[-1]}; "
                f"pixels median={pixel_counts[middle]}, range={pixel_counts[0]}..{pixel_counts[-1]}"
            )


def apply_plan(
    planned: list[PlannedState],
    data: dict[int, ProvinceData],
    original_outer: set[int],
    outer_source: str,
    generated_paths: list[Path],
) -> None:
    generated_provinces = set().union(*(state.provinces for state in planned))
    remaining_outer = (original_outer | set().union(*(parse_state(path)[1] for path in generated_paths))) - generated_provinces
    if not remaining_outer:
        raise RuntimeError("state 23 would become empty")

    # All destructive targets are explicitly marked generated files inside the
    # state directory; legacy/manual state files are never removed.
    for path in generated_paths:
        path.unlink()
    state_path(23).write_text(replace_outer_provinces(outer_source, remaining_outer), encoding="utf-8", newline="\n")
    for state in planned:
        path = STATE_DIR / f"{state.state_id}-outer-{state.landmass}.txt"
        path.write_text(render_state(state, data), encoding="utf-8", newline="\n")

    localisation = ["\ufeffl_russian:"]
    localisation.extend(f' STATE_{state.state_id}: "{state.name}"' for state in planned)
    LOCALISATION.write_text("\n".join(localisation) + "\n", encoding="utf-8", newline="\n")
    print(f"Applied {len(planned)} generated state shells; state 23 now keeps {len(remaining_outer)} provinces.")
    print("Run tools/build_adiscord_northern_countries.py --apply next to restore northern owners and balance data.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write generated state files and localisation")
    args = parser.parse_args()

    source_pool, original_outer, outer_source, generated_paths = load_source_pool()
    province_types, color_to_province = load_province_definitions()
    data = build_province_data(province_types, color_to_province)
    adjacency = load_province_adjacency(province_types, color_to_province)
    left, right, right_components = select_landmasses(source_pool, adjacency, data)
    clusters = plan_clusters(left, right_components, adjacency, data)
    planned = assign_ids_and_metadata(clusters, data)
    validate_plan(planned, source_pool, left, right)
    print_summary(planned, data)
    if args.apply:
        apply_plan(planned, data, original_outer, outer_source, generated_paths)
        mismatches = synchronize_buildings(ROOT, apply=True)
        print(f"Synchronized {len(mismatches)} map-building state assignments.")
    else:
        print("Dry run only; pass --apply to write files.")


if __name__ == "__main__":
    main()
