"""Additional dated technologies for A-Discord combat branches."""

EXPANSIONS: dict[str, dict[int, tuple[str, str, str, str]]] = {
    "artillery": {
        2150: ("electrohydraulic_gun_laying", "Электрогидравлическое наведение орудий", "Electrohydraulic Gun Laying", "artillery1"),
        2162: ("solid_state_ballistic_computers", "Твердотельные баллистические вычислители", "Solid-state Ballistic Computers", "artillery2"),
        2164: ("counterbattery_radar_links", "Каналы контрбатарейных РЛС", "Counter-battery Radar Links", "artillery3"),
        2166: ("modular_propellant_charges", "Модульные метательные заряды", "Modular Propellant Charges", "artillery4"),
        2168: ("inertial_battery_survey", "Инерциальная топопривязка батарей", "Inertial Battery Survey", "artillery5"),
        2173: ("course_correcting_fuzes", "Взрыватели коррекции траектории", "Course-correcting Fuzes", "rocket_artillery2"),
        2176: ("multispectral_spotter_drones", "Мультиспектральные дроны-корректировщики", "Multispectral Spotter Drones", "rocket_artillery4"),
        2179: ("robotic_shell_handling", "Роботизированная подача снарядов", "Robotic Shell Handling", "artillery2"),
        2185: ("distributed_counterbattery_mesh", "Распределённая контрбатарейная сеть", "Distributed Counter-battery Mesh", "artillery3"),
        2188: ("loitering_artillery_observers", "Барражирующие артиллерийские наблюдатели", "Loitering Artillery Observers", "artillery4"),
        2191: ("electromagnetic_recoil_brakes", "Электромагнитные тормоза отката", "Electromagnetic Recoil Brakes", "artillery5"),
        2194: ("predictive_fire_mission_control", "Предиктивное управление огневыми задачами", "Predictive Fire-mission Control", "rocket_artillery2"),
        2197: ("uncrewed_howitzer_sections", "Необитаемые гаубичные расчёты", "Uncrewed Howitzer Sections", "rocket_artillery4"),
    },
    "anti_tank": {
        2150: ("active_protection_defeat_probes", "Датчики преодоления активной защиты", "Active-protection Defeat Probes", "antitank1"),
        2162: ("stabilized_missile_launchers", "Стабилизированные ракетные пусковые установки", "Stabilized Missile Launchers", "antitank2"),
        2164: ("imaging_infrared_seekers", "Матричные инфракрасные головки наведения", "Imaging Infrared Seekers", "antitank3"),
        2166: ("overflight_attack_sensors", "Датчики атаки на пролёте", "Overflight-attack Sensors", "antitank4"),
        2168: ("hunter_killer_team_datalinks", "Каналы связи противотанковых групп", "Hunter-killer Team Datalinks", "antitank5"),
        2173: ("multispectral_armor_classifiers", "Мультиспектральные классификаторы брони", "Multispectral Armor Classifiers", "generic_railway_gun"),
        2176: ("loitering_anti_armor_munitions", "Барражирующие противоброневые боеприпасы", "Loitering Anti-armor Munitions", "generic_super_heavy_railway_gun"),
        2179: ("distributed_missile_ambush_nodes", "Распределённые узлы ракетных засад", "Distributed Missile-ambush Nodes", "antitank2"),
        2185: ("superconducting_coil_barrels", "Сверхпроводящие катушечные стволы", "Superconducting Coil Barrels", "antitank3"),
        2188: ("guided_hypervelocity_penetrators", "Управляемые гиперскоростные пенетраторы", "Guided Hypervelocity Penetrators", "antitank4"),
        2191: ("camouflage_defeat_radar", "РЛС распознавания активной маскировки", "Camouflage-defeat Radar", "antitank5"),
        2194: ("autonomous_anti_armor_sentries", "Автономные противоброневые посты", "Autonomous Anti-armor Sentries", "generic_railway_gun"),
        2197: ("predictive_armor_route_interdiction", "Предиктивное блокирование маршрутов бронетехники", "Predictive Armor-route Interdiction", "generic_super_heavy_railway_gun"),
    },
    "anti_air": {
        2150: ("stabilized_autocannon_mounts", "Стабилизированные зенитные автопушки", "Stabilized Autocannon Mounts", "antiair1"),
        2162: ("solid_state_air_search_radar", "Твердотельные РЛС воздушного поиска", "Solid-state Air-search Radar", "antiair2"),
        2164: ("programmable_airburst_shells", "Программируемые снаряды воздушного подрыва", "Programmable Airburst Shells", "antiair3"),
        2166: ("infrared_search_track_arrays", "Массивы инфракрасного поиска и сопровождения", "Infrared Search-and-track Arrays", "antiair4"),
        2168: ("integrated_short_range_missile_cells", "Интегрированные ячейки ракет ближнего действия", "Integrated Short-range Missile Cells", "antiair5"),
        2173: ("multispectral_drone_classifiers", "Мультиспектральные классификаторы дронов", "Multispectral Drone Classifiers", "generic_super_heavy_railway_gun"),
        2176: ("counter_uas_microwave_emitters", "СВЧ-излучатели против беспилотников", "Counter-UAS Microwave Emitters", "sp_nuclear_isotope_separation"),
        2179: ("cooperative_engagement_links", "Каналы совместного поражения целей", "Cooperative Engagement Links", "antiair2"),
        2185: ("rail_accelerated_interceptors", "Рельсовые зенитные перехватчики", "Rail-accelerated Interceptors", "antiair3"),
        2188: ("adaptive_laser_beam_directors", "Адаптивные системы наведения лазера", "Adaptive Laser Beam Directors", "antiair4"),
        2191: ("high_energy_laser_turrets", "Турели высокоэнергетических лазеров", "High-energy Laser Turrets", "antiair5"),
        2194: ("autonomous_interceptor_swarms", "Автономные рои перехватчиков", "Autonomous Interceptor Swarms", "generic_super_heavy_railway_gun"),
        2197: ("predictive_airspace_denial_grid", "Предиктивная сеть блокирования воздушного пространства", "Predictive Airspace-denial Grid", "sp_nuclear_isotope_separation"),
    },
    "recon_armor": {
        2150: ("sealed_electric_scout_drives", "Герметичные электроприводы разведмашин", "Sealed Electric Scout Drives", "gwtank"),
        2162: ("retractable_sensor_masts", "Выдвижные сенсорные мачты", "Retractable Sensor Masts", "basic_light_tank"),
        2164: ("hybrid_silent_running", "Гибридный малошумный ход", "Hybrid Silent Running", "improved_light_tank"),
        2166: ("multispectral_recon_suites", "Мультиспектральные разведывательные комплексы", "Multispectral Reconnaissance Suites", "advanced_light_tank"),
        2168: ("terrain_mapping_suspension", "Подвеска картирования рельефа", "Terrain-mapping Suspension", "recon"),
        2173: ("deployable_microdrone_racks", "Кассеты развёртываемых микродронов", "Deployable Microdrone Racks", "ger_armored_car_equipment_1"),
        2176: ("terrain_following_autopilots", "Автопилоты следования рельефу", "Terrain-following Autopilots", "ger_armored_car_equipment_3"),
        2179: ("signature_management_skins", "Обшивка управления сигнатурой", "Signature-management Skins", "basic_light_tank"),
        2185: ("unmanned_scout_turrets", "Необитаемые разведывательные башни", "Unmanned Scout Turrets", "improved_light_tank"),
        2188: ("cooperative_mapping_relays", "Ретрансляторы совместного картирования", "Cooperative Mapping Relays", "advanced_light_tank"),
        2191: ("expendable_sensor_carriers", "Расходуемые носители сенсоров", "Expendable Sensor Carriers", "recon"),
        2194: ("autonomous_route_clearance_scouts", "Автономные разведчики расчистки маршрутов", "Autonomous Route-clearance Scouts", "ger_armored_car_equipment_1"),
        2197: ("self_organizing_scout_formations", "Самоорганизующиеся разведывательные порядки", "Self-organizing Scout Formations", "ger_armored_car_equipment_3"),
    },
    "combat_armor": {
        2150: ("electric_turret_drives", "Электрические приводы башни", "Electric Turret Drives", "basic_medium_tank"),
        2162: ("digital_fire_control_buses", "Цифровые шины управления огнём", "Digital Fire-control Buses", "improved_medium_tank"),
        2164: ("hard_kill_protection_arrays", "Комплексы активной защиты жёсткого поражения", "Hard-kill Protection Arrays", "advanced_medium_tank"),
        2166: ("modular_ceramic_armor_blocks", "Модульные керамические бронеблоки", "Modular Ceramic Armor Blocks", "generic_modern_tank"),
        2168: ("distributed_crew_stations", "Распределённые рабочие места экипажа", "Distributed Crew Stations", "generic_modern_tank"),
        2173: ("multispectral_gunner_sights", "Мультиспектральные прицелы наводчика", "Multispectral Gunner Sights", "generic_modern_tank"),
        2176: ("unmanned_turret_capsules", "Необитаемые башенные капсулы", "Unmanned Turret Capsules", "generic_modern_tank"),
        2179: ("armored_platoon_target_handoff", "Передача целей внутри броневзвода", "Armored-platoon Target Handoff", "improved_medium_tank"),
        2185: ("adaptive_suspension_control", "Адаптивное управление подвеской", "Adaptive Suspension Control", "advanced_medium_tank"),
        2188: ("electromagnetic_main_guns", "Электромагнитные основные орудия", "Electromagnetic Main Guns", "generic_modern_tank"),
        2191: ("self_healing_armor_matrices", "Самовосстанавливающиеся броневые матрицы", "Self-healing Armor Matrices", "generic_modern_tank"),
        2194: ("autonomous_platoon_control", "Автономное управление броневзводом", "Autonomous Platoon Control", "generic_modern_tank"),
        2197: ("resilient_combat_cloud_nodes", "Защищённые узлы боевого облака", "Resilient Combat-cloud Nodes", "generic_modern_tank"),
    },
    "heavy_armor": {
        2150: ("hydropneumatic_load_equalizers", "Гидропневматические выравниватели нагрузки", "Hydropneumatic Load Equalizers", "basic_heavy_tank"),
        2162: ("compact_turbine_powerpacks", "Компактные турбинные силовые блоки", "Compact Turbine Powerpacks", "improved_heavy_tank"),
        2164: ("spall_isolated_crew_citadels", "Изолированные от осколков экипажные цитадели", "Spall-isolated Crew Citadels", "advanced_heavy_tank"),
        2166: ("modular_heavy_armor_cassettes", "Модульные кассеты тяжёлой брони", "Modular Heavy-armor Cassettes", "tech_maintenance_company"),
        2168: ("robotic_recovery_booms", "Роботизированные эвакуационные стрелы", "Robotic Recovery Booms", "super_heavy_tank"),
        2173: ("active_mass_balancing_suspension", "Подвеска активного распределения массы", "Active Mass-balancing Suspension", "main_battle_tank"),
        2176: ("remote_breaching_manipulators", "Дистанционные штурмовые манипуляторы", "Remote Breaching Manipulators", "generic_land_cruiser_chassis"),
        2179: ("distributed_hull_power_buses", "Распределённые силовые шины корпуса", "Distributed Hull-power Buses", "improved_heavy_tank"),
        2185: ("hybrid_siege_powerplants", "Гибридные силовые установки осадных машин", "Hybrid Siege Powerplants", "advanced_heavy_tank"),
        2188: ("electromagnetic_siege_mortars", "Электромагнитные осадные мортиры", "Electromagnetic Siege Mortars", "tech_maintenance_company"),
        2191: ("autonomous_obstacle_reduction", "Автономное преодоление заграждений", "Autonomous Obstacle Reduction", "super_heavy_tank"),
        2194: ("self_repairing_track_assemblies", "Самовосстанавливающиеся гусеничные узлы", "Self-repairing Track Assemblies", "main_battle_tank"),
        2197: ("networked_siege_coordination_cores", "Сетевые ядра координации осадных платформ", "Networked Siege-coordination Cores", "generic_land_cruiser_chassis"),
    },
    "fighter": {
        2150: ("composite_wing_spars", "Композитные лонжероны крыла", "Composite Wing Spars", "early_fighter"),
        2162: ("digital_flight_controls", "Цифровая электродистанционная система управления", "Digital Flight Controls", "fighter1"),
        2164: ("electronically_scanned_fighter_radar", "РЛС истребителя с электронным сканированием", "Electronically Scanned Fighter Radar", "fighter2"),
        2166: ("helmet_cued_targeting", "Нашлемное целеуказание", "Helmet-cued Targeting", "fighter3"),
        2168: ("fighter_infrared_search_track", "Истребительная система инфракрасного поиска", "Fighter Infrared Search and Track", "jet_fighter1"),
        2173: ("supercruise_turbofans", "Турбовентиляторы сверхзвукового крейсерского полёта", "Supercruise Turbofans", "jet_fighter2"),
        2176: ("low_observable_inlet_geometry", "Малозаметная геометрия воздухозаборников", "Low-observable Inlet Geometry", "guided_missile_3"),
        2179: ("cooperative_fighter_sensor_fusion", "Совместное объединение сенсоров истребителей", "Cooperative Fighter Sensor Fusion", "fighter1"),
        2185: ("adaptive_cycle_engines", "Двигатели адаптивного цикла", "Adaptive-cycle Engines", "fighter2"),
        2188: ("directed_energy_defensive_suites", "Комплексы направленной энергетической защиты", "Directed-energy Defensive Suites", "fighter3"),
        2191: ("autonomous_dogfight_controller", "Автономный контроллер воздушного боя", "Autonomous Dogfight Controller", "jet_fighter1"),
        2194: ("exoatmospheric_boost_stages", "Заатмосферные разгонные ступени", "Exoatmospheric Boost Stages", "jet_fighter2"),
        2197: ("distributed_interceptor_swarms", "Распределённые рои перехватчиков", "Distributed Interceptor Swarms", "guided_missile_3"),
    },
    "air_support": {
        2150: ("ruggedized_targeting_pods", "Защищённые прицельные контейнеры", "Ruggedized Targeting Pods", "CAS1"),
        2162: ("millimeter_wave_ground_radar", "РЛС наземных целей миллиметрового диапазона", "Millimeter-wave Ground Radar", "CAS2"),
        2164: ("precision_glide_bomb_kits", "Комплекты планирующих высокоточных бомб", "Precision Glide-bomb Kits", "CAS3"),
        2166: ("terrain_following_attack_controls", "Система огибания рельефа для штурмовиков", "Terrain-following Attack Controls", "CAS2"),
        2168: ("modular_airframe_armor_pods", "Модульные броневые контейнеры планера", "Modular Airframe Armor Pods", "CAS3"),
        2173: ("tiltrotor_assault_propulsion", "Поворотная винтомоторная установка штурмовика", "Tiltrotor Assault Propulsion", "sp_rockets_glide_bombs"),
        2176: ("loitering_strike_drones", "Барражирующие ударные беспилотники", "Loitering Strike Drones", "nuclear_missile_equipment_1"),
        2179: ("cooperative_close_air_control_links", "Каналы совместного управления авиаподдержкой", "Cooperative Close-air-control Links", "CAS2"),
        2185: ("autonomous_target_discrimination", "Автономное распознавание наземных целей", "Autonomous Target Discrimination", "CAS3"),
        2188: ("directed_energy_countermeasures", "Средства противодействия направленной энергией", "Directed-energy Countermeasures", "CAS2"),
        2191: ("electromagnetic_cannon_pods", "Электромагнитные пушечные контейнеры", "Electromagnetic Cannon Pods", "CAS3"),
        2194: ("unmanned_forward_air_controllers", "Беспилотные передовые авианаводчики", "Unmanned Forward Air Controllers", "sp_rockets_glide_bombs"),
        2197: ("persistent_sensor_strike_loops", "Непрерывные разведывательно-ударные контуры", "Persistent Sensor-strike Loops", "nuclear_missile_equipment_1"),
    },
    "strategic_air": {
        2150: ("storable_liquid_propellants", "Долгохранимые жидкие топлива", "Storable Liquid Propellants", "rocket_engines"),
        2162: ("ring_laser_gyroscopes", "Кольцевые лазерные гироскопы", "Ring-laser Gyroscopes", "improved_rocket_engines"),
        2164: ("terrain_contour_matching", "Сопоставление контура местности", "Terrain-contour Matching", "guided_missile_1"),
        2166: ("hardened_mobile_launchers", "Защищённые мобильные пусковые установки", "Hardened Mobile Launchers", "guided_missile_2"),
        2168: ("digital_warhead_buses", "Цифровые шины боевых частей", "Digital Warhead Buses", "radio_detection"),
        2173: ("low_observable_cruise_missile_skins", "Малозаметная обшивка крылатых ракет", "Low-observable Cruise-missile Skins", "guided_missile_3"),
        2176: ("hypersonic_glide_vehicles", "Гиперзвуковые планирующие блоки", "Hypersonic Glide Vehicles", "guided_missile_3"),
        2179: ("astro_inertial_navigation", "Астроинерциальная навигация", "Astro-inertial Navigation", "improved_rocket_engines"),
        2185: ("reusable_boost_stages", "Многоразовые разгонные ступени", "Reusable Boost Stages", "guided_missile_1"),
        2188: ("maneuvering_reentry_vehicles", "Маневрирующие боевые блоки", "Maneuvering Reentry Vehicles", "guided_missile_2"),
        2191: ("orbital_relay_targeting", "Целеуказание через орбитальные ретрансляторы", "Orbital-relay Targeting", "radio_detection"),
        2194: ("suborbital_skip_glide_guidance", "Наведение суборбитального рикошетирующего полёта", "Suborbital Skip-glide Guidance", "guided_missile_3"),
        2197: ("autonomous_strategic_strike_planning", "Автономное планирование стратегических ударов", "Autonomous Strategic-strike Planning", "guided_missile_3"),
    },
    "naval_support": {
        2150: ("modular_escort_combat_systems", "Модульные боевые системы эскорта", "Modular Escort Combat Systems", "basic_destroyer"),
        2162: ("towed_array_sonar", "Буксируемые гидроакустические антенны", "Towed-array Sonar", "improved_destroyer"),
        2164: ("variable_depth_sonar", "Гидролокаторы переменной глубины", "Variable-depth Sonar", "sonar"),
        2166: ("containerized_escort_missile_cells", "Контейнерные ракетные ячейки эскорта", "Containerized Escort Missile Cells", "improved_sonar"),
        2168: ("escort_integrated_electric_propulsion", "Интегрированная электрическая тяга эскортных кораблей", "Escort Integrated Electric Propulsion", "advanced_destroyer"),
        2173: ("cooperative_convoy_tracking", "Совместное сопровождение конвоев", "Cooperative Convoy Tracking", "modern_destroyer"),
        2176: ("unmanned_mine_countermeasure_boats", "Беспилотные противоминные катера", "Unmanned Mine-countermeasure Boats", "advanced_centimetric_radar"),
        2179: ("over_horizon_escort_radar", "Загоризонтная РЛС эскорта", "Over-the-horizon Escort Radar", "improved_destroyer"),
        2185: ("autonomous_replenishment_craft", "Автономные суда пополнения", "Autonomous Replenishment Craft", "sonar"),
        2188: ("directed_energy_point_defense", "Точечная защита направленной энергией", "Directed-energy Point Defense", "improved_sonar"),
        2191: ("distributed_acoustic_pickets", "Распределённые акустические дозоры", "Distributed Acoustic Pickets", "advanced_destroyer"),
        2194: ("self_repairing_escort_hulls", "Самовосстанавливающиеся корпуса эскорта", "Self-repairing Escort Hulls", "modern_destroyer"),
        2197: ("predictive_convoy_defense_network", "Предиктивная сеть обороны конвоев", "Predictive Convoy-defense Network", "advanced_centimetric_radar"),
    },
    "surface_fleet": {
        2150: ("stabilized_naval_gun_directors", "Стабилизированные корабельные директора огня", "Stabilized Naval-gun Directors", "basic_light_cruiser"),
        2162: ("phased_array_mast_complexes", "Мачтовые комплексы фазированных решёток", "Phased-array Mast Complexes", "improved_light_cruiser"),
        2164: ("modular_vertical_launch_cells", "Модульные установки вертикального пуска", "Modular Vertical-launch Cells", "basic_heavy_cruiser"),
        2166: ("capital_ship_integrated_electric_drive", "Интегрированный электропривод крупных кораблей", "Capital-ship Integrated Electric Drive", "advanced_heavy_cruiser"),
        2168: ("composite_armor_belts", "Композитные броневые пояса", "Composite Armor Belts", "basic_battleship"),
        2173: ("cooperative_fleet_missile_defense", "Совместная противоракетная оборона флота", "Cooperative Fleet Missile Defense", "advanced_battleship"),
        2176: ("unmanned_damage_control_decks", "Необитаемые палубы борьбы за живучесть", "Unmanned Damage-control Decks", "modern_battleship"),
        2179: ("long_range_railgun_fire_control", "Дальнее управление огнём рельсовых орудий", "Long-range Railgun Fire Control", "improved_light_cruiser"),
        2185: ("superconducting_railgun_turrets", "Сверхпроводящие рельсовые башни", "Superconducting Railgun Turrets", "basic_heavy_cruiser"),
        2188: ("drone_carrier_deck_systems", "Палубные комплексы носителей беспилотников", "Drone-carrier Deck Systems", "advanced_heavy_cruiser"),
        2191: ("directed_energy_broadside_defense", "Бортовая защита направленной энергией", "Directed-energy Broadside Defense", "basic_battleship"),
        2194: ("autonomous_capital_ship_cores", "Автономные ядра крупных кораблей", "Autonomous Capital-ship Cores", "advanced_battleship"),
        2197: ("distributed_horizon_targeting", "Распределённое загоризонтное целеуказание", "Distributed Horizon Targeting", "modern_battleship"),
    },
    "subsurface": {
        2150: ("anechoic_tile_bonding", "Крепление звукопоглощающих плиток", "Anechoic Tile Bonding", "basic_submarine"),
        2162: ("pumpjet_propulsors", "Водомётные движители закрытого типа", "Pump-jet Propulsors", "improved_submarine"),
        2164: ("wake_homing_torpedo_seekers", "Головки наведения торпед по кильватерному следу", "Wake-homing Torpedo Seekers", "basic_torpedo"),
        2166: ("conformal_flank_sonars", "Конформные бортовые гидролокаторы", "Conformal Flank Sonars", "advanced_submarine"),
        2168: ("pressure_tolerant_lithium_cells", "Устойчивые к давлению литиевые ячейки", "Pressure-tolerant Lithium Cells", "basic_naval_mines"),
        2173: ("seabed_terrain_navigation", "Навигация по рельефу морского дна", "Seabed-terrain Navigation", "modern_submarine"),
        2176: ("fiber_optic_torpedo_control", "Волоконно-оптическое управление торпедами", "Fiber-optic Torpedo Control", "advanced_naval_mines"),
        2179: ("underwater_vehicle_deployment_bays", "Отсеки развёртывания подводных аппаратов", "Underwater-vehicle Deployment Bays", "improved_submarine"),
        2185: ("magnetohydrodynamic_silent_drive", "Магнитогидродинамический бесшумный движитель", "Magnetohydrodynamic Silent Drive", "basic_torpedo"),
        2188: ("supercavitating_interceptor_torpedoes", "Суперкавитационные торпеды-перехватчики", "Supercavitating Interceptor Torpedoes", "advanced_submarine"),
        2191: ("quantum_magnetometer_arrays", "Массивы квантовых магнитометров", "Quantum Magnetometer Arrays", "basic_naval_mines"),
        2194: ("distributed_abyssal_comm_relays", "Распределённые глубоководные ретрансляторы", "Distributed Abyssal Communication Relays", "modern_submarine"),
        2197: ("self_repairing_pressure_hulls", "Самовосстанавливающиеся прочные корпуса", "Self-repairing Pressure Hulls", "advanced_naval_mines"),
    },
}
