#!/usr/bin/env python3
"""Build A-Discord land and sea strategic regions with seasonal weather."""

from __future__ import annotations

import csv
import re
from collections import Counter, deque
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
STATE_DIR = ROOT / "history" / "states"
REGION_DIR = ROOT / "map" / "strategicregions"
# Load after the vanilla strategic-region file so duplicate numeric keys are
# overridden by A-Discord names instead of showing names such as "Прибалтика".
LOCALISATION = ROOT / "localisation" / "replace" / "strategic_region_names_l_russian.yml"
WEATHER_POSITIONS = ROOT / "map" / "weatherpositions.txt"
GENERATED_MARKER = "# Generated by tools/build_adiscord_strategic_regions.py"


@dataclass(frozen=True)
class Region:
    region_id: int
    slug: str
    russian_name: str
    climate: str
    states: tuple[int, ...]


@dataclass(frozen=True)
class SeaRegion:
    region_id: int
    slug: str
    russian_name: str
    climate: str
    latitude_band: int
    longitude_band: int


SEA_REGIONS = (
    SeaRegion(1, "northwestern-polar-ocean", "Северо-западный полярный океан", "polar_ocean", 0, 0),
    SeaRegion(26, "northern-polar-ocean", "Северный полярный океан", "polar_ocean", 0, 1),
    SeaRegion(27, "northeastern-polar-ocean", "Северо-восточный полярный океан", "polar_ocean", 0, 2),
    SeaRegion(28, "northwestern-sea", "Северо-западное море", "subpolar_ocean", 1, 0),
    SeaRegion(29, "northern-inner-sea", "Северное внутреннее море", "subpolar_ocean", 1, 1),
    SeaRegion(30, "northeastern-sea", "Северо-восточное море", "subpolar_ocean", 1, 2),
    SeaRegion(31, "western-ocean", "Западный океан", "temperate_ocean", 2, 0),
    SeaRegion(32, "central-seas", "Центральные моря", "temperate_ocean", 2, 1),
    SeaRegion(33, "eastern-ocean", "Восточный океан", "temperate_ocean", 2, 2),
    SeaRegion(34, "southwestern-seas", "Юго-западные моря", "warm_ocean", 3, 0),
    SeaRegion(35, "southern-inner-sea", "Южное внутреннее море", "warm_ocean", 3, 1),
    SeaRegion(36, "southeastern-seas", "Юго-восточные моря", "warm_ocean", 3, 2),
    SeaRegion(37, "southwestern-ocean", "Юго-западный океан", "tropical_ocean", 4, 0),
    SeaRegion(38, "southern-ocean", "Южный океан", "tropical_ocean", 4, 1),
    SeaRegion(39, "southeastern-ocean", "Юго-восточный океан", "tropical_ocean", 4, 2),
)

SEA_REGION_GRID = (
    (1, 26, 27),
    (28, 29, 30),
    (31, 32, 33),
    (34, 35, 36),
    (37, 38, 39),
)


REGIONS = (
    Region(2, "outer-lands", "Внешние земли", "temperate_continental", (23,)),
    Region(3, "polar-islands", "Полярные острова", "polar", (47,)),
    Region(4, "western-archipelago", "Западный архипелаг", "cool_maritime", (77,)),
    Region(5, "far-west", "Дальний запад", "cool_maritime", (78,)),
    Region(6, "northern-march", "Северная марка", "cool_maritime", (89, 127, 128, 129, 130, 131, 132, 164)),
    Region(7, "ivan-plains", "Иванские равнины", "cool_continental", (25, 92, 95, 97, 98, 126, 135, 139, 140, 141, 142, 143)),
    Region(8, "western-rimat", "Западный Римат", "temperate_continental", (26, 71, 90, 91, 93, 94, 96, 99, 100, 101, 103, 194, 202, 328)),
    Region(9, "vych-country", "Вычский край", "warm_semiarid", (75, 102, 106, 107, 108, 109, 110, 111, 121, 122, 123, 124, 201, 307, 324, 325)),
    Region(10, "upper-watershed", "Верхний водораздел", "cool_highland", (72, 73, 133, 134, 136, 137, 138, 144, 145, 146, 147, 148, 149, 150, 151, 195, 196, 319, 321, 322)),
    Region(11, "zlatoriver", "Златоречье", "temperate_wet", (80, 82, 157, 158, 159, 161, 162, 163, 199, 315, 316, 317, 318)),
    Region(12, "vorkernsberg", "Воркенсберг", "temperate_continental", (27, 32, 33, 34, 35, 36, 37, 38, 39, 40, 79, 81, 104, 105, 306, 308, 309, 320, 323, 327)),
    Region(13, "southern-rimat", "Южный Римат", "hot_arid", (52, 74, 76, 113, 114, 197, 198, 310, 311, 312, 313, 314, 326)),
    Region(14, "reing-heights", "Рейнгские высоты", "hot_highland", (112, 115, 116, 117)),
    Region(15, "northeastern-forests", "Северо-восточные леса", "cool_maritime", (13, 14, 17, 18, 19, 20, 21, 22, 83, 84, 85, 86, 87, 118, 119, 120, 303)),
    Region(16, "eastern-riverlands", "Восточное междуречье", "temperate_wet", (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 28, 29, 30, 31, 41, 53)),
    Region(17, "antolla-heights", "Антолльские высоты", "cool_highland", (43, 44, 45, 46, 58, 59, 60, 61, 62, 63, 64, 65, 88, 179)),
    Region(18, "zoilong-frontier", "Зойлонгский рубеж", "temperate_highland", (24, 42, 48, 54, 55, 56, 57, 168)),
    Region(19, "grey-belt", "Серая полоса", "arid_highland", (49, 50, 51, 66, 125, 176, 180, 181, 191, 192, 193, 233, 329, 330)),
    Region(20, "irem-wastes", "Иримская пустошь", "arid", (177, 178, 182, 183, 184, 185, 186, 187, 188, 189, 190, 206, 207, 208, 220, 221)),
    Region(21, "western-reactor-zone", "Западная реакторная зона", "arid", (152, 153, 154, 155, 156, 160, 223, 224)),
    Region(22, "loren-corridor", "Лоренский коридор", "arid", (167, 169, 170, 171, 172, 173, 203, 204, 205, 211, 216, 217)),
    Region(23, "southern-reactor-zone", "Южная реакторная зона", "hot_arid", (165, 166, 209, 210, 212, 213, 214, 215, 218, 219, 222)),
    Region(24, "mardar-lowlands", "Мардарская низина", "hot_arid", (67, 68, 69, 70, 174, 175)),
    Region(25, "southern-islands", "Южные острова", "tropical_maritime", (200, 225, 226, 227, 228, 229, 230, 231, 232)),
    Region(40, "kadir-coast", "Кадирское побережье", "hot_arid", tuple(range(234, 265))),
    Region(41, "mazar-oases", "Мазарские оазисы", "hot_arid", tuple(range(265, 287))),
    Region(42, "shahrabad-saltlands", "Шахрабадские солончаки", "hot_highland", (*range(287, 303), 304, 305)),
)


MONTH_RANGES = (
    "0.0 30.0", "0.1 27.1", "0.2 30.2", "0.3 29.3",
    "0.4 30.4", "0.5 29.5", "0.6 30.6", "0.7 30.7",
    "0.8 29.8", "0.9 30.9", "0.10 29.10", "0.11 30.11",
)


TEMPERATURES = {
    "polar_ocean": ((-26, -8), (-25, -7), (-21, -4), (-14, 2), (-7, 7), (-2, 12), (1, 15), (0, 13), (-4, 8), (-11, 2), (-19, -4), (-24, -7)),
    "subpolar_ocean": ((-15, 2), (-14, 3), (-9, 7), (-3, 12), (2, 17), (7, 21), (10, 24), (9, 23), (5, 19), (0, 13), (-6, 7), (-12, 3)),
    "temperate_ocean": ((-4, 12), (-3, 13), (1, 16), (5, 20), (9, 24), (13, 27), (16, 30), (16, 30), (12, 26), (7, 21), (2, 16), (-2, 13)),
    "warm_ocean": ((10, 23), (11, 24), (14, 27), (17, 30), (20, 33), (23, 35), (25, 37), (25, 37), (23, 35), (19, 32), (15, 27), (11, 24)),
    "tropical_ocean": ((20, 31), (20, 31), (21, 32), (22, 33), (23, 34), (24, 35), (25, 36), (25, 36), (24, 35), (23, 34), (22, 33), (21, 32)),
    "polar": ((-32, -15), (-30, -13), (-25, -8), (-16, 0), (-8, 6), (-2, 11), (1, 14), (0, 12), (-5, 7), (-13, 1), (-22, -7), (-29, -12)),
    "cool_maritime": ((-12, 3), (-11, 4), (-7, 8), (-1, 14), (4, 19), (9, 23), (12, 26), (11, 25), (7, 20), (2, 14), (-4, 8), (-9, 4)),
    "cool_continental": ((-18, -3), (-16, 0), (-9, 7), (-1, 15), (5, 21), (10, 27), (13, 30), (11, 28), (6, 22), (-1, 14), (-8, 6), (-15, 0)),
    "temperate_continental": ((-10, 5), (-8, 7), (-3, 13), (3, 19), (8, 24), (13, 29), (16, 32), (14, 30), (9, 25), (3, 18), (-3, 11), (-8, 6)),
    "temperate_wet": ((-6, 7), (-4, 9), (1, 14), (6, 19), (10, 24), (14, 28), (17, 31), (16, 30), (12, 26), (7, 20), (1, 13), (-4, 8)),
    "cool_highland": ((-18, -2), (-16, 0), (-10, 6), (-4, 12), (1, 17), (6, 22), (9, 25), (8, 23), (3, 18), (-3, 11), (-9, 5), (-15, 0)),
    "temperate_highland": ((-10, 4), (-8, 6), (-3, 11), (2, 16), (6, 21), (10, 25), (13, 28), (12, 27), (8, 22), (3, 16), (-3, 10), (-8, 5)),
    "warm_semiarid": ((1, 16), (3, 19), (7, 23), (11, 28), (15, 33), (19, 37), (22, 40), (21, 39), (17, 34), (11, 28), (6, 22), (2, 18)),
    "arid_highland": ((-5, 12), (-3, 15), (2, 20), (7, 25), (12, 30), (16, 34), (19, 37), (18, 36), (13, 31), (7, 25), (1, 18), (-3, 13)),
    "arid": ((2, 18), (4, 21), (9, 27), (14, 33), (19, 38), (23, 42), (26, 45), (25, 44), (20, 39), (14, 32), (8, 25), (3, 19)),
    "hot_arid": ((7, 23), (9, 26), (14, 31), (19, 36), (24, 41), (28, 45), (30, 47), (29, 46), (25, 42), (19, 36), (13, 29), (8, 24)),
    "hot_highland": ((2, 17), (4, 19), (8, 23), (12, 27), (16, 31), (20, 35), (22, 37), (21, 36), (17, 32), (12, 27), (7, 22), (3, 18)),
    "tropical_maritime": ((18, 30), (19, 31), (20, 32), (21, 33), (22, 34), (23, 34), (24, 35), (24, 35), (23, 34), (22, 33), (20, 32), (19, 31)),
}


def phenomenon(climate: str, month: int) -> tuple[float, float, float, float, float, float, float]:
    """Return clear, light rain, heavy rain, snow, blizzard, mud and sandstorm."""
    winter = month in (11, 0, 1)
    shoulder = month in (2, 3, 9, 10)
    summer = month in (5, 6, 7)

    if climate == "polar_ocean":
        return (0.30, 0.04, 0.01, 0.35, 0.18, 0.0, 0.0) if winter else (0.38, 0.14, 0.06, 0.24, 0.09, 0.0, 0.0)
    if climate == "subpolar_ocean":
        if winter:
            return (0.35, 0.18, 0.09, 0.22, 0.08, 0.0, 0.0)
        return (0.35, 0.39, 0.18, 0.01, 0.0, 0.0, 0.0)
    if climate == "temperate_ocean":
        return (0.36, 0.38, 0.18, 0.05 if winter else 0.0, 0.01 if winter else 0.0, 0.0, 0.0)
    if climate == "warm_ocean":
        return (0.40, 0.37, 0.18, 0.0, 0.0, 0.0, 0.0)
    if climate == "tropical_ocean":
        return (0.25, 0.35, 0.32, 0.0, 0.0, 0.0, 0.0) if month in (4, 5, 6, 7, 8) else (0.45, 0.31, 0.18, 0.0, 0.0, 0.0, 0.0)
    if climate == "polar":
        return (0.32, 0.03, 0.01, 0.38, 0.18, 0.03, 0.0) if winter else (0.40, 0.12, 0.04, 0.23, 0.08, 0.12, 0.0)
    if climate == "cool_maritime":
        if winter:
            return (0.36, 0.20, 0.07, 0.22, 0.05, 0.18, 0.0)
        if shoulder:
            return (0.36, 0.31, 0.11, 0.06, 0.01, 0.38, 0.0)
        return (0.43, 0.32, 0.13, 0.0, 0.0, 0.18, 0.0)
    if climate in ("cool_continental", "cool_highland"):
        if winter:
            return (0.39, 0.10, 0.03, 0.31, 0.09, 0.08, 0.0)
        if shoulder:
            return (0.43, 0.25, 0.08, 0.08, 0.01, 0.36, 0.0)
        return (0.51, 0.27, 0.10, 0.0, 0.0, 0.14, 0.0)
    if climate in ("temperate_continental", "temperate_highland"):
        if winter:
            return (0.45, 0.13, 0.03, 0.25, 0.05, 0.10, 0.0)
        if shoulder:
            return (0.43, 0.27, 0.09, 0.05, 0.0, 0.34, 0.0)
        return (0.50, 0.28, 0.12, 0.0, 0.0, 0.14, 0.0)
    if climate == "temperate_wet":
        if winter:
            return (0.35, 0.27, 0.10, 0.15, 0.03, 0.22, 0.0)
        if shoulder:
            return (0.32, 0.37, 0.16, 0.02, 0.0, 0.44, 0.0)
        return (0.38, 0.36, 0.19, 0.0, 0.0, 0.25, 0.0)
    if climate == "warm_semiarid":
        return (0.64, 0.12, 0.04, 0.03 if winter else 0.0, 0.0, 0.12 if shoulder else 0.04, 0.10 if summer else 0.06)
    if climate in ("arid", "arid_highland", "hot_arid"):
        rain_light = 0.08 if winter or shoulder else 0.04
        rain_heavy = 0.03 if winter or shoulder else 0.01
        snow = 0.08 if climate == "arid_highland" and winter else 0.0
        sand = 0.17 if summer else 0.11
        return (0.67, rain_light, rain_heavy, snow, 0.01 if snow else 0.0, 0.07 if shoulder else 0.02, sand)
    if climate == "hot_highland":
        return (0.55, 0.18, 0.07, 0.01 if winter else 0.0, 0.0, 0.16 if shoulder else 0.07, 0.08 if summer else 0.03)
    if climate == "tropical_maritime":
        if month in (4, 5, 6, 7, 8):
            return (0.28, 0.34, 0.28, 0.0, 0.0, 0.30, 0.0)
        return (0.47, 0.29, 0.16, 0.0, 0.0, 0.14, 0.0)
    raise ValueError(f"unknown climate profile: {climate}")


def arctic_water(climate: str, month: int) -> float:
    if climate == "polar_ocean":
        return 0.70 if month in (11, 0, 1) else 0.35 if month in (2, 3, 9, 10) else 0.08
    if climate == "subpolar_ocean":
        return 0.25 if month in (11, 0, 1) else 0.05 if month in (2, 10) else 0.0
    return 0.0


def load_states() -> dict[int, set[int]]:
    states: dict[int, set[int]] = {}
    for path in STATE_DIR.glob("*.txt"):
        text = path.read_text(encoding="utf-8-sig", errors="strict")
        state_match = re.search(r"\bid\s*=\s*(\d+)", text)
        province_match = re.search(r"\bprovinces\s*=\s*\{([^}]*)\}", text, re.DOTALL)
        if not state_match or not province_match:
            continue
        state_id = int(state_match.group(1))
        if state_id in states:
            raise ValueError(f"duplicate state id {state_id}")
        states[state_id] = {int(value) for value in re.findall(r"\d+", province_match.group(1))}
    return states


def load_province_definitions() -> tuple[dict[int, str], dict[int, int]]:
    provinces: dict[int, str] = {}
    colors: dict[int, int] = {}
    with (ROOT / "map" / "definition.csv").open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.reader(handle, delimiter=";"):
            if len(row) >= 5 and row[0].isdigit() and int(row[0]) > 0:
                province_id = int(row[0])
                provinces[province_id] = row[4]
                color = (int(row[1]) << 16) | (int(row[2]) << 8) | int(row[3])
                if color in colors:
                    raise ValueError(f"duplicate province color in definition.csv: {row[1:4]}")
                colors[color] = province_id
    return provinces, colors


def load_province_types() -> dict[int, str]:
    return load_province_definitions()[0]


def load_province_adjacency(
    province_types: dict[int, str], color_to_province: dict[int, int]
) -> dict[int, set[int]]:
    """Read bitmap and special links into the province graph used by the engine."""
    adjacency = {province_id: set() for province_id in province_types}
    with Image.open(ROOT / "map" / "provinces.bmp") as source:
        image = source.convert("RGB")
        width, height = image.size
        red, green, blue = (band.tobytes() for band in image.split())

    previous_row = [-1] * width
    for y in range(height):
        row_start = y * width
        first = -1
        left = -1
        for x in range(width):
            offset = row_start + x
            color = (red[offset] << 16) | (green[offset] << 8) | blue[offset]
            try:
                province_id = color_to_province[color]
            except KeyError as exc:
                raise ValueError(
                    f"provinces.bmp uses undefined color {color >> 16};{(color >> 8) & 255};{color & 255} at {x},{y}"
                ) from exc
            if x == 0:
                first = province_id
            elif province_id != left:
                adjacency[province_id].add(left)
                adjacency[left].add(province_id)
            above = previous_row[x]
            if above != -1 and province_id != above:
                adjacency[province_id].add(above)
                adjacency[above].add(province_id)
            previous_row[x] = province_id
            left = province_id

        # Clausewitz maps wrap horizontally, so the two map edges are adjacent.
        if first != left:
            adjacency[first].add(left)
            adjacency[left].add(first)

    adjacency_path = ROOT / "map" / "adjacencies.csv"
    if adjacency_path.exists():
        with adjacency_path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.reader(handle, delimiter=";"):
                if len(row) < 2 or not row[0].isdigit() or not row[1].isdigit():
                    continue
                first, second = int(row[0]), int(row[1])
                if first in adjacency and second in adjacency:
                    adjacency[first].add(second)
                    adjacency[second].add(first)
    return adjacency


def connected_components(nodes: set[int], adjacency: dict[int, set[int]]) -> list[set[int]]:
    remaining = set(nodes)
    components: list[set[int]] = []
    while remaining:
        start = min(remaining)
        component = {start}
        queue = deque((start,))
        remaining.remove(start)
        while queue:
            province_id = queue.popleft()
            for neighbour in adjacency[province_id]:
                if neighbour in remaining:
                    remaining.remove(neighbour)
                    component.add(neighbour)
                    queue.append(neighbour)
        components.append(component)
    return sorted(components, key=lambda component: (-len(component), min(component)))


def partition_connected_sea(
    sea: set[int],
    adjacency: dict[int, set[int]],
    positions: dict[int, tuple[float, float, float]],
) -> dict[int, set[int]]:
    """Partition one connected ocean with a seeded BFS, preserving connectivity."""
    seeds: dict[int, int] = {}
    for sea_region in SEA_REGIONS:
        candidates = [
            province_id
            for province_id in sea
            if sea_region_id_for(positions[province_id]) == sea_region.region_id
        ]
        if not candidates:
            raise ValueError(f"sea strategic region {sea_region.region_id} has no seed candidates")
        center_x = sum(positions[province_id][0] for province_id in candidates) / len(candidates)
        center_z = sum(positions[province_id][2] for province_id in candidates) / len(candidates)
        seeds[sea_region.region_id] = min(
            candidates,
            key=lambda province_id: (
                (positions[province_id][0] - center_x) ** 2 + (positions[province_id][2] - center_z) ** 2,
                province_id,
            ),
        )

    assignments = {province_id: region_id for region_id, province_id in seeds.items()}
    queue = deque(seeds[region_id] for region_id in sorted(seeds))
    while queue:
        province_id = queue.popleft()
        region_id = assignments[province_id]
        for neighbour in sorted(adjacency[province_id]):
            if neighbour in sea and neighbour not in assignments:
                assignments[neighbour] = region_id
                queue.append(neighbour)
    if set(assignments) != sea:
        raise ValueError("main ocean component could not be fully partitioned")

    partition = {region.region_id: set() for region in SEA_REGIONS}
    for province_id, region_id in assignments.items():
        partition[region_id].add(province_id)
    return partition


def load_province_positions() -> dict[int, tuple[float, float, float]]:
    positions: dict[int, tuple[float, float, float]] = {}
    with (ROOT / "map" / "unitstacks.txt").open(encoding="utf-8-sig", errors="strict") as handle:
        for line in handle:
            fields = line.strip().split(";")
            if len(fields) < 5 or not fields[0].isdigit() or fields[1] != "0":
                continue
            province_id = int(fields[0])
            positions.setdefault(province_id, (float(fields[2]), float(fields[3]), float(fields[4])))
    return positions


def format_provinces(provinces: set[int]) -> str:
    values = sorted(provinces)
    lines = []
    for start in range(0, len(values), 24):
        lines.append("\t\t" + " ".join(str(value) for value in values[start:start + 24]))
    return "\n".join(lines)


def format_weather(climate: str) -> str:
    lines = ["\tweather={"]
    for month, date_range in enumerate(MONTH_RANGES):
        low, high = TEMPERATURES[climate][month]
        clear, light, heavy, snow, blizzard, mud, sandstorm = phenomenon(climate, month)
        lines.extend((
            "\t\tperiod={",
            f"\t\t\tbetween={{ {date_range} }}",
            f"\t\t\ttemperature={{ {low:.1f} {high:.1f} }}",
            f"\t\t\tno_phenomenon={clear:.2f}",
            f"\t\t\train_light={light:.2f}",
            f"\t\t\train_heavy={heavy:.2f}",
            f"\t\t\tsnow={snow:.2f}",
            f"\t\t\tblizzard={blizzard:.2f}",
            f"\t\t\tarctic_water={arctic_water(climate, month):.2f}",
            f"\t\t\tmud={mud:.2f}",
            f"\t\t\tsandstorm={sandstorm:.2f}",
            "\t\t\tmin_snow_level=0.00",
            "\t\t}",
        ))
    lines.append("\t}")
    return "\n".join(lines)


def representative_positions(
    provinces: set[int], positions: dict[int, tuple[float, float, float]]
) -> list[tuple[float, float, float]]:
    available = [positions[province_id] for province_id in provinces if province_id in positions]
    if not available:
        raise ValueError("strategic region has no unit-stack positions")
    if len(available) == 1:
        return available

    x_span = max(point[0] for point in available) - min(point[0] for point in available)
    z_span = max(point[2] for point in available) - min(point[2] for point in available)
    axis = 0 if x_span >= z_span else 2
    ordered = sorted(available, key=lambda point: point[axis])
    if len(available) < 24:
        return [ordered[len(ordered) // 2]]
    return [ordered[len(ordered) // 3], ordered[(2 * len(ordered)) // 3]]


def sea_region_id_for(position: tuple[float, float, float]) -> int:
    x, _height, z = position
    latitude_band = 0 if z >= 1600 else 1 if z >= 1250 else 2 if z >= 900 else 3 if z >= 550 else 4
    longitude_band = 0 if x < 1800 else 1 if x < 3800 else 2
    return SEA_REGION_GRID[latitude_band][longitude_band]


def validate_manifest(states: dict[int, set[int]]) -> None:
    assigned: dict[int, int] = {}
    for region in REGIONS:
        if region.climate not in TEMPERATURES:
            raise ValueError(f"region {region.region_id} uses unknown climate {region.climate}")
        for state_id in region.states:
            if state_id not in states:
                raise ValueError(f"region {region.region_id} references missing state {state_id}")
            if state_id in assigned:
                raise ValueError(f"state {state_id} is in regions {assigned[state_id]} and {region.region_id}")
            assigned[state_id] = region.region_id
    missing = sorted(set(states) - set(assigned))
    if missing:
        raise ValueError(f"states without a strategic region: {missing}")


def build() -> None:
    states = load_states()
    validate_manifest(states)
    province_types, color_to_province = load_province_definitions()
    non_sea = {province_id for province_id, province_type in province_types.items() if province_type != "sea"}
    sea = {province_id for province_id, province_type in province_types.items() if province_type == "sea"}
    state_provinces = set().union(*states.values())
    unknown = state_provinces - non_sea
    if unknown:
        raise ValueError(f"state provinces absent from non-sea definition rows: {sorted(unknown)}")

    for path in REGION_DIR.glob("*.txt"):
        text = path.read_text(encoding="utf-8-sig", errors="strict")
        if path.name in ("1-sea.txt", "2-land.txt") or text.startswith(GENERATED_MARKER):
            path.unlink()

    province_positions = load_province_positions()
    for province_id in sea:
        if province_id not in province_positions:
            raise ValueError(f"sea province {province_id} has no unit-stack position")

    adjacency = load_province_adjacency(province_types, color_to_province)
    sea_components = connected_components(sea, adjacency)
    if not sea_components:
        raise ValueError("map contains no sea provinces")
    main_ocean = sea_components[0]

    region_provinces: dict[int, set[int]] = {}
    land_region_by_province: dict[int, int] = {}
    for region in REGIONS:
        provinces = set().union(*(states[state_id] for state_id in region.states))
        if region.region_id == 2:
            provinces |= non_sea - state_provinces
        region_provinces[region.region_id] = provinces
        for province_id in provinces:
            land_region_by_province[province_id] = region.region_id

    # Inland lakes must belong to their surrounding land region. Combining them
    # with the ocean makes Clausewitz report a fractioned naval strategic region.
    for component in sea_components[1:]:
        neighbouring_land = Counter(
            land_region_by_province[neighbour]
            for province_id in component
            for neighbour in adjacency[province_id]
            if neighbour in land_region_by_province
        )
        if not neighbouring_land:
            raise ValueError(f"isolated sea component {sorted(component)} has no neighbouring land region")
        region_id = min(neighbouring_land, key=lambda candidate: (-neighbouring_land[candidate], candidate))
        region_provinces[region_id].update(component)

    region_provinces.update(partition_connected_sea(main_ocean, adjacency, province_positions))

    sea_by_id = {region.region_id: region for region in SEA_REGIONS}
    for region_id, region in sorted(sea_by_id.items()):
        provinces = region_provinces.get(region_id, set())
        if not provinces:
            raise ValueError(f"sea strategic region {region_id} is empty")
        content = (
            f"{GENERATED_MARKER}\n"
            "strategic_region={\n"
            f"\tid={region.region_id}\n"
            f"\tname=\"STRATEGICREGION_{region.region_id}\"\n"
            "\tprovinces={\n"
            f"{format_provinces(provinces)}\n"
            "\t}\n"
            "\tnaval_terrain=water_deep_ocean\n"
            f"{format_weather(region.climate)}\n"
            "}\n"
        )
        path = REGION_DIR / f"{region.region_id}-{region.slug}.txt"
        path.write_text(content, encoding="utf-8", newline="\n")

    for region in REGIONS:
        provinces = region_provinces[region.region_id]
        content = (
            f"{GENERATED_MARKER}\n"
            "strategic_region={\n"
            f"\tid={region.region_id}\n"
            f"\tname=\"STRATEGICREGION_{region.region_id}\"\n"
            "\tprovinces={\n"
            f"{format_provinces(provinces)}\n"
            "\t}\n"
            f"{format_weather(region.climate)}\n"
            "}\n"
        )
        path = REGION_DIR / f"{region.region_id}-{region.slug}.txt"
        path.write_text(content, encoding="utf-8", newline="\n")

    LOCALISATION.parent.mkdir(parents=True, exist_ok=True)
    localisation_lines = ["\ufeffl_russian:"]
    for region in sorted((*SEA_REGIONS, *REGIONS), key=lambda item: item.region_id):
        localisation_lines.append(f' STRATEGICREGION_{region.region_id}: "{region.russian_name}"')
    LOCALISATION.write_text("\n".join(localisation_lines) + "\n", encoding="utf-8", newline="\n")

    weather_lines = []
    for region_id in sorted(region_provinces):
        size = "big" if len(region_provinces[region_id]) >= 100 else "small"
        for x, height, z in representative_positions(region_provinces[region_id], province_positions):
            weather_lines.append(f"{region_id};{x:.2f};{height:.2f};{z:.2f};{size}")
    WEATHER_POSITIONS.write_text("\n".join(weather_lines) + "\n", encoding="utf-8", newline="\n")

    print(f"Built {len(REGIONS)} land and {len(SEA_REGIONS)} sea strategic regions for {len(states)} states.")


if __name__ == "__main__":
    build()
